package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Area generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "AREA")
public class Area implements java.io.Serializable {

	private long idArea;
	private Area area;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<AreaPerfil> areaPerfils = new HashSet<AreaPerfil>(0);
	private Set<PoliticaValor> politicaValors = new HashSet<PoliticaValor>(0);
	private Set<DocumentoClasificacion> documentoClasificacions = new HashSet<DocumentoClasificacion>(
			0);
	private Set<AreaPersona> areaPersonas = new HashSet<AreaPersona>(0);
	private Set<AreaEquivalente> areaEquivalentes = new HashSet<AreaEquivalente>(
			0);
	private Set<AreaEmpresa> areaEmpresas = new HashSet<AreaEmpresa>(0);
	private Set<Area> areas = new HashSet<Area>(0);

	public Area() {
	}

	public Area(long idArea, String descripcion, boolean estatusRegistro) {
		this.idArea = idArea;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public Area(long idArea, Area area, String descripcion, String significado,
			boolean estatusRegistro, Set<AreaPerfil> areaPerfils,
			Set<PoliticaValor> politicaValors,
			Set<DocumentoClasificacion> documentoClasificacions,
			 Set<AreaPersona> areaPersonas,
			Set<AreaEquivalente> areaEquivalentes,
			Set<AreaEmpresa> areaEmpresas, Set<Area> areas) {
		this.idArea = idArea;
		this.area = area;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.areaPerfils = areaPerfils;
		this.politicaValors = politicaValors;
		this.documentoClasificacions = documentoClasificacions;
		this.areaPersonas = areaPersonas;
		this.areaEquivalentes = areaEquivalentes;
		this.areaEmpresas = areaEmpresas;
		this.areas = areas;
	}

	@Id
	@Column(name = "ID_AREA", unique = true, nullable = false)
	public long getIdArea() {
		return this.idArea;
	}

	public void setIdArea(long idArea) {
		this.idArea = idArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA_RELACIONADA")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<AreaPerfil> getAreaPerfils() {
		return this.areaPerfils;
	}

	public void setAreaPerfils(Set<AreaPerfil> areaPerfils) {
		this.areaPerfils = areaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<PoliticaValor> getPoliticaValors() {
		return this.politicaValors;
	}

	public void setPoliticaValors(Set<PoliticaValor> politicaValors) {
		this.politicaValors = politicaValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<DocumentoClasificacion> getDocumentoClasificacions() {
		return this.documentoClasificacions;
	}

	public void setDocumentoClasificacions(
			Set<DocumentoClasificacion> documentoClasificacions) {
		this.documentoClasificacions = documentoClasificacions;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<AreaPersona> getAreaPersonas() {
		return this.areaPersonas;
	}

	public void setAreaPersonas(Set<AreaPersona> areaPersonas) {
		this.areaPersonas = areaPersonas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<AreaEquivalente> getAreaEquivalentes() {
		return this.areaEquivalentes;
	}

	public void setAreaEquivalentes(Set<AreaEquivalente> areaEquivalentes) {
		this.areaEquivalentes = areaEquivalentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<AreaEmpresa> getAreaEmpresas() {
		return this.areaEmpresas;
	}

	public void setAreaEmpresas(Set<AreaEmpresa> areaEmpresas) {
		this.areaEmpresas = areaEmpresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

}
