package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;


/**
 * AreaPersona generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "AREA_PERSONA")
@DynamicUpdate
public class AreaPersona implements java.io.Serializable {

	private long idAreaPersona;
	private Area area;
	private Persona persona;
	private boolean principal;
	private boolean confirmada;
	private boolean personal;


	public AreaPersona() {
	}

	public AreaPersona(long idAreaPersona, Area area, Persona persona,
			boolean principal, boolean confirmada, boolean personal) {
		this.idAreaPersona = idAreaPersona;
		this.area = area;
		this.persona = persona;
		this.principal = principal;
		this.confirmada = confirmada;
		this.personal = personal;
	}

	@Id
	@SequenceGenerator(name="seq_area_persona", sequenceName=Constante.SECUENCIA_BD_AREA_PERSONA, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_area_persona")
	@Column(name = "ID_AREA_PERSONA", unique = true, nullable = false)
	public long getIdAreaPersona() {
		return this.idAreaPersona;
	}

	public void setIdAreaPersona(long idAreaPersona) {
		this.idAreaPersona = idAreaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "principal", nullable = false)
	public boolean isPrincipal() {
		return this.principal;
	}

	public void setPrincipal(boolean principal) {
		this.principal = principal;
	}

	@Column(name = "confirmada", nullable = false)
	public boolean isConfirmada() {
		return this.confirmada;
	}

	public void setConfirmada(boolean confirmada) {
		this.confirmada = confirmada;
	}
	
	@Column(name = "personal", nullable = false)
	public boolean isPersonal() {
		return this.personal;
	}

	public void setPersonal(boolean personal) {
		this.personal = personal;
	}
}
