package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * AreaPerfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "AREA_PERFIL")
public class AreaPerfil implements java.io.Serializable {

	private long idAreaPerfil;
	private Perfil perfil;
	private Area area;
	private boolean confirmada;
	private Set<BitacoraPosicion> bitacoraPosicions = new HashSet<BitacoraPosicion>(
			0);

	public AreaPerfil() {
	}

	public AreaPerfil(long idAreaPerfil, Perfil perfil, Area area,
			boolean confirmada, Set<BitacoraPosicion> bitacoraPosicions) {
		this.idAreaPerfil = idAreaPerfil;
		this.perfil = perfil;
		this.area = area;
		this.confirmada = confirmada;
		this.bitacoraPosicions = bitacoraPosicions;
	}

	@Id
	@SequenceGenerator(name="seq_area_perfil", sequenceName=Constante.SECUENCIA_BD_AREA_PERFIL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_area_perfil")
	@Column(name = "ID_AREA_PERFIL", unique = true, nullable = false)
	public long getIdAreaPerfil() {
		return this.idAreaPerfil;
	}

	public void setIdAreaPerfil(long idAreaPerfil) {
		this.idAreaPerfil = idAreaPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "confirmada", nullable = false)
	public boolean isConfirmada() {
		return this.confirmada;
	}

	public void setConfirmada(boolean confirmada) {
		this.confirmada = confirmada;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaPerfil")
	public Set<BitacoraPosicion> getBitacoraPosicions() {
		return this.bitacoraPosicions;
	}

	public void setBitacoraPosicions(Set<BitacoraPosicion> bitacoraPosicions) {
		this.bitacoraPosicions = bitacoraPosicions;
	}

}
