package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaInteres generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "AREA_INTERES")
public class AreaInteres implements java.io.Serializable {

	private long idAreaInteres;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Preferencia> preferencias = new HashSet<Preferencia>(0);

	public AreaInteres() {
	}

	public AreaInteres(long idAreaInteres, String descripcion) {
		this.idAreaInteres = idAreaInteres;
		this.descripcion = descripcion;
	}

	public AreaInteres(long idAreaInteres, String descripcion,
			String significado, boolean estatusRegistro,
			Set<Preferencia> preferencias) {
		this.idAreaInteres = idAreaInteres;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.preferencias = preferencias;
	}

	@Id
	@Column(name = "ID_AREA_INTERES", unique = true, nullable = false)
	public long getIdAreaInteres() {
		return this.idAreaInteres;
	}

	public void setIdAreaInteres(long idAreaInteres) {
		this.idAreaInteres = idAreaInteres;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaInteres")
	public Set<Preferencia> getPreferencias() {
		return this.preferencias;
	}

	public void setPreferencias(Set<Preferencia> preferencias) {
		this.preferencias = preferencias;
	}

}
