package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Asentamiento generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ASENTAMIENTO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"clave_asentamiento", "id_tipo_asentamiento", "id_municipio" }))
public class Asentamiento implements java.io.Serializable {

	private long idAsentamiento;
	private Municipio municipio;
	private Ciudad ciudad;
	private TipoAsentamiento tipoAsentamiento;
	private String claveAsentamiento;
	private String descripcion;
	private String codigoPostal;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private boolean estatusRegistro;
	private Set<BitacoraDomicilio> bitacoraDomicilios = new HashSet<BitacoraDomicilio>(
			0);
	private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

	public Asentamiento() {
	}

	public Asentamiento(long idAsentamiento, Municipio municipio,
			TipoAsentamiento tipoAsentamiento, String claveAsentamiento,
			String descripcion, String codigoPostal) {
		this.idAsentamiento = idAsentamiento;
		this.municipio = municipio;
		this.tipoAsentamiento = tipoAsentamiento;
		this.claveAsentamiento = claveAsentamiento;
		this.descripcion = descripcion;
		this.codigoPostal = codigoPostal;
	}

	public Asentamiento(long idAsentamiento, Municipio municipio,
			Ciudad ciudad, TipoAsentamiento tipoAsentamiento,
			String claveAsentamiento, String descripcion, String codigoPostal,
			BigDecimal latitude, BigDecimal longitude, boolean estatusRegistro,
			Set<BitacoraDomicilio> bitacoraDomicilios, Set<Domicilio> domicilios) {
		this.idAsentamiento = idAsentamiento;
		this.municipio = municipio;
		this.ciudad = ciudad;
		this.tipoAsentamiento = tipoAsentamiento;
		this.claveAsentamiento = claveAsentamiento;
		this.descripcion = descripcion;
		this.codigoPostal = codigoPostal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.estatusRegistro = estatusRegistro;
		this.bitacoraDomicilios = bitacoraDomicilios;
		this.domicilios = domicilios;
	}

	@Id
	@Column(name = "id_asentamiento", unique = true, nullable = false)
	public long getIdAsentamiento() {
		return this.idAsentamiento;
	}

	public void setIdAsentamiento(long idAsentamiento) {
		this.idAsentamiento = idAsentamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudad")
	public Ciudad getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_asentamiento", nullable = false)
	public TipoAsentamiento getTipoAsentamiento() {
		return this.tipoAsentamiento;
	}

	public void setTipoAsentamiento(TipoAsentamiento tipoAsentamiento) {
		this.tipoAsentamiento = tipoAsentamiento;
	}

	@Column(name = "clave_asentamiento", nullable = false, length = 10)
	public String getClaveAsentamiento() {
		return this.claveAsentamiento;
	}

	public void setClaveAsentamiento(String claveAsentamiento) {
		this.claveAsentamiento = claveAsentamiento;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "codigo_postal", nullable = false, length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "latitude", precision = 131089, scale = 0)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 131089, scale = 0)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asentamiento")
	public Set<BitacoraDomicilio> getBitacoraDomicilios() {
		return this.bitacoraDomicilios;
	}

	public void setBitacoraDomicilios(Set<BitacoraDomicilio> bitacoraDomicilios) {
		this.bitacoraDomicilios = bitacoraDomicilios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asentamiento")
	public Set<Domicilio> getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Set<Domicilio> domicilios) {
		this.domicilios = domicilios;
	}

}
