package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Automovil generated by hbm2java
 */
@Entity
@Table(name = "automovil")
@DynamicUpdate
public class Automovil implements java.io.Serializable {

	private long idPersona;
	private Compensacion compensacion;
	private Boolean perteneceCompania;
	private String marca;
	private String modelo;
	private Boolean gastosPagados;
	private Boolean opcionCompra;
	private Short tiempoCambio;

	public Automovil() {
	}

	public Automovil(Compensacion compensacion) {
		this.compensacion = compensacion;
	}

	public Automovil(Compensacion compensacion, Boolean perteneceCompania,
			String marca, String modelo, Boolean gastosPagados,
			Boolean opcionCompra, Short tiempoCambio) {
		this.compensacion = compensacion;
		this.perteneceCompania = perteneceCompania;
		this.marca = marca;
		this.modelo = modelo;
		this.gastosPagados = gastosPagados;
		this.opcionCompra = opcionCompra;
		this.tiempoCambio = tiempoCambio;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "compensacion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_persona", unique = true, nullable = false)
	public long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(long idPersona) {
		this.idPersona = idPersona;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Compensacion getCompensacion() {
		return this.compensacion;
	}

	public void setCompensacion(Compensacion compensacion) {
		this.compensacion = compensacion;
	}

	@Column(name = "pertenece_compania")
	public Boolean getPerteneceCompania() {
		return this.perteneceCompania;
	}

	public void setPerteneceCompania(Boolean perteneceCompania) {
		this.perteneceCompania = perteneceCompania;
	}

	@Column(name = "marca", length = 100)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo", length = 100)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "gastos_pagados")
	public Boolean getGastosPagados() {
		return this.gastosPagados;
	}

	public void setGastosPagados(Boolean gastosPagados) {
		this.gastosPagados = gastosPagados;
	}

	@Column(name = "opcion_compra")
	public Boolean getOpcionCompra() {
		return this.opcionCompra;
	}

	public void setOpcionCompra(Boolean opcionCompra) {
		this.opcionCompra = opcionCompra;
	}

	@Column(name = "tiempo_cambio")
	public Short getTiempoCambio() {
		return this.tiempoCambio;
	}

	public void setTiempoCambio(Short tiempoCambio) {
		this.tiempoCambio = tiempoCambio;
	}

}
