package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aviso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "AVISO", uniqueConstraints = @UniqueConstraint(columnNames = "clave_aviso"))
public class Aviso implements java.io.Serializable {

	private long idAviso;
	private TipoAviso tipoAviso;
	private String texto;
	private String claveAviso;
	private Set<AvisoCandidato> avisoCandidatos = new HashSet<AvisoCandidato>(0);

	public Aviso() {
	}

	public Aviso(long idAviso, String claveAviso) {
		this.idAviso = idAviso;
		this.claveAviso = claveAviso;
	}

	public Aviso(long idAviso, TipoAviso tipoAviso, String texto,
			String claveAviso, Set<AvisoCandidato> avisoCandidatos) {
		this.idAviso = idAviso;
		this.tipoAviso = tipoAviso;
		this.texto = texto;
		this.claveAviso = claveAviso;
		this.avisoCandidatos = avisoCandidatos;
	}

	@Id
	@Column(name = "ID_AVISO", unique = true, nullable = false)
	public long getIdAviso() {
		return this.idAviso;
	}

	public void setIdAviso(long idAviso) {
		this.idAviso = idAviso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_AVISO")
	public TipoAviso getTipoAviso() {
		return this.tipoAviso;
	}

	public void setTipoAviso(TipoAviso tipoAviso) {
		this.tipoAviso = tipoAviso;
	}

	@Column(name = "TEXTO", length = 250)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "CLAVE_AVISO", unique = true, nullable = false, length = 50)
	public String getClaveAviso() {
		return this.claveAviso;
	}

	public void setClaveAviso(String claveAviso) {
		this.claveAviso = claveAviso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aviso")
	public Set<AvisoCandidato> getAvisoCandidatos() {
		return this.avisoCandidatos;
	}

	public void setAvisoCandidatos(Set<AvisoCandidato> avisoCandidatos) {
		this.avisoCandidatos = avisoCandidatos;
	}

}
