package net.tce.model;

// Generated Dec 20, 2017 6:46:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * BitacoraPoliticaValor generated by hbm2java
 */
@Entity
@Table(name = "bitacora_politica_valor")
@DynamicUpdate
public class BitacoraPoliticaValor implements java.io.Serializable {

	private long idBitacoraPoliticaValor;
	private TipoGenero tipoGenero;
	private BitacoraPosicion bitacoraPosicion;
	private TipoDispViajar tipoDispViajar;
	private Politica politica;
	private GradoAcademico gradoAcademico;
	private EstadoCivil estadoCivil;
	private Idioma idioma;
	private EstatusEscolar estatusEscolar;
	private Dominio dominio;
	private Short ponderacion;
	private String descripcion;
	private String valor;
	private String valorMin;
	private String valorMax;
	private Long idPoliticaValor;
	private Boolean escolaridadMax;
	private Long idPoliticaMValor;

	public BitacoraPoliticaValor() {
	}

	public BitacoraPoliticaValor(long idBitacoraPoliticaValor, Politica politica) {
		this.idBitacoraPoliticaValor = idBitacoraPoliticaValor;
		this.politica = politica;
	}

	public BitacoraPoliticaValor(long idBitacoraPoliticaValor,
			TipoGenero tipoGenero, BitacoraPosicion bitacoraPosicion,
			TipoDispViajar tipoDispViajar, Politica politica,
			GradoAcademico gradoAcademico, EstadoCivil estadoCivil,
			Idioma idioma, EstatusEscolar estatusEscolar, Dominio dominio,
			Short ponderacion, String descripcion, String valor,
			String valorMin, String valorMax, Long idPoliticaValor,
			Boolean escolaridadMax, Long idPoliticaMValor) {
		this.idBitacoraPoliticaValor = idBitacoraPoliticaValor;
		this.tipoGenero = tipoGenero;
		this.bitacoraPosicion = bitacoraPosicion;
		this.tipoDispViajar = tipoDispViajar;
		this.politica = politica;
		this.gradoAcademico = gradoAcademico;
		this.estadoCivil = estadoCivil;
		this.idioma = idioma;
		this.estatusEscolar = estatusEscolar;
		this.dominio = dominio;
		this.ponderacion = ponderacion;
		this.descripcion = descripcion;
		this.valor = valor;
		this.valorMin = valorMin;
		this.valorMax = valorMax;
		this.idPoliticaValor = idPoliticaValor;
		this.escolaridadMax = escolaridadMax;
		this.idPoliticaMValor = idPoliticaMValor;
	}

	@Id
	@Column(name = "id_bitacora_politica_valor", unique = true, nullable = false)
	@SequenceGenerator(name="seq_btc_politica_valor", sequenceName=Constante.SECUENCIA_BD_BTC_POLITICA_VALOR, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_btc_politica_valor")
	public long getIdBitacoraPoliticaValor() {
		return this.idBitacoraPoliticaValor;
	}

	public void setIdBitacoraPoliticaValor(long idBitacoraPoliticaValor) {
		this.idBitacoraPoliticaValor = idBitacoraPoliticaValor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_genero")
	public TipoGenero getTipoGenero() {
		return this.tipoGenero;
	}

	public void setTipoGenero(TipoGenero tipoGenero) {
		this.tipoGenero = tipoGenero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_posicion", nullable = false)
	public BitacoraPosicion getBitacoraPosicion() {
		return this.bitacoraPosicion;
	}

	public void setBitacoraPosicion(BitacoraPosicion bitacoraPosicion) {
		this.bitacoraPosicion = bitacoraPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_disp_viajar")
	public TipoDispViajar getTipoDispViajar() {
		return this.tipoDispViajar;
	}

	public void setTipoDispViajar(TipoDispViajar tipoDispViajar) {
		this.tipoDispViajar = tipoDispViajar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_politica", nullable = false)
	public Politica getPolitica() {
		return this.politica;
	}

	public void setPolitica(Politica politica) {
		this.politica = politica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_academico")
	public GradoAcademico getGradoAcademico() {
		return this.gradoAcademico;
	}

	public void setGradoAcademico(GradoAcademico gradoAcademico) {
		this.gradoAcademico = gradoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_civil")
	public EstadoCivil getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(EstadoCivil estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_idioma")
	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_escolar")
	public EstatusEscolar getEstatusEscolar() {
		return this.estatusEscolar;
	}

	public void setEstatusEscolar(EstatusEscolar estatusEscolar) {
		this.estatusEscolar = estatusEscolar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dominio")
	public Dominio getDominio() {
		return this.dominio;
	}

	public void setDominio(Dominio dominio) {
		this.dominio = dominio;
	}

	@Column(name = "ponderacion")
	public Short getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Short ponderacion) {
		this.ponderacion = ponderacion;
	}

	@Column(name = "descripcion", length = 1500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor", length = 300)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "valor_min", length = 300)
	public String getValorMin() {
		return this.valorMin;
	}

	public void setValorMin(String valorMin) {
		this.valorMin = valorMin;
	}

	@Column(name = "valor_max", length = 300)
	public String getValorMax() {
		return this.valorMax;
	}

	public void setValorMax(String valorMax) {
		this.valorMax = valorMax;
	}
	
	@Column(name = "id_politica_valor", nullable = false)
	public Long getIdPoliticaValor() {
		return this.idPoliticaValor;
	}

	public void setIdPoliticaValor(Long idPoliticaValor) {
		this.idPoliticaValor = idPoliticaValor;
	}
	
	@Column(name = "escolaridad_max")
	public Boolean getEscolaridadMax() {
		return this.escolaridadMax;
	}

	public void setEscolaridadMax(Boolean escolaridadMax) {
		this.escolaridadMax = escolaridadMax;
	}

	@Column(name = "id_politica_m_valor")
	public Long getIdPoliticaMValor() {
		return this.idPoliticaMValor;
	}

	public void setIdPoliticaMValor(Long idPoliticaMValor) {
		this.idPoliticaMValor = idPoliticaMValor;
	}

}
