package net.tce.model;
// Generated Jan 15, 2020 8:17:29 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * BitacoraModelorsc generated by hbm2java
 */
@Entity
@Table(name = "bitacora_modelorsc")
public class BitacoraModelorsc implements java.io.Serializable {

	private long idBitacoraModelorsc;
	private Long idModeloRsc;
	private Long idModeloRscPos;
	private Long idTipoModeloRsc;
	private Long idPerfilPosicion;
	private Long idRol;
	private String nombre;
	private String descripcion;
	private Boolean activo;
	private Boolean monitor;
	private Boolean principal;
	private Set<BitacoraTrack> bitacoraTracks = new HashSet<BitacoraTrack>(0);

	public BitacoraModelorsc() {
	}

	public BitacoraModelorsc(long idBitacoraModelorsc) {
		this.idBitacoraModelorsc = idBitacoraModelorsc;
	}

	public BitacoraModelorsc(long idBitacoraModelorsc, Long idModeloRsc, Long idModeloRscPos, Long idTipoModeloRsc,
			Long idPerfilPosicion, Long idRol, String nombre, String descripcion, Boolean activo, Boolean monitor,
			Boolean principal, Set<BitacoraTrack> bitacoraTracks) {
		this.idBitacoraModelorsc = idBitacoraModelorsc;
		this.idModeloRsc = idModeloRsc;
		this.idModeloRscPos = idModeloRscPos;
		this.idTipoModeloRsc = idTipoModeloRsc;
		this.idPerfilPosicion = idPerfilPosicion;
		this.idRol = idRol;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activo = activo;
		this.monitor = monitor;
		this.principal = principal;
		this.bitacoraTracks = bitacoraTracks;
	}

	@Id
	@SequenceGenerator(name="seq_bitacora_modelorsc", sequenceName=Constante.SECUENCIA_BD_BTC_MOD_RSC, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_bitacora_modelorsc")
	@Column(name = "id_bitacora_modelorsc", unique = true, nullable = false)
	public long getIdBitacoraModelorsc() {
		return this.idBitacoraModelorsc;
	}

	public void setIdBitacoraModelorsc(long idBitacoraModelorsc) {
		this.idBitacoraModelorsc = idBitacoraModelorsc;
	}

	@Column(name = "id_modelo_rsc")
	public Long getIdModeloRsc() {
		return this.idModeloRsc;
	}

	public void setIdModeloRsc(Long idModeloRsc) {
		this.idModeloRsc = idModeloRsc;
	}

	@Column(name = "id_modelo_rsc_pos")
	public Long getIdModeloRscPos() {
		return this.idModeloRscPos;
	}

	public void setIdModeloRscPos(Long idModeloRscPos) {
		this.idModeloRscPos = idModeloRscPos;
	}

	@Column(name = "id_tipo_modelo_rsc")
	public Long getIdTipoModeloRsc() {
		return this.idTipoModeloRsc;
	}

	public void setIdTipoModeloRsc(Long idTipoModeloRsc) {
		this.idTipoModeloRsc = idTipoModeloRsc;
	}

	@Column(name = "id_perfil_posicion")
	public Long getIdPerfilPosicion() {
		return this.idPerfilPosicion;
	}

	public void setIdPerfilPosicion(Long idPerfilPosicion) {
		this.idPerfilPosicion = idPerfilPosicion;
	}

	@Column(name = "id_rol")
	public Long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Long idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "monitor")
	public Boolean getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Boolean monitor) {
		this.monitor = monitor;
	}

	@Column(name = "principal")
	public Boolean getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(Boolean principal) {
		this.principal = principal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraModelorsc")
	public Set<BitacoraTrack> getBitacoraTracks() {
		return this.bitacoraTracks;
	}

	public void setBitacoraTracks(Set<BitacoraTrack> bitacoraTracks) {
		this.bitacoraTracks = bitacoraTracks;
	}

}
