package net.tce.model;

// Generated Dec 20, 2017 6:46:39 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * BitacoraDomicilio generated by hbm2java
 */
@Entity
@Table(name = "bitacora_domicilio")
@DynamicUpdate
public class BitacoraDomicilio implements java.io.Serializable {

	private long idBitacoraDomicilio;
	private BitacoraPosicion bitacoraPosicion;
	private TipoPrecision tipoPrecision;
	private CodigoProceso codigoProceso;
	private Asentamiento asentamiento;
	private String calle;
	private String numeroInterior;
	private String numeroExterior;
	private BigDecimal googleLatitude;
	private BigDecimal googleLongitude;

	public BitacoraDomicilio() {
	}

	public BitacoraDomicilio(long idBitacoraDomicilio) {
		this.idBitacoraDomicilio = idBitacoraDomicilio;
	}

	public BitacoraDomicilio(long idBitacoraDomicilio,
			BitacoraPosicion bitacoraPosicion, TipoPrecision tipoPrecision,
			CodigoProceso codigoProceso,
			Asentamiento asentamiento, String calle, String numeroInterior,
			String numeroExterior, BigDecimal googleLatitude,
			BigDecimal googleLongitude) {
		this.idBitacoraDomicilio = idBitacoraDomicilio;
		this.bitacoraPosicion = bitacoraPosicion;
		this.tipoPrecision = tipoPrecision;
		this.codigoProceso = codigoProceso;
		this.asentamiento = asentamiento;
		this.calle = calle;
		this.numeroInterior = numeroInterior;
		this.numeroExterior = numeroExterior;
		this.googleLatitude = googleLatitude;
		this.googleLongitude = googleLongitude;
	}

	@Id
	@Column(name = "id_bitacora_domicilio", unique = true, nullable = false)
	@SequenceGenerator(name="seq_btc_domicilio", sequenceName=Constante.SECUENCIA_BD_BTC_DOMICILIO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_btc_domicilio")
	public long getIdBitacoraDomicilio() {
		return this.idBitacoraDomicilio;
	}

	public void setIdBitacoraDomicilio(long idBitacoraDomicilio) {
		this.idBitacoraDomicilio = idBitacoraDomicilio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_posicion")
	public BitacoraPosicion getBitacoraPosicion() {
		return this.bitacoraPosicion;
	}

	public void setBitacoraPosicion(BitacoraPosicion bitacoraPosicion) {
		this.bitacoraPosicion = bitacoraPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_precision")
	public TipoPrecision getTipoPrecision() {
		return this.tipoPrecision;
	}

	public void setTipoPrecision(TipoPrecision tipoPrecision) {
		this.tipoPrecision = tipoPrecision;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_codigo_proceso")
	public CodigoProceso getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(CodigoProceso codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asentamiento")
	public Asentamiento getAsentamiento() {
		return this.asentamiento;
	}

	public void setAsentamiento(Asentamiento asentamiento) {
		this.asentamiento = asentamiento;
	}

	@Column(name = "calle", length = 250)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numero_interior", length = 10)
	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	@Column(name = "numero_exterior", length = 10)
	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	@Column(name = "google_latitude", precision = 131089, scale = 0)
	public BigDecimal getGoogleLatitude() {
		return this.googleLatitude;
	}

	public void setGoogleLatitude(BigDecimal googleLatitude) {
		this.googleLatitude = googleLatitude;
	}

	@Column(name = "google_longitude", precision = 131089, scale = 0)
	public BigDecimal getGoogleLongitude() {
		return this.googleLongitude;
	}

	public void setGoogleLongitude(BigDecimal googleLongitude) {
		this.googleLongitude = googleLongitude;
	}

}
