package net.tce.model;
// Generated Jan 21, 2020 11:22:18 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * BitacoraTrack generated by hbm2java
 */
@Entity
@Table(name = "bitacora_track")
public class BitacoraTrack implements java.io.Serializable {

	private long idBitacoraTrack;
	private BitacoraTrackCand bitacoraTrackCand;
	private Posicion posicion;
	private RelacionEmpresaPersona relacionEmpresaPersona;
	private BitacoraFase bitacoraFase;
	private BitacoraTrack bitacoraTrack;
	private TipoModuloBitacora tipoModuloBitacora;
	private BitacoraModelorsc bitacoraModelorsc;
	private BitacoraMonitor bitacoraMonitor;
	private TipoEventoBitacora tipoEventoBitacora;
	private BitacoraTrackMon bitacoraTrackMon;
	private BitacoraTrackPost bitacoraTrackPost;
	private Date fecha;
	private boolean porSistema;
	private String observacion;
	private Set<BitacoraTrack> bitacoraTracks = new HashSet<BitacoraTrack>(0);

	public BitacoraTrack() {
	}

	public BitacoraTrack(long idBitacoraTrack, RelacionEmpresaPersona relacionEmpresaPersona,
			TipoModuloBitacora tipoModuloBitacora, TipoEventoBitacora tipoEventoBitacora, Date fecha,
			boolean porSistema) {
		this.idBitacoraTrack = idBitacoraTrack;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.tipoModuloBitacora = tipoModuloBitacora;
		this.tipoEventoBitacora = tipoEventoBitacora;
		this.fecha = fecha;
		this.porSistema = porSistema;
	}

	public BitacoraTrack(long idBitacoraTrack, BitacoraTrackCand bitacoraTrackCand, Posicion posicion,
			RelacionEmpresaPersona relacionEmpresaPersona, BitacoraFase bitacoraFase, BitacoraTrack bitacoraTrack,
			TipoModuloBitacora tipoModuloBitacora, BitacoraModelorsc bitacoraModelorsc, BitacoraMonitor bitacoraMonitor,
			TipoEventoBitacora tipoEventoBitacora, BitacoraTrackMon bitacoraTrackMon,
			BitacoraTrackPost bitacoraTrackPost, Date fecha, boolean porSistema, String observacion,
			Set<BitacoraTrack> bitacoraTracks) {
		this.idBitacoraTrack = idBitacoraTrack;
		this.bitacoraTrackCand = bitacoraTrackCand;
		this.posicion = posicion;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.bitacoraFase = bitacoraFase;
		this.bitacoraTrack = bitacoraTrack;
		this.tipoModuloBitacora = tipoModuloBitacora;
		this.bitacoraModelorsc = bitacoraModelorsc;
		this.bitacoraMonitor = bitacoraMonitor;
		this.tipoEventoBitacora = tipoEventoBitacora;
		this.bitacoraTrackMon = bitacoraTrackMon;
		this.bitacoraTrackPost = bitacoraTrackPost;
		this.fecha = fecha;
		this.porSistema = porSistema;
		this.observacion = observacion;
		this.bitacoraTracks = bitacoraTracks;
	}

	@Id
	@SequenceGenerator(name="seq_bitacora_track", sequenceName=Constante.SECUENCIA_BD_BTC_TRACK, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_bitacora_track")
	@Column(name = "id_bitacora_track", unique = true, nullable = false)
	public long getIdBitacoraTrack() {
		return this.idBitacoraTrack;
	}

	public void setIdBitacoraTrack(long idBitacoraTrack) {
		this.idBitacoraTrack = idBitacoraTrack;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_cand")
	public BitacoraTrackCand getBitacoraTrackCand() {
		return this.bitacoraTrackCand;
	}

	public void setBitacoraTrackCand(BitacoraTrackCand bitacoraTrackCand) {
		this.bitacoraTrackCand = bitacoraTrackCand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_posicion")
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_relacion_empresa_persona", nullable = false)
	public RelacionEmpresaPersona getRelacionEmpresaPersona() {
		return this.relacionEmpresaPersona;
	}

	public void setRelacionEmpresaPersona(RelacionEmpresaPersona relacionEmpresaPersona) {
		this.relacionEmpresaPersona = relacionEmpresaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_fase")
	public BitacoraFase getBitacoraFase() {
		return this.bitacoraFase;
	}

	public void setBitacoraFase(BitacoraFase bitacoraFase) {
		this.bitacoraFase = bitacoraFase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_rel")
	public BitacoraTrack getBitacoraTrack() {
		return this.bitacoraTrack;
	}

	public void setBitacoraTrack(BitacoraTrack bitacoraTrack) {
		this.bitacoraTrack = bitacoraTrack;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_modulo_bitacora", nullable = false)
	public TipoModuloBitacora getTipoModuloBitacora() {
		return this.tipoModuloBitacora;
	}

	public void setTipoModuloBitacora(TipoModuloBitacora tipoModuloBitacora) {
		this.tipoModuloBitacora = tipoModuloBitacora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_modelorsc")
	public BitacoraModelorsc getBitacoraModelorsc() {
		return this.bitacoraModelorsc;
	}

	public void setBitacoraModelorsc(BitacoraModelorsc bitacoraModelorsc) {
		this.bitacoraModelorsc = bitacoraModelorsc;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_monitor")
	public BitacoraMonitor getBitacoraMonitor() {
		return this.bitacoraMonitor;
	}

	public void setBitacoraMonitor(BitacoraMonitor bitacoraMonitor) {
		this.bitacoraMonitor = bitacoraMonitor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_evento_bitacora", nullable = false)
	public TipoEventoBitacora getTipoEventoBitacora() {
		return this.tipoEventoBitacora;
	}

	public void setTipoEventoBitacora(TipoEventoBitacora tipoEventoBitacora) {
		this.tipoEventoBitacora = tipoEventoBitacora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_mon")
	public BitacoraTrackMon getBitacoraTrackMon() {
		return this.bitacoraTrackMon;
	}

	public void setBitacoraTrackMon(BitacoraTrackMon bitacoraTrackMon) {
		this.bitacoraTrackMon = bitacoraTrackMon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_post")
	public BitacoraTrackPost getBitacoraTrackPost() {
		return this.bitacoraTrackPost;
	}

	public void setBitacoraTrackPost(BitacoraTrackPost bitacoraTrackPost) {
		this.bitacoraTrackPost = bitacoraTrackPost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "por_sistema", nullable = false)
	public boolean isPorSistema() {
		return this.porSistema;
	}

	public void setPorSistema(boolean porSistema) {
		this.porSistema = porSistema;
	}
	
	@Column(name = "observacion", length = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraTrack")
	public Set<BitacoraTrack> getBitacoraTracks() {
		return this.bitacoraTracks;
	}

	public void setBitacoraTracks(Set<BitacoraTrack> bitacoraTracks) {
		this.bitacoraTracks = bitacoraTracks;
	}

}
