package net.tce.model;
// Generated Mar 24, 2020 12:00:43 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * BitacoraTrackCont generated by hbm2java
 */
@Entity
@Table(name = "bitacora_track_cont")
public class BitacoraTrackCont implements java.io.Serializable {

	private long idBitacoraTrackCont;
	private BitacoraTrackMon bitacoraTrackMon;
	private BitacoraTrackPost bitacoraTrackPost;
	private Long idContenido;
	private Long idTipoContenidoArchivo;
	private String descripcion;
	private String rutaAbsoluta;
	private Date fechaCarga;

	public BitacoraTrackCont() {
	}

	public BitacoraTrackCont(long idBitacoraTrackCont) {
		this.idBitacoraTrackCont = idBitacoraTrackCont;
	}

	public BitacoraTrackCont(long idBitacoraTrackCont, BitacoraTrackMon bitacoraTrackMon,
			BitacoraTrackPost bitacoraTrackPost, Long idContenido, Long idTipoContenidoArchivo, String descripcion,
			String rutaAbsoluta, Date fechaCarga) {
		this.idBitacoraTrackCont = idBitacoraTrackCont;
		this.bitacoraTrackMon = bitacoraTrackMon;
		this.bitacoraTrackPost = bitacoraTrackPost;
		this.idContenido = idContenido;
		this.idTipoContenidoArchivo = idTipoContenidoArchivo;
		this.descripcion = descripcion;
		this.rutaAbsoluta = rutaAbsoluta;
		this.fechaCarga = fechaCarga;
	}

	@Id
	@SequenceGenerator(name="seq_bitacora_track_cont", sequenceName=Constante.SECUENCIA_BD_BTC_TRACK_CONT, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_bitacora_track_cont")
	@Column(name = "id_bitacora_track_cont", unique = true, nullable = false)
	public long getIdBitacoraTrackCont() {
		return this.idBitacoraTrackCont;
	}

	public void setIdBitacoraTrackCont(long idBitacoraTrackCont) {
		this.idBitacoraTrackCont = idBitacoraTrackCont;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_mon")
	public BitacoraTrackMon getBitacoraTrackMon() {
		return this.bitacoraTrackMon;
	}

	public void setBitacoraTrackMon(BitacoraTrackMon bitacoraTrackMon) {
		this.bitacoraTrackMon = bitacoraTrackMon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bitacora_track_post")
	public BitacoraTrackPost getBitacoraTrackPost() {
		return this.bitacoraTrackPost;
	}

	public void setBitacoraTrackPost(BitacoraTrackPost bitacoraTrackPost) {
		this.bitacoraTrackPost = bitacoraTrackPost;
	}

	@Column(name = "id_contenido")
	public Long getIdContenido() {
		return this.idContenido;
	}

	public void setIdContenido(Long idContenido) {
		this.idContenido = idContenido;
	}

	@Column(name = "id_tipo_contenido_archivo")
	public Long getIdTipoContenidoArchivo() {
		return this.idTipoContenidoArchivo;
	}

	public void setIdTipoContenidoArchivo(Long idTipoContenidoArchivo) {
		this.idTipoContenidoArchivo = idTipoContenidoArchivo;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ruta_absoluta", length = 250)
	public String getRutaAbsoluta() {
		return this.rutaAbsoluta;
	}

	public void setRutaAbsoluta(String rutaAbsoluta) {
		this.rutaAbsoluta = rutaAbsoluta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_carga", length = 29)
	public Date getFechaCarga() {
		return this.fechaCarga;
	}

	public void setFechaCarga(Date fechaCarga) {
		this.fechaCarga = fechaCarga;
	}

}
