package net.tce.model;
// Generated Feb 13, 2020 12:42:15 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * BitacoraMonitor generated by hbm2java
 */
@Entity
@Table(name = "bitacora_monitor")
public class BitacoraMonitor implements java.io.Serializable {

	private long idBitacoraMonitor;
	private long idMonitor;
	private Long idModeloRscPosFase;
	private Long idRelacionEmpresaPersona;
	private Boolean principal;
	private Long idRelacionEmpresaPersonaS;
	private Set<BitacoraTrack> bitacoraTracks = new HashSet<BitacoraTrack>(0);

	public BitacoraMonitor() {
	}

	public BitacoraMonitor(long idBitacoraMonitor, long idMonitor) {
		this.idBitacoraMonitor = idBitacoraMonitor;
		this.idMonitor = idMonitor;
	}

	public BitacoraMonitor(long idBitacoraMonitor, long idMonitor, Long idModeloRscPosFase,
			Long idRelacionEmpresaPersona, Boolean principal, Long idRelacionEmpresaPersonaS,
			Set<BitacoraTrack> bitacoraTracks) {
		this.idBitacoraMonitor = idBitacoraMonitor;
		this.idMonitor = idMonitor;
		this.idModeloRscPosFase = idModeloRscPosFase;
		this.idRelacionEmpresaPersona = idRelacionEmpresaPersona;
		this.principal = principal;
		this.idRelacionEmpresaPersonaS = idRelacionEmpresaPersonaS;
		this.bitacoraTracks = bitacoraTracks;
	}

	@Id
	@SequenceGenerator(name="seq_bitacora_monitor", sequenceName=Constante.SECUENCIA_BD_BTC_MONITOR, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_bitacora_monitor")
	@Column(name = "id_bitacora_monitor", unique = true, nullable = false)
	public long getIdBitacoraMonitor() {
		return this.idBitacoraMonitor;
	}

	public void setIdBitacoraMonitor(long idBitacoraMonitor) {
		this.idBitacoraMonitor = idBitacoraMonitor;
	}

	@Column(name = "id_monitor", nullable = false)
	public long getIdMonitor() {
		return this.idMonitor;
	}

	public void setIdMonitor(long idMonitor) {
		this.idMonitor = idMonitor;
	}

	@Column(name = "id_modelo_rsc_pos_fase")
	public Long getIdModeloRscPosFase() {
		return this.idModeloRscPosFase;
	}

	public void setIdModeloRscPosFase(Long idModeloRscPosFase) {
		this.idModeloRscPosFase = idModeloRscPosFase;
	}

	@Column(name = "id_relacion_empresa_persona")
	public Long getIdRelacionEmpresaPersona() {
		return this.idRelacionEmpresaPersona;
	}

	public void setIdRelacionEmpresaPersona(Long idRelacionEmpresaPersona) {
		this.idRelacionEmpresaPersona = idRelacionEmpresaPersona;
	}

	@Column(name = "principal")
	public Boolean getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(Boolean principal) {
		this.principal = principal;
	}

	@Column(name = "id_relacion_empresa_persona_s")
	public Long getIdRelacionEmpresaPersonaS() {
		return this.idRelacionEmpresaPersonaS;
	}

	public void setIdRelacionEmpresaPersonaS(Long idRelacionEmpresaPersonaS) {
		this.idRelacionEmpresaPersonaS = idRelacionEmpresaPersonaS;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraMonitor")
	public Set<BitacoraTrack> getBitacoraTracks() {
		return this.bitacoraTracks;
	}

	public void setBitacoraTracks(Set<BitacoraTrack> bitacoraTracks) {
		this.bitacoraTracks = bitacoraTracks;
	}

}
