package net.tce.model;

// Generated Dec 20, 2017 6:46:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * BitacoraPosicion generated by hbm2java
 */
@Entity
@Table(name = "bitacora_posicion")
@DynamicUpdate
public class BitacoraPosicion implements java.io.Serializable {

	private long idBitacoraPosicion;
	private RelacionEmpresaPersona relacionEmpresaPersona;
	private TipoContrato tipoContrato;
	private RelacionEmpresaPersona relacionEmpresaPersonaS;
	private TipoOperacionBitacora tipoOperacionBitacora;
	private AreaPerfil areaPerfil;
	private PerfilPosicion perfilPosicion;
	private TipoPrestacion tipoPrestacion;
	private AmbitoGeografico ambitoGeografico;
	private PeriodicidadPago periodicidadPago;
	private TipoJornada tipoJornada;
	private String nombre;
	private String otros;
	private Boolean sueldoNegociable;
	private Boolean esConfidencial;
	private Long salarioMin;
	private Long salarioMax;
	private Date fechaBitacora;
	private Set<BitacoraDomicilio> bitacoraDomicilios = new HashSet<BitacoraDomicilio>(0);
	private Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils = new HashSet<BitacoraCompetenciaPerfil>(0);
	private Set<BitacoraPerfilTextoNgram> bitacoraPerfilTextoNgrams = new HashSet<BitacoraPerfilTextoNgram>(0);
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(0);

	public BitacoraPosicion() {
	}

	public BitacoraPosicion(long idBitacoraPosicion,
			RelacionEmpresaPersona relacionEmpresaPersona,
			TipoOperacionBitacora tipoOperacionBitacora, PerfilPosicion perfilPosicion) {
		this.idBitacoraPosicion = idBitacoraPosicion;
		this.relacionEmpresaPersona= relacionEmpresaPersona;
		this.tipoOperacionBitacora = tipoOperacionBitacora;
		this.perfilPosicion = perfilPosicion;
	}

	public BitacoraPosicion(long idBitacoraPosicion,
			RelacionEmpresaPersona relacionEmpresaPersona, TipoContrato tipoContrato,
			RelacionEmpresaPersona relacionEmpresaPersonaS,
			TipoOperacionBitacora tipoOperacionBitacora, AreaPerfil areaPerfil, PerfilPosicion perfilPosicion,
			TipoPrestacion tipoPrestacion, AmbitoGeografico ambitoGeografico, PeriodicidadPago periodicidadPago,
			TipoJornada tipoJornada, String nombre, String otros, Boolean sueldoNegociable, Boolean esConfidencial,
			Long salarioMin, Long salarioMax, Date fechaBitacora, Set<BitacoraDomicilio> bitacoraDomicilios,
			Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils,
			Set<BitacoraPerfilTextoNgram> bitacoraPerfilTextoNgrams,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.idBitacoraPosicion = idBitacoraPosicion;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.tipoContrato = tipoContrato;
		this.relacionEmpresaPersonaS = relacionEmpresaPersonaS;
		this.tipoOperacionBitacora = tipoOperacionBitacora;
		this.areaPerfil = areaPerfil;
		this.perfilPosicion = perfilPosicion;
		this.tipoPrestacion = tipoPrestacion;
		this.ambitoGeografico = ambitoGeografico;
		this.periodicidadPago = periodicidadPago;
		this.tipoJornada = tipoJornada;
		this.nombre = nombre;
		this.otros = otros;
		this.sueldoNegociable = sueldoNegociable;
		this.esConfidencial = esConfidencial;
		this.salarioMin = salarioMin;
		this.salarioMax = salarioMax;
		this.fechaBitacora = fechaBitacora;
		this.bitacoraDomicilios = bitacoraDomicilios;
		this.bitacoraCompetenciaPerfils = bitacoraCompetenciaPerfils;
		this.bitacoraPerfilTextoNgrams = bitacoraPerfilTextoNgrams;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	
	@Id
	@Column(name = "id_bitacora_posicion", unique = true, nullable = false)
	@SequenceGenerator(name="seq_btc_posicion", sequenceName=Constante.SECUENCIA_BD_BTC_POSICION, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_btc_posicion")
	public long getIdBitacoraPosicion() {
		return this.idBitacoraPosicion;
	}

	public void setIdBitacoraPosicion(long idBitacoraPosicion) {
		this.idBitacoraPosicion = idBitacoraPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_prestacion")
	public TipoPrestacion getTipoPrestacion() {
		return this.tipoPrestacion;
	}

	public void setTipoPrestacion(TipoPrestacion tipoPrestacion) {
		this.tipoPrestacion = tipoPrestacion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_operacion_bitacora")
	public TipoOperacionBitacora getTipoOperacionBitacora() {
		return this.tipoOperacionBitacora;
	}

	public void setTipoOperacionBitacora(
			TipoOperacionBitacora tipoOperacionBitacora) {
		this.tipoOperacionBitacora = tipoOperacionBitacora;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_area_perfil")
	public AreaPerfil getAreaPerfil() {
		return this.areaPerfil;
	}

	public void setAreaPerfil(AreaPerfil areaPerfil) {
		this.areaPerfil = areaPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodicidad_pago")
	public PeriodicidadPago getPeriodicidadPago() {
		return this.periodicidadPago;
	}

	public void setPeriodicidadPago(PeriodicidadPago periodicidadPago) {
		this.periodicidadPago = periodicidadPago;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ambito_geografico")
	public AmbitoGeografico getAmbitoGeografico() {
		return this.ambitoGeografico;
	}

	public void setAmbitoGeografico(AmbitoGeografico ambitoGeografico) {
		this.ambitoGeografico = ambitoGeografico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_contrato")
	public TipoContrato getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(TipoContrato tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_relacion_empresa_persona", nullable = false)
	public RelacionEmpresaPersona getRelacionEmpresaPersona() {
		return this.relacionEmpresaPersona;
	}

	public void setRelacionEmpresaPersona(
			RelacionEmpresaPersona relacionEmpresaPersona) {
		this.relacionEmpresaPersona = relacionEmpresaPersona;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_relacion_empresa_persona_s")
	public RelacionEmpresaPersona getRelacionEmpresaPersonaS() {
		return this.relacionEmpresaPersonaS;
	}

	public void setRelacionEmpresaPersonaS(
			RelacionEmpresaPersona relacionEmpresaPersonaS) {
		this.relacionEmpresaPersonaS = relacionEmpresaPersonaS;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_jornada")
	public TipoJornada getTipoJornada() {
		return this.tipoJornada;
	}

	public void setTipoJornada(TipoJornada tipoJornada) {
		this.tipoJornada = tipoJornada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil_posicion")
	public PerfilPosicion getPerfilPosicion() {
		return this.perfilPosicion;
	}

	public void setPerfilPosicion(PerfilPosicion perfilPosicion) {
		this.perfilPosicion = perfilPosicion;
	}

	@Column(name = "nombre", length = 250)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "otros", length = 1500)
	public String getOtros() {
		return this.otros;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	@Column(name = "sueldo_negociable")
	public Boolean getSueldoNegociable() {
		return this.sueldoNegociable;
	}

	public void setSueldoNegociable(Boolean sueldoNegociable) {
		this.sueldoNegociable = sueldoNegociable;
	}

	@Column(name = "es_confidencial")
	public Boolean getEsConfidencial() {
		return this.esConfidencial;
	}

	public void setEsConfidencial(Boolean esConfidencial) {
		this.esConfidencial = esConfidencial;
	}

	@Column(name = "salario_min")
	public Long getSalarioMin() {
		return this.salarioMin;
	}

	public void setSalarioMin(Long salarioMin) {
		this.salarioMin = salarioMin;
	}

	@Column(name = "salario_max")
	public Long getSalarioMax() {
		return this.salarioMax;
	}

	public void setSalarioMax(Long salarioMax) {
		this.salarioMax = salarioMax;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_bitacora", length = 29)
	public Date getFechaBitacora() {
		return this.fechaBitacora;
	}

	public void setFechaBitacora(Date fechaBitacora) {
		this.fechaBitacora = fechaBitacora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraPosicion")
	public Set<BitacoraPerfilTextoNgram> getBitacoraPerfilTextoNgrams() {
		return this.bitacoraPerfilTextoNgrams;
	}

	public void setBitacoraPerfilTextoNgrams(
			Set<BitacoraPerfilTextoNgram> bitacoraPerfilTextoNgrams) {
		this.bitacoraPerfilTextoNgrams = bitacoraPerfilTextoNgrams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraPosicion")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraPosicion")
	public Set<BitacoraDomicilio> getBitacoraDomicilios() {
		return this.bitacoraDomicilios;
	}

	public void setBitacoraDomicilios(Set<BitacoraDomicilio> bitacoraDomicilios) {
		this.bitacoraDomicilios = bitacoraDomicilios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacoraPosicion")
	public Set<BitacoraCompetenciaPerfil> getBitacoraCompetenciaPerfils() {
		return this.bitacoraCompetenciaPerfils;
	}

	public void setBitacoraCompetenciaPerfils(
			Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils) {
		this.bitacoraCompetenciaPerfils = bitacoraCompetenciaPerfils;
	}

}
