package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * CandidatoRechazo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CANDIDATO_RECHAZO")
public class CandidatoRechazo implements java.io.Serializable {

	private long idCandidatoRechazo;
	private Candidato candidato;
	private MotivoRechazo motivoRechazo;
	private String otro;

	public CandidatoRechazo() {
	}

	public CandidatoRechazo(long idCandidatoRechazo, Candidato candidato,
			MotivoRechazo motivoRechazo) {
		this.idCandidatoRechazo = idCandidatoRechazo;
		this.candidato = candidato;
		this.motivoRechazo = motivoRechazo;
	}

	public CandidatoRechazo(long idCandidatoRechazo, Candidato candidato,
			MotivoRechazo motivoRechazo, String otro) {
		this.idCandidatoRechazo = idCandidatoRechazo;
		this.candidato = candidato;
		this.motivoRechazo = motivoRechazo;
		this.otro = otro;
	}

	@Id
	@SequenceGenerator(name="seq_candidato_rechazo", sequenceName=Constante.SECUENCIA_BD_CANDIDATO_RECHAZO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_candidato_rechazo")	
	@Column(name = "ID_CANDIDATO_RECHAZO", unique = true, nullable = false)
	public long getIdCandidatoRechazo() {
		return this.idCandidatoRechazo;
	}

	public void setIdCandidatoRechazo(long idCandidatoRechazo) {
		this.idCandidatoRechazo = idCandidatoRechazo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CANDIDATO", nullable = false)
	public Candidato getCandidato() {
		return this.candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MOTIVO_RECHAZO", nullable = false)
	public MotivoRechazo getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(MotivoRechazo motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}

	@Column(name = "OTRO", length = 250)
	public String getOtro() {
		return this.otro;
	}

	public void setOtro(String otro) {
		this.otro = otro;
	}

}
