package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaEvento generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CATEGORIA_EVENTO")
public class CategoriaEvento implements java.io.Serializable {

	private long idCategoriaEvento;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<TipoEvento> tipoEventos = new HashSet<TipoEvento>(0);

	public CategoriaEvento() {
	}

	public CategoriaEvento(long idCategoriaEvento, String descripcion,
			boolean estatusRegistro) {
		this.idCategoriaEvento = idCategoriaEvento;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public CategoriaEvento(long idCategoriaEvento, String descripcion,
			String significado, boolean estatusRegistro,
			Set<TipoEvento> tipoEventos) {
		this.idCategoriaEvento = idCategoriaEvento;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.tipoEventos = tipoEventos;
	}

	@Id
	@Column(name = "ID_CATEGORIA_EVENTO", unique = true, nullable = false)
	public long getIdCategoriaEvento() {
		return this.idCategoriaEvento;
	}

	public void setIdCategoriaEvento(long idCategoriaEvento) {
		this.idCategoriaEvento = idCategoriaEvento;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaEvento")
	public Set<TipoEvento> getTipoEventos() {
		return this.tipoEventos;
	}

	public void setTipoEventos(Set<TipoEvento> tipoEventos) {
		this.tipoEventos = tipoEventos;
	}

}
