package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CertificacionEmpresa generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CERTIFICACION_EMPRESA")
public class CertificacionEmpresa implements java.io.Serializable {

	private long idCertificacionEmpresa;
	private Empresa empresa;
	private Mes mes;
	private String texto;
	private String institucion;
	private Short anioInicio;
	private byte diaInicio;
	private Date fechaInicio;

	public CertificacionEmpresa() {
	}

	public CertificacionEmpresa(long idCertificacionEmpresa, Empresa empresa) {
		this.idCertificacionEmpresa = idCertificacionEmpresa;
		this.empresa = empresa;
	}

	public CertificacionEmpresa(long idCertificacionEmpresa, Empresa empresa,
			Mes mes, String texto, String institucion, Short anioInicio,
			byte diaInicio, Date fechaInicio) {
		this.idCertificacionEmpresa = idCertificacionEmpresa;
		this.empresa = empresa;
		this.mes = mes;
		this.texto = texto;
		this.institucion = institucion;
		this.anioInicio = anioInicio;
		this.diaInicio = diaInicio;
		this.fechaInicio = fechaInicio;
	}

	@Id
	@Column(name = "ID_CERTIFICACION_EMPRESA", unique = true, nullable = false)
	public long getIdCertificacionEmpresa() {
		return this.idCertificacionEmpresa;
	}

	public void setIdCertificacionEmpresa(long idCertificacionEmpresa) {
		this.idCertificacionEmpresa = idCertificacionEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MES_INICIO")
	public Mes getMes() {
		return this.mes;
	}

	public void setMes(Mes mes) {
		this.mes = mes;
	}

	@Column(name = "TEXTO", length = 2500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "INSTITUCION", length = 100)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "ANIO_INICIO")
	public Short getAnioInicio() {
		return this.anioInicio;
	}

	public void setAnioInicio(Short anioInicio) {
		this.anioInicio = anioInicio;
	}

	@Column(name = "DIA_INICIO")
	public byte getDiaInicio() {
		return this.diaInicio;
	}

	public void setDiaInicio(byte diaInicio) {
		this.diaInicio = diaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	
}
