package net.tce.model;
// Generated Mar 17, 2017 1:04:38 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

import org.hibernate.annotations.DynamicUpdate;

/**
 * Certificacion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CERTIFICACION")
public class Certificacion  implements java.io.Serializable {


     private long idCertificacion;
     private Mes mes;
     private Persona persona;
     private GradoAcademico gradoAcademico;
     private String titulo;
     private String institucion;
     private Short anio;

    public Certificacion() {
    }

	
    public Certificacion(long idCertificacion, Persona persona) {
        this.idCertificacion = idCertificacion;
        this.persona = persona;
    }
    public Certificacion(long idCertificacion, Mes mes, Persona persona, GradoAcademico gradoAcademico, String titulo, String institucion, Short anio) {
       this.idCertificacion = idCertificacion;
       this.mes = mes;
       this.persona = persona;
       this.titulo = titulo;
       this.institucion = institucion;
       this.anio = anio;
       this.gradoAcademico = gradoAcademico;
    }
   
    @Id
    @SequenceGenerator(name="seq_certificacion", sequenceName=Constante.SECUENCIA_BD_HABILIDAD, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_certificacion")
    @Column(name="ID_CERTIFICACION", unique=true, nullable=false)
    public long getIdCertificacion() {
        return this.idCertificacion;
    }
    
    public void setIdCertificacion(long idCertificacion) {
        this.idCertificacion = idCertificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MES")
    public Mes getMes() {
        return this.mes;
    }
    
    public void setMes(Mes mes) {
        this.mes = mes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GRADO_ACADEMICO")
	public GradoAcademico getGradoAcademico() {
		return this.gradoAcademico;
	}

	public void setGradoAcademico(GradoAcademico gradoAcademico) {
		this.gradoAcademico = gradoAcademico;
	}

    
    @Column(name="TITULO", length=250)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="INSTITUCION", length=100)
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    
    @Column(name="ANIO")
    public Short getAnio() {
        return this.anio;
    }
    
    public void setAnio(Short anio) {
        this.anio = anio;
    }




}


