package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CIUDAD")
public class Ciudad implements java.io.Serializable {

	private long idCiudad;
	private Municipio municipio;
	private String claveCiudad;
	private String nombre;
	private boolean estatusRegistro;
	private Set<Asentamiento> asentamientos = new HashSet<Asentamiento>(0);

	public Ciudad() {
	}

	public Ciudad(long idCiudad, Municipio municipio, String nombre,
			boolean estatusRegistro) {
		this.idCiudad = idCiudad;
		this.municipio = municipio;
		this.nombre = nombre;
		this.estatusRegistro = estatusRegistro;
	}

	public Ciudad(long idCiudad, Municipio municipio, String claveCiudad,
			String nombre, boolean estatusRegistro,
			Set<Asentamiento> asentamientos) {
		this.idCiudad = idCiudad;
		this.municipio = municipio;
		this.claveCiudad = claveCiudad;
		this.nombre = nombre;
		this.estatusRegistro = estatusRegistro;
		this.asentamientos = asentamientos;
	}

	@Id
	@Column(name = "ID_CIUDAD", unique = true, nullable = false)
	public long getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(long idCiudad) {
		this.idCiudad = idCiudad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MUNICIPIO", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@Column(name = "CLAVE_CIUDAD", length = 10)
	public String getClaveCiudad() {
		return this.claveCiudad;
	}

	public void setClaveCiudad(String claveCiudad) {
		this.claveCiudad = claveCiudad;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
	public Set<Asentamiento> getAsentamientos() {
		return this.asentamientos;
	}

	public void setAsentamientos(Set<Asentamiento> asentamientos) {
		this.asentamientos = asentamientos;
	}

}
