package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClasificacionContacto generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CLASIFICACION_CONTACTO")
public class ClasificacionContacto implements java.io.Serializable {

	private long idClasificacionContacto;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<TipoContacto> tipoContactos = new HashSet<TipoContacto>(0);

	public ClasificacionContacto() {
	}

	public ClasificacionContacto(long idClasificacionContacto,
			boolean estatusRegistro) {
		this.idClasificacionContacto = idClasificacionContacto;
		this.estatusRegistro = estatusRegistro;
	}

	public ClasificacionContacto(long idClasificacionContacto,
			String descripcion, String significado, boolean estatusRegistro,
			Set<TipoContacto> tipoContactos) {
		this.idClasificacionContacto = idClasificacionContacto;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.tipoContactos = tipoContactos;
	}

	@Id
	@Column(name = "ID_CLASIFICACION_CONTACTO", unique = true, nullable = false)
	public long getIdClasificacionContacto() {
		return this.idClasificacionContacto;
	}

	public void setIdClasificacionContacto(long idClasificacionContacto) {
		this.idClasificacionContacto = idClasificacionContacto;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clasificacionContacto")
	public Set<TipoContacto> getTipoContactos() {
		return this.tipoContactos;
	}

	public void setTipoContactos(Set<TipoContacto> tipoContactos) {
		this.tipoContactos = tipoContactos;
	}

}
