package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodigoProceso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CODIGO_PROCESO")
public class CodigoProceso implements java.io.Serializable {

	private long idCodigoProceso;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<BitacoraDomicilio> bitacoraDomicilios = new HashSet<BitacoraDomicilio>(
			0);
	private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

	public CodigoProceso() {
	}

	public CodigoProceso(long idCodigoProceso, String descripcion) {
		this.idCodigoProceso = idCodigoProceso;
		this.descripcion = descripcion;
	}

	public CodigoProceso(long idCodigoProceso, String descripcion,
			String significado, boolean estatusRegistro,
			Set<BitacoraDomicilio> bitacoraDomicilios, Set<Domicilio> domicilios) {
		this.idCodigoProceso = idCodigoProceso;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.bitacoraDomicilios = bitacoraDomicilios;
		this.domicilios = domicilios;
	}

	@Id
	@Column(name = "id_codigo_proceso", unique = true, nullable = false)
	public long getIdCodigoProceso() {
		return this.idCodigoProceso;
	}

	public void setIdCodigoProceso(long idCodigoProceso) {
		this.idCodigoProceso = idCodigoProceso;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codigoProceso")
	public Set<BitacoraDomicilio> getBitacoraDomicilios() {
		return this.bitacoraDomicilios;
	}

	public void setBitacoraDomicilios(Set<BitacoraDomicilio> bitacoraDomicilios) {
		this.bitacoraDomicilios = bitacoraDomicilios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codigoProceso")
	public Set<Domicilio> getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Set<Domicilio> domicilios) {
		this.domicilios = domicilios;
	}

}
