package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * CompetenciaPerfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "COMPETENCIA_PERFIL")
@DynamicUpdate
public class CompetenciaPerfil implements java.io.Serializable {

	private long idCompetenciaPerfil;
	private Competencia competencia;
	private Perfil perfil;
	private boolean seleccionado;

	public CompetenciaPerfil() {
	}

	public CompetenciaPerfil(long idCompetenciaPerfil, Competencia competencia,
			Perfil perfil, boolean seleccionado) {
		this.idCompetenciaPerfil = idCompetenciaPerfil;
		this.competencia = competencia;
		this.perfil = perfil;
		this.seleccionado = seleccionado;
	}

	@Id
	@SequenceGenerator(name="seq_comp_perf", sequenceName=Constante.SECUENCIA_BD_COMPETENCIA_PERFIL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_comp_perf")
	@Column(name = "id_competencia_perfil", unique = true, nullable = false)
	public long getIdCompetenciaPerfil() {
		return this.idCompetenciaPerfil;
	}

	public void setIdCompetenciaPerfil(long idCompetenciaPerfil) {
		this.idCompetenciaPerfil = idCompetenciaPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_competencia", nullable = false)
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "seleccionado", nullable = false)
	public boolean isSeleccionado() {
		return this.seleccionado;
	}

	public void setSeleccionado(boolean seleccionado) {
		this.seleccionado = seleccionado;
	}

}
