package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Competencia generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "COMPETENCIA")
public class Competencia implements java.io.Serializable {

	private long idCompetencia;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils = new HashSet<BitacoraCompetenciaPerfil>(
			0);
	private Set<CompetenciaPerfil> competenciaPerfils = new HashSet<CompetenciaPerfil>(
			0);
	private Set<Reactivo> reactivos = new HashSet<Reactivo>(0);

	public Competencia() {
	}

	public Competencia(long idCompetencia, String descripcion) {
		this.idCompetencia = idCompetencia;
		this.descripcion = descripcion;
	}

	public Competencia(long idCompetencia, String descripcion,
			String significado, boolean estatusRegistro,
			Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils,
			Set<CompetenciaPerfil> competenciaPerfils, Set<Reactivo> reactivos) {
		this.idCompetencia = idCompetencia;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.bitacoraCompetenciaPerfils = bitacoraCompetenciaPerfils;
		this.competenciaPerfils = competenciaPerfils;
		this.reactivos = reactivos;
	}

	@Id
	@Column(name = "id_competencia", unique = true, nullable = false)
	public long getIdCompetencia() {
		return this.idCompetencia;
	}

	public void setIdCompetencia(long idCompetencia) {
		this.idCompetencia = idCompetencia;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<BitacoraCompetenciaPerfil> getBitacoraCompetenciaPerfils() {
		return this.bitacoraCompetenciaPerfils;
	}

	public void setBitacoraCompetenciaPerfils(
			Set<BitacoraCompetenciaPerfil> bitacoraCompetenciaPerfils) {
		this.bitacoraCompetenciaPerfils = bitacoraCompetenciaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<CompetenciaPerfil> getCompetenciaPerfils() {
		return this.competenciaPerfils;
	}

	public void setCompetenciaPerfils(Set<CompetenciaPerfil> competenciaPerfils) {
		this.competenciaPerfils = competenciaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<Reactivo> getReactivos() {
		return this.reactivos;
	}

	public void setReactivos(Set<Reactivo> reactivos) {
		this.reactivos = reactivos;
	}
}
