package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * ControlProceso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CONTROL_PROCESO")
public class ControlProceso implements java.io.Serializable {

	private long idControlProceso;
	private TipoProceso tipoProceso;
	private EstatusProceso estatusProceso;
	private Persona persona;
	private Date fechaInicio;
	private Date fechaFin;
	private String resultado;
	private String mensaje;

	public ControlProceso() {
	}

	public ControlProceso(long idControlProceso, TipoProceso tipoProceso,
			EstatusProceso estatusProceso, Date fechaInicio) {
		this.idControlProceso = idControlProceso;
		this.tipoProceso = tipoProceso;
		this.estatusProceso = estatusProceso;
		this.fechaInicio = fechaInicio;
	}

	public ControlProceso(long idControlProceso, TipoProceso tipoProceso,
			EstatusProceso estatusProceso, Persona persona, Date fechaInicio,
			Date fechaFin, String resultado, String mensaje) {
		this.idControlProceso = idControlProceso;
		this.tipoProceso = tipoProceso;
		this.estatusProceso = estatusProceso;
		this.persona = persona;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.resultado = resultado;
		this.mensaje = mensaje;
	}


	@Id
	@SequenceGenerator(name="seq_Control_Proceso", sequenceName=Constante.SECUENCIA_BD_CONTROL_PROCESO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Control_Proceso")
	@Column(name = "ID_CONTROL_PROCESO", unique = true, nullable = false)
	public long getIdControlProceso() {
		return this.idControlProceso;
	}

	public void setIdControlProceso(long idControlProceso) {
		this.idControlProceso = idControlProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_PROCESO", nullable = false)
	public TipoProceso getTipoProceso() {
		return this.tipoProceso;
	}

	public void setTipoProceso(TipoProceso tipoProceso) {
		this.tipoProceso = tipoProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTATUS_PROCESO", nullable = false)
	public EstatusProceso getEstatusProceso() {
		return this.estatusProceso;
	}

	public void setEstatusProceso(EstatusProceso estatusProceso) {
		this.estatusProceso = estatusProceso;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", nullable = false, length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "RESULTADO", length = 1500)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "MENSAJE", length = 1500)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
