package net.tce.model;

// Generated Feb 10, 2015 12:45:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import net.tce.util.Constante;

/**
 * Contenido generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "CONTENIDO")
public class Contenido implements java.io.Serializable {

	private long idContenido;
	private Empresa empresa;
	private TrackingPostulante trackingPostulante;
	private TipoContenidoArchivo tipoContenidoArchivo;
	private Persona persona;
	private TrackingMonitor trackingMonitor;
	private Date fechaCarga;
	private byte[] contenido;
	private String descripcion;
	private String rutaAbsoluta;
	

	public Contenido() {
	}

	public Contenido(long idContenido, TipoContenidoArchivo tipoContenidoArchivo, Date fechaCarga) {
		this.idContenido = idContenido;
		this.tipoContenidoArchivo = tipoContenidoArchivo;
		this.fechaCarga = fechaCarga;
	}

	public Contenido(long idContenido, TrackingPostulante trackingPostulante, TrackingMonitor trackingMonitor,
			Empresa empresa, Persona persona, TipoContenidoArchivo tipoContenidoArchivo, Date fechaCarga,
			byte[] contenido, String descripcion, String rutaAbsoluta) {
		this.idContenido = idContenido;
		this.trackingPostulante = trackingPostulante;
		this.trackingMonitor = trackingMonitor;
		this.empresa = empresa;
		this.persona = persona;
		this.tipoContenidoArchivo = tipoContenidoArchivo;
		this.fechaCarga = fechaCarga;
		this.contenido = contenido;
		this.descripcion = descripcion;
		this.rutaAbsoluta = rutaAbsoluta;
	}


	@Id
	@SequenceGenerator(name="seq_contenido", sequenceName=Constante.SECUENCIA_BD_CONTENIDO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_contenido")
	@Column(name = "ID_CONTENIDO", unique = true, nullable = false)
	public long getIdContenido() {
		return this.idContenido;
	}

	public void setIdContenido(long idContenido) {
		this.idContenido = idContenido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_CONTENIDO_ARCHIVO", nullable = false)
	public TipoContenidoArchivo getTipoContenidoArchivo() {
		return this.tipoContenidoArchivo;
	}

	public void setTipoContenidoArchivo(
			TipoContenidoArchivo tipoContenidoArchivo) {
		this.tipoContenidoArchivo = tipoContenidoArchivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CARGA", nullable = false, length = 29)
	public Date getFechaCarga() {
		return this.fechaCarga;
	}

	public void setFechaCarga(Date fechaCarga) {
		this.fechaCarga = fechaCarga;
	}

	@Column(name = "CONTENIDO")
	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

	@Column(name = "DESCRIPCION", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "ruta_absoluta", length = 250)
	public String getRutaAbsoluta() {
		return this.rutaAbsoluta;
	}

	public void setRutaAbsoluta(String rutaAbsoluta) {
		this.rutaAbsoluta = rutaAbsoluta;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tracking_postulante")
	public TrackingPostulante getTrackingPostulante() {
		return this.trackingPostulante;
	}

	public void setTrackingPostulante(TrackingPostulante trackingPostulante) {
		this.trackingPostulante = trackingPostulante;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tracking_monitor")
	public TrackingMonitor getTrackingMonitor() {
		return this.trackingMonitor;
	}

	public void setTrackingMonitor(TrackingMonitor trackingMonitor) {
		this.trackingMonitor = trackingMonitor;
	}
}
