package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import net.tce.util.Constante;

/**
 * DocumentoClasificacion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "DOCUMENTO_CLASIFICACION", uniqueConstraints = @UniqueConstraint(columnNames = "id_texto_clasificacion"))
public class DocumentoClasificacion implements java.io.Serializable {

	private long idDocumentoClasificacion;
	private Empresa empresa;
	private Perfil perfil;
	private Area area;
	private Persona persona;
	private Posicion posicion;
	private String idTextoClasificacion;
	private Integer estatusClasificacion;
	private String versionModelo;
	private String areasConfirmadas;
	private String categoria;
	private String categoriasAnalisis;
	private Date fechaModificacion;
	private boolean sincronizado;
	private boolean automatico;

	public DocumentoClasificacion() {
	}

	public DocumentoClasificacion(long idDocumentoClasificacion) {
		this.idDocumentoClasificacion = idDocumentoClasificacion;
	}

	public DocumentoClasificacion(long idDocumentoClasificacion,
			Empresa empresa, Perfil perfil, Area area, Persona persona,
			Posicion posicion, String idTextoClasificacion,
			Integer estatusClasificacion, String versionModelo,
			String areasConfirmadas, String categoria,
			String categoriasAnalisis, Date fechaModificacion,
			boolean sincronizado, boolean automatico) {
		this.idDocumentoClasificacion = idDocumentoClasificacion;
		this.empresa = empresa;
		this.perfil = perfil;
		this.area = area;
		this.persona = persona;
		this.posicion = posicion;
		this.idTextoClasificacion = idTextoClasificacion;
		this.estatusClasificacion = estatusClasificacion;
		this.versionModelo = versionModelo;
		this.areasConfirmadas = areasConfirmadas;
		this.categoria = categoria;
		this.categoriasAnalisis = categoriasAnalisis;
		this.fechaModificacion = fechaModificacion;
		this.sincronizado = sincronizado;
		this.automatico = automatico;
	}

	@Id
	@SequenceGenerator(name="seq_Documento_Clasificacion", sequenceName=Constante.SECUENCIA_BD_DOCUMENTO_CLASIFICACION, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Documento_Clasificacion")
	@Column(name = "id_documento_clasificacion", unique = true, nullable = false)
	public long getIdDocumentoClasificacion() {
		return this.idDocumentoClasificacion;
	}

	public void setIdDocumentoClasificacion(long idDocumentoClasificacion) {
		this.idDocumentoClasificacion = idDocumentoClasificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_area")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_posicion")
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	@Column(name = "id_texto_clasificacion", unique = true, length = 100)
	public String getIdTextoClasificacion() {
		return this.idTextoClasificacion;
	}

	public void setIdTextoClasificacion(String idTextoClasificacion) {
		this.idTextoClasificacion = idTextoClasificacion;
	}

	@Column(name = "estatus_clasificacion")
	public Integer getEstatusClasificacion() {
		return this.estatusClasificacion;
	}

	public void setEstatusClasificacion(Integer estatusClasificacion) {
		this.estatusClasificacion = estatusClasificacion;
	}

	@Column(name = "version_modelo", length = 100)
	public String getVersionModelo() {
		return this.versionModelo;
	}

	public void setVersionModelo(String versionModelo) {
		this.versionModelo = versionModelo;
	}

	@Column(name = "areas_confirmadas", length = 2500)
	public String getAreasConfirmadas() {
		return this.areasConfirmadas;
	}

	public void setAreasConfirmadas(String areasConfirmadas) {
		this.areasConfirmadas = areasConfirmadas;
	}

	@Column(name = "categoria", length = 2500)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "categorias_analisis", length = 2500)
	public String getCategoriasAnalisis() {
		return this.categoriasAnalisis;
	}

	public void setCategoriasAnalisis(String categoriasAnalisis) {
		this.categoriasAnalisis = categoriasAnalisis;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}
	
	@Column(name = "sincronizado", nullable = false)
	public boolean isSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(boolean sincronizado) {
		this.sincronizado = sincronizado;
	}

	@Column(name = "automatico", nullable = false)
	public boolean isAutomatico() {
		return this.automatico;
	}

	public void setAutomatico(boolean automatico) {
		this.automatico = automatico;
	}
}
