package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dominio generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "DOMINIO")
public class Dominio implements java.io.Serializable {

	private long idDominio;
	private String descripcion;
	private String significado;
	private BigDecimal ponderacion;
	private boolean estatusRegistro;
	private Set<PersonaIdioma> personaIdiomas = new HashSet<PersonaIdioma>(0);
	private Set<PoliticaMValor> politicaMValors = new HashSet<PoliticaMValor>(0);
	private Set<Habilidad> habilidads = new HashSet<Habilidad>(0);
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(
			0);

	public Dominio() {
	}

	public Dominio(long idDominio, String descripcion, BigDecimal ponderacion) {
		this.idDominio = idDominio;
		this.descripcion = descripcion;
		this.ponderacion = ponderacion;
	}

	public Dominio(long idDominio, String descripcion, String significado,
			BigDecimal ponderacion, boolean estatusRegistro,
			Set<PersonaIdioma> personaIdiomas,
			Set<PoliticaMValor> politicaMValors, Set<Habilidad> habilidads,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.idDominio = idDominio;
		this.descripcion = descripcion;
		this.significado = significado;
		this.ponderacion = ponderacion;
		this.estatusRegistro = estatusRegistro;
		this.personaIdiomas = personaIdiomas;
		this.politicaMValors = politicaMValors;
		this.habilidads = habilidads;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@Id
	@Column(name = "id_dominio", unique = true, nullable = false)
	public long getIdDominio() {
		return this.idDominio;
	}

	public void setIdDominio(long idDominio) {
		this.idDominio = idDominio;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ponderacion", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(BigDecimal ponderacion) {
		this.ponderacion = ponderacion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dominio")
	public Set<PersonaIdioma> getPersonaIdiomas() {
		return this.personaIdiomas;
	}

	public void setPersonaIdiomas(Set<PersonaIdioma> personaIdiomas) {
		this.personaIdiomas = personaIdiomas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dominio")
	public Set<PoliticaMValor> getPoliticaMValors() {
		return this.politicaMValors;
	}

	public void setPoliticaMValors(Set<PoliticaMValor> politicaMValors) {
		this.politicaMValors = politicaMValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dominio")
	public Set<Habilidad> getHabilidads() {
		return this.habilidads;
	}

	public void setHabilidads(Set<Habilidad> habilidads) {
		this.habilidads = habilidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dominio")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}
}
