package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EmpresaParametro generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "EMPRESA_PARAMETRO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"orden", "contexto", "id_tipo_parametro", "id_conf", "descripcion" }))
public class EmpresaParametro implements java.io.Serializable {

	private long idEmpresaParametro;
	private Conf conf;
	private TipoParametro tipoParametro;
	private long orden;
	private String contexto;
	private String valor;
	private String condicion;
	private String descripcion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String funcion;

	public EmpresaParametro() {
	}

	public EmpresaParametro(long idEmpresaParametro,
			TipoParametro tipoParametro, long orden, String descripcion,
			Date fechaCreacion) {
		this.idEmpresaParametro = idEmpresaParametro;
		this.tipoParametro = tipoParametro;
		this.orden = orden;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
	}

	public EmpresaParametro(long idEmpresaParametro, Conf conf,
			TipoParametro tipoParametro, long orden, String contexto,
			String valor, String condicion, String descripcion,
			Date fechaCreacion, Date fechaModificacion, String funcion) {
		this.idEmpresaParametro = idEmpresaParametro;
		this.conf = conf;
		this.tipoParametro = tipoParametro;
		this.orden = orden;
		this.contexto = contexto;
		this.valor = valor;
		this.condicion = condicion;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.funcion = funcion;
	}

	@Id
	@Column(name = "ID_EMPRESA_PARAMETRO", unique = true, nullable = false)
	public long getIdEmpresaParametro() {
		return this.idEmpresaParametro;
	}

	public void setIdEmpresaParametro(long idEmpresaParametro) {
		this.idEmpresaParametro = idEmpresaParametro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONF")
	public Conf getConf() {
		return this.conf;
	}

	public void setConf(Conf conf) {
		this.conf = conf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_PARAMETRO", nullable = false)
	public TipoParametro getTipoParametro() {
		return this.tipoParametro;
	}

	public void setTipoParametro(TipoParametro tipoParametro) {
		this.tipoParametro = tipoParametro;
	}

	@Column(name = "ORDEN", nullable = false)
	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

	@Column(name = "CONTEXTO", length = 100)
	public String getContexto() {
		return this.contexto;
	}

	public void setContexto(String contexto) {
		this.contexto = contexto;
	}

	@Column(name = "VALOR", length = 1500)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "CONDICION", length = 250)
	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CREACION", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_MODIFICACION", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "FUNCION", length = 100)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

}
