package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * EmpresaPerfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "EMPRESA_PERFIL", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_empresa", "id_perfil" }))
@DynamicUpdate
public class EmpresaPerfil implements java.io.Serializable {

	private long idEmpresaPerfil;
	private Empresa empresa;
	private Perfil perfil;
	private BigDecimal iap;
	private BigDecimal iapBruto;
	private Date fechaCreacion;
	private Date fechaModificacion;

	public EmpresaPerfil() {
	}

	public EmpresaPerfil(long idEmpresaPerfil, Empresa empresa, Perfil perfil,
			Date fechaCreacion) {
		this.idEmpresaPerfil = idEmpresaPerfil;
		this.empresa = empresa;
		this.perfil = perfil;
		this.fechaCreacion = fechaCreacion;
	}

	public EmpresaPerfil(long idEmpresaPerfil, Empresa empresa, Perfil perfil,
			BigDecimal iap, BigDecimal iapBruto, Date fechaCreacion,
			Date fechaModificacion) {
		this.idEmpresaPerfil = idEmpresaPerfil;
		this.empresa = empresa;
		this.perfil = perfil;
		this.iap = iap;
		this.iapBruto = iapBruto;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	@Id
	@SequenceGenerator(name="seq_empresaPerfil", sequenceName=Constante.SECUENCIA_BD_EMPRESA_PERFIL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_empresaPerfil")
	@Column(name = "ID_EMPRESA_PERFIL", unique = true, nullable = false)
	public long getIdEmpresaPerfil() {
		return this.idEmpresaPerfil;
	}

	public void setIdEmpresaPerfil(long idEmpresaPerfil) {
		this.idEmpresaPerfil = idEmpresaPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "IAP", precision = 131089, scale = 0)
	public BigDecimal getIap() {
		return this.iap;
	}

	public void setIap(BigDecimal iap) {
		this.iap = iap;
	}

	@Column(name = "IAP_BRUTO", precision = 131089, scale = 0)
	public BigDecimal getIapBruto() {
		return this.iapBruto;
	}

	public void setIapBruto(BigDecimal iapBruto) {
		this.iapBruto = iapBruto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CREACION", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_MODIFICACION", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
