package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpresaConf generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "EMPRESA_CONF")
public class EmpresaConf implements java.io.Serializable {

	private long idEmpresaConf;
	private Empresa empresa;
	private Conf conf;

	public EmpresaConf() {
	}

	public EmpresaConf(long idEmpresaConf) {
		this.idEmpresaConf = idEmpresaConf;
	}

	public EmpresaConf(long idEmpresaConf, Empresa empresa, Conf conf) {
		this.idEmpresaConf = idEmpresaConf;
		this.empresa = empresa;
		this.conf = conf;
	}

	@Id
	@Column(name = "ID_EMPRESA_CONF", unique = true, nullable = false)
	public long getIdEmpresaConf() {
		return this.idEmpresaConf;
	}

	public void setIdEmpresaConf(long idEmpresaConf) {
		this.idEmpresaConf = idEmpresaConf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONF")
	public Conf getConf() {
		return this.conf;
	}

	public void setConf(Conf conf) {
		this.conf = conf;
	}

}
