package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;


import net.tce.util.Constante;

/**
 * Escolaridad generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESCOLARIDAD")
@DynamicUpdate	
public class Escolaridad implements java.io.Serializable {

	private long idEscolaridad;
	private Mes mesByMesFin;
	private Pais pais;
	private Persona persona;
	private GradoAcademico gradoAcademico;
	private Mes mesByMesInicio;
	private EstatusEscolar estatusEscolar;
	private String nombreInstitucion;
	private String titulo;
	private String texto;
	private String textoFiltrado;
	private Short anioInicio;
	private Byte diaInicio;
	private Date fechaInicio;
	private Short anioFin;
	private Byte diaFin;
	private Date fechaFin;

	public Escolaridad() {
	}

	public Escolaridad(long idEscolaridad, Persona persona) {
		this.idEscolaridad = idEscolaridad;
		this.persona = persona;
	}

	public Escolaridad(long idEscolaridad, Mes mesByMesFin, Pais pais,
			Persona persona, GradoAcademico gradoAcademico, Mes mesByMesInicio,
			EstatusEscolar estatusEscolar, String nombreInstitucion,
			String titulo, String texto, String textoFiltrado,
			Short anioInicio, Byte diaInicio, Date fechaInicio, Short anioFin,
			Byte diaFin, Date fechaFin) {
		this.idEscolaridad = idEscolaridad;
		this.mesByMesFin = mesByMesFin;
		this.pais = pais;
		this.persona = persona;
		this.gradoAcademico = gradoAcademico;
		this.mesByMesInicio = mesByMesInicio;
		this.estatusEscolar = estatusEscolar;
		this.nombreInstitucion = nombreInstitucion;
		this.titulo = titulo;
		this.texto = texto;
		this.textoFiltrado = textoFiltrado;
		this.anioInicio = anioInicio;
		this.diaInicio = diaInicio;
		this.fechaInicio = fechaInicio;
		this.anioFin = anioFin;
		this.diaFin = diaFin;
		this.fechaFin = fechaFin;
	}

	@Id
	@SequenceGenerator(name="seq_referencia", sequenceName=Constante.SECUENCIA_BD_ESCOLARIDAD, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_referencia")
	@Column(name = "ID_ESCOLARIDAD", unique = true, nullable = false)
	public long getIdEscolaridad() {
		return this.idEscolaridad;
	}

	public void setIdEscolaridad(long idEscolaridad) {
		this.idEscolaridad = idEscolaridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MES_FIN")
	public Mes getMesByMesFin() {
		return this.mesByMesFin;
	}

	public void setMesByMesFin(Mes mesByMesFin) {
		this.mesByMesFin = mesByMesFin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GRADO_ACADEMICO")
	public GradoAcademico getGradoAcademico() {
		return this.gradoAcademico;
	}

	public void setGradoAcademico(GradoAcademico gradoAcademico) {
		this.gradoAcademico = gradoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MES_INICIO")
	public Mes getMesByMesInicio() {
		return this.mesByMesInicio;
	}

	public void setMesByMesInicio(Mes mesByMesInicio) {
		this.mesByMesInicio = mesByMesInicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTATUS_ESCOLAR")
	public EstatusEscolar getEstatusEscolar() {
		return this.estatusEscolar;
	}

	public void setEstatusEscolar(EstatusEscolar estatusEscolar) {
		this.estatusEscolar = estatusEscolar;
	}

	@Column(name = "NOMBRE_INSTITUCION", length = 250)
	public String getNombreInstitucion() {
		return this.nombreInstitucion;
	}

	public void setNombreInstitucion(String nombreInstitucion) {
		this.nombreInstitucion = nombreInstitucion;
	}

	@Column(name = "TITULO", length = 250)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "TEXTO", length = 2500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "TEXTO_FILTRADO", length = 2500)
	public String getTextoFiltrado() {
		return this.textoFiltrado;
	}

	public void setTextoFiltrado(String textoFiltrado) {
		this.textoFiltrado = textoFiltrado;
	}

	@Column(name = "ANIO_INICIO")
	public Short getAnioInicio() {
		return this.anioInicio;
	}

	public void setAnioInicio(Short anioInicio) {
		this.anioInicio = anioInicio;
	}

	@Column(name = "DIA_INICIO")
	public Byte getDiaInicio() {
		return this.diaInicio;
	}

	public void setDiaInicio(Byte diaInicio) {
		this.diaInicio = diaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "ANIO_FIN")
	public Short getAnioFin() {
		return this.anioFin;
	}

	public void setAnioFin(Short anioFin) {
		this.anioFin = anioFin;
	}

	@Column(name = "DIA_FIN")
	public Byte getDiaFin() {
		return this.diaFin;
	}

	public void setDiaFin(Byte diaFin) {
		this.diaFin = diaFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
