package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estado generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTADO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"clave_estado", "id_pais" }))
public class Estado implements java.io.Serializable {

	private long idEstado;
	private Pais pais;
	private String claveEstado;
	private String nombre;
	private BigDecimal mediaIntermunicipal;
	private BigDecimal desviacionEstIntermunicipal;
	private BigDecimal minDistanciaIntermunicipal;
	private BigDecimal maxDistanciaIntermunicipal;
	private boolean estatusRegistro;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);

	public Estado() {
	}

	public Estado(long idEstado, Pais pais, String claveEstado, String nombre,
			boolean estatusRegistro) {
		this.idEstado = idEstado;
		this.pais = pais;
		this.claveEstado = claveEstado;
		this.nombre = nombre;
		this.estatusRegistro = estatusRegistro;
	}

	public Estado(long idEstado, Pais pais, String claveEstado, String nombre,
			BigDecimal mediaIntermunicipal,
			BigDecimal desviacionEstIntermunicipal,
			BigDecimal minDistanciaIntermunicipal,
			BigDecimal maxDistanciaIntermunicipal, boolean estatusRegistro,
			Set<Municipio> municipios) {
		this.idEstado = idEstado;
		this.pais = pais;
		this.claveEstado = claveEstado;
		this.nombre = nombre;
		this.mediaIntermunicipal = mediaIntermunicipal;
		this.desviacionEstIntermunicipal = desviacionEstIntermunicipal;
		this.minDistanciaIntermunicipal = minDistanciaIntermunicipal;
		this.maxDistanciaIntermunicipal = maxDistanciaIntermunicipal;
		this.estatusRegistro = estatusRegistro;
		this.municipios = municipios;
	}

	@Id
	@Column(name = "ID_ESTADO", unique = true, nullable = false)
	public long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(long idEstado) {
		this.idEstado = idEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PAIS", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "CLAVE_ESTADO", nullable = false, length = 10)
	public String getClaveEstado() {
		return this.claveEstado;
	}

	public void setClaveEstado(String claveEstado) {
		this.claveEstado = claveEstado;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "MEDIA_INTERMUNICIPAL", precision = 131089, scale = 0)
	public BigDecimal getMediaIntermunicipal() {
		return this.mediaIntermunicipal;
	}

	public void setMediaIntermunicipal(BigDecimal mediaIntermunicipal) {
		this.mediaIntermunicipal = mediaIntermunicipal;
	}

	@Column(name = "DESVIACION_EST_INTERMUNICIPAL", precision = 131089, scale = 0)
	public BigDecimal getDesviacionEstIntermunicipal() {
		return this.desviacionEstIntermunicipal;
	}

	public void setDesviacionEstIntermunicipal(
			BigDecimal desviacionEstIntermunicipal) {
		this.desviacionEstIntermunicipal = desviacionEstIntermunicipal;
	}

	@Column(name = "MIN_DISTANCIA_INTERMUNICIPAL", precision = 131089, scale = 0)
	public BigDecimal getMinDistanciaIntermunicipal() {
		return this.minDistanciaIntermunicipal;
	}

	public void setMinDistanciaIntermunicipal(
			BigDecimal minDistanciaIntermunicipal) {
		this.minDistanciaIntermunicipal = minDistanciaIntermunicipal;
	}

	@Column(name = "MAX_DISTANCIA_INTERMUNICIPAL", precision = 131089, scale = 0)
	public BigDecimal getMaxDistanciaIntermunicipal() {
		return this.maxDistanciaIntermunicipal;
	}

	public void setMaxDistanciaIntermunicipal(
			BigDecimal maxDistanciaIntermunicipal) {
		this.maxDistanciaIntermunicipal = maxDistanciaIntermunicipal;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
