package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusOperativo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_OPERATIVO")
public class EstatusOperativo implements java.io.Serializable {

	private long idEstatusOperativo;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<PosibleCandidato> posibleCandidatos = new HashSet<PosibleCandidato>(
			0);
	private Set<Candidato> candidatos = new HashSet<Candidato>(0);

	public EstatusOperativo() {
	}

	public EstatusOperativo(long idEstatusOperativo, String descripcion) {
		this.idEstatusOperativo = idEstatusOperativo;
		this.descripcion = descripcion;
	}

	public EstatusOperativo(long idEstatusOperativo, String descripcion,
			String significado, boolean estatusRegistro,
			Set<PosibleCandidato> posibleCandidatos, Set<Candidato> candidatos) {
		this.idEstatusOperativo = idEstatusOperativo;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.posibleCandidatos = posibleCandidatos;
		this.candidatos = candidatos;
	}

	@Id
	@Column(name = "ID_ESTATUS_OPERATIVO", unique = true, nullable = false)
	public long getIdEstatusOperativo() {
		return this.idEstatusOperativo;
	}

	public void setIdEstatusOperativo(long idEstatusOperativo) {
		this.idEstatusOperativo = idEstatusOperativo;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusOperativo")
	public Set<PosibleCandidato> getPosibleCandidatos() {
		return this.posibleCandidatos;
	}

	public void setPosibleCandidatos(Set<PosibleCandidato> posibleCandidatos) {
		this.posibleCandidatos = posibleCandidatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusOperativo")
	public Set<Candidato> getCandidatos() {
		return this.candidatos;
	}

	public void setCandidatos(Set<Candidato> candidatos) {
		this.candidatos = candidatos;
	}

}
