package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusPosicion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_POSICION")
public class EstatusPosicion implements java.io.Serializable {

	private long idEstatusPosicion;
	private String descripcion;
	private String significado;
	private Boolean valorActivo;
	private boolean estatusRegistro;
	private Set<Posicion> posicions = new HashSet<Posicion>(0);

	public EstatusPosicion() {
	}

	public EstatusPosicion(long idEstatusPosicion, String descripcion) {
		this.idEstatusPosicion = idEstatusPosicion;
		this.descripcion = descripcion;
	}

	public EstatusPosicion(long idEstatusPosicion, String descripcion,
			String significado, Boolean valorActivo, boolean estatusRegistro,
			Set<Posicion> posicions) {
		this.idEstatusPosicion = idEstatusPosicion;
		this.descripcion = descripcion;
		this.significado = significado;
		this.valorActivo = valorActivo;
		this.estatusRegistro = estatusRegistro;
		this.posicions = posicions;
	}

	@Id
	@Column(name = "ID_ESTATUS_POSICION", unique = true, nullable = false)
	public long getIdEstatusPosicion() {
		return this.idEstatusPosicion;
	}

	public void setIdEstatusPosicion(long idEstatusPosicion) {
		this.idEstatusPosicion = idEstatusPosicion;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "VALOR_ACTIVO")
	public Boolean getValorActivo() {
		return this.valorActivo;
	}

	public void setValorActivo(Boolean valorActivo) {
		this.valorActivo = valorActivo;
	}

	@Column(name = "ESTATUS_REGISTRO", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusPosicion")
	public Set<Posicion> getPosicions() {
		return this.posicions;
	}

	public void setPosicions(Set<Posicion> posicions) {
		this.posicions = posicions;
	}

}
