package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusInscripcion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_INSCRIPCION")
public class EstatusInscripcion implements java.io.Serializable {

	private long idEstatusInscripcion;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public EstatusInscripcion() {
	}

	public EstatusInscripcion(long idEstatusInscripcion, String descripcion,
			boolean estatusRegistro) {
		this.idEstatusInscripcion = idEstatusInscripcion;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public EstatusInscripcion(long idEstatusInscripcion, String descripcion,
			String significado, boolean estatusRegistro, Set<Persona> personas,
			Set<Empresa> empresas) {
		this.idEstatusInscripcion = idEstatusInscripcion;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.personas = personas;
		this.empresas = empresas;
	}

	@Id
	@Column(name = "ID_ESTATUS_INSCRIPCION", unique = true, nullable = false)
	public long getIdEstatusInscripcion() {
		return this.idEstatusInscripcion;
	}

	public void setIdEstatusInscripcion(long idEstatusInscripcion) {
		this.idEstatusInscripcion = idEstatusInscripcion;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusInscripcion")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusInscripcion")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
