package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusEscolar generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_ESCOLAR")
public class EstatusEscolar implements java.io.Serializable {

	private long idEstatusEscolar;
	private String descripcion;
	private String significado;
	private byte nivel;
	private byte preponderancia;
	private boolean estatusRegistro;
	private Set<Escolaridad> escolaridads = new HashSet<Escolaridad>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<PoliticaMValor> politicaMValors = new HashSet<PoliticaMValor>(0);
	private Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMin = new HashSet<EmpresaPolitica>(
			0);
	private Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMax = new HashSet<EmpresaPolitica>(
			0);
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(
			0);

	public EstatusEscolar() {
	}

	public EstatusEscolar(long idEstatusEscolar, String descripcion,
			byte nivel, byte preponderancia) {
		this.idEstatusEscolar = idEstatusEscolar;
		this.descripcion = descripcion;
		this.nivel = nivel;
		this.preponderancia = preponderancia;
	}

	public EstatusEscolar(long idEstatusEscolar, String descripcion,
			String significado, byte nivel, byte preponderancia,
			boolean estatusRegistro, Set<Escolaridad> escolaridads,
			Set<Persona> personas, Set<PoliticaMValor> politicaMValors,
			Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMin,
			Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMax,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.idEstatusEscolar = idEstatusEscolar;
		this.descripcion = descripcion;
		this.significado = significado;
		this.nivel = nivel;
		this.preponderancia = preponderancia;
		this.estatusRegistro = estatusRegistro;
		this.escolaridads = escolaridads;
		this.personas = personas;
		this.politicaMValors = politicaMValors;
		this.empresaPoliticasForIdEstatusEscolarMin = empresaPoliticasForIdEstatusEscolarMin;
		this.empresaPoliticasForIdEstatusEscolarMax = empresaPoliticasForIdEstatusEscolarMax;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@Id
	@Column(name = "id_estatus_escolar", unique = true, nullable = false)
	public long getIdEstatusEscolar() {
		return this.idEstatusEscolar;
	}

	public void setIdEstatusEscolar(long idEstatusEscolar) {
		this.idEstatusEscolar = idEstatusEscolar;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "nivel", nullable = false)
	public byte getNivel() {
		return this.nivel;
	}

	public void setNivel(byte nivel) {
		this.nivel = nivel;
	}

	@Column(name = "preponderancia", nullable = false)
	public byte getPreponderancia() {
		return this.preponderancia;
	}

	public void setPreponderancia(byte preponderancia) {
		this.preponderancia = preponderancia;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolar")
	public Set<Escolaridad> getEscolaridads() {
		return this.escolaridads;
	}

	public void setEscolaridads(Set<Escolaridad> escolaridads) {
		this.escolaridads = escolaridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolar")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolar")
	public Set<PoliticaMValor> getPoliticaMValors() {
		return this.politicaMValors;
	}

	public void setPoliticaMValors(Set<PoliticaMValor> politicaMValors) {
		this.politicaMValors = politicaMValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolarByIdEstatusEscolarMin")
	public Set<EmpresaPolitica> getEmpresaPoliticasForIdEstatusEscolarMin() {
		return this.empresaPoliticasForIdEstatusEscolarMin;
	}

	public void setEmpresaPoliticasForIdEstatusEscolarMin(
			Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMin) {
		this.empresaPoliticasForIdEstatusEscolarMin = empresaPoliticasForIdEstatusEscolarMin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolarByIdEstatusEscolarMax")
	public Set<EmpresaPolitica> getEmpresaPoliticasForIdEstatusEscolarMax() {
		return this.empresaPoliticasForIdEstatusEscolarMax;
	}

	public void setEmpresaPoliticasForIdEstatusEscolarMax(
			Set<EmpresaPolitica> empresaPoliticasForIdEstatusEscolarMax) {
		this.empresaPoliticasForIdEstatusEscolarMax = empresaPoliticasForIdEstatusEscolarMax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEscolar")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

}
