package net.tce.model;

// Generated Sep 15, 2015 2:39:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusPerfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_PERFIL")
public class EstatusPerfil implements java.io.Serializable {

	private long idEstatusPerfil;
	private String descripcion;
	private boolean estatusRegistro;
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public EstatusPerfil() {
	}

	public EstatusPerfil(long idEstatusPerfil, String descripcion,
			boolean estatusRegistro) {
		this.idEstatusPerfil = idEstatusPerfil;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public EstatusPerfil(long idEstatusPerfil, String descripcion,
			boolean estatusRegistro, Set<Perfil> perfils) {
		this.idEstatusPerfil = idEstatusPerfil;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.perfils = perfils;
	}

	@Id
	@Column(name = "ID_ESTATUS_PERFIL", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdEstatusPerfil() {
		return this.idEstatusPerfil;
	}

	public void setIdEstatusPerfil(long idEstatusPerfil) {
		this.idEstatusPerfil = idEstatusPerfil;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS_REGISTRO", nullable = false, precision = 1, scale = 0)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusPerfil")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
