package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusProceso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "ESTATUS_PROCESO")
public class EstatusProceso implements java.io.Serializable {

	private long idEstatusProceso;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<ControlProceso> controlProcesos = new HashSet<ControlProceso>(0);

	public EstatusProceso() {
	}

	public EstatusProceso(long idEstatusProceso, String descripcion,
			boolean estatusRegistro) {
		this.idEstatusProceso = idEstatusProceso;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public EstatusProceso(long idEstatusProceso, String descripcion,
			String significado, boolean estatusRegistro,
			Set<ControlProceso> controlProcesos) {
		this.idEstatusProceso = idEstatusProceso;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.controlProcesos = controlProcesos;
	}

	@Id
	@Column(name = "ID_ESTATUS_PROCESO", unique = true, nullable = false)
	public long getIdEstatusProceso() {
		return this.idEstatusProceso;
	}

	public void setIdEstatusProceso(long idEstatusProceso) {
		this.idEstatusProceso = idEstatusProceso;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusProceso")
	public Set<ControlProceso> getControlProcesos() {
		return this.controlProcesos;
	}

	public void setControlProcesos(Set<ControlProceso> controlProcesos) {
		this.controlProcesos = controlProcesos;
	}

}
