package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * ExperienciaLaboral generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "EXPERIENCIA_LABORAL")
@DynamicUpdate
public class ExperienciaLaboral implements java.io.Serializable {

	private long idExperienciaLaboral;
	private TipoPrestacion tipoPrestacion;
	private NivelJerarquico nivelJerarquico;
	private Mes mesByMesFin;
	private Pais pais;
	private TipoContrato tipoContrato;
	private Persona persona;
	private Mes mesByMesInicio;
	private TipoJornada tipoJornada;
	private String nombreEmpresa;
	private String puesto;
	private String motivoSeparacion;
	private String texto;
	private String textoFiltrado;
	private Short anioInicio;
	private Byte diaInicio;
	private Date fechaInicio;
	private Short anioFin;
	private Byte diaFin;
	private Date fechaFin;
	private Boolean trabajoActual;
	private Boolean referencias;
	private Boolean genteACargo;
	private String complementoDireccion;
	public ExperienciaLaboral() {
	}

	public ExperienciaLaboral(long idExperienciaLaboral, Persona persona) {
		this.idExperienciaLaboral = idExperienciaLaboral;
		this.persona = persona;
	}

	public ExperienciaLaboral(long idExperienciaLaboral,
			TipoPrestacion tipoPrestacion, NivelJerarquico nivelJerarquico,
			Mes mesByMesFin, Pais pais, TipoContrato tipoContrato,
			Persona persona, Mes mesByMesInicio, TipoJornada tipoJornada,
			String nombreEmpresa, String puesto, String motivoSeparacion,
			String texto, String textoFiltrado, Short anioInicio,
			Byte diaInicio, Date fechaInicio, Short anioFin, Byte diaFin,
			Date fechaFin, Boolean trabajoActual, Boolean referencias,
			Boolean genteACargo, String complementoDireccion) {
		this.idExperienciaLaboral = idExperienciaLaboral;
		this.tipoPrestacion = tipoPrestacion;
		this.nivelJerarquico = nivelJerarquico;
		this.mesByMesFin = mesByMesFin;
		this.pais = pais;
		this.tipoContrato = tipoContrato;
		this.persona = persona;
		this.mesByMesInicio = mesByMesInicio;
		this.tipoJornada = tipoJornada;
		this.nombreEmpresa = nombreEmpresa;
		this.puesto = puesto;
		this.motivoSeparacion = motivoSeparacion;
		this.texto = texto;
		this.textoFiltrado = textoFiltrado;
		this.anioInicio = anioInicio;
		this.diaInicio = diaInicio;
		this.fechaInicio = fechaInicio;
		this.anioFin = anioFin;
		this.diaFin = diaFin;
		this.fechaFin = fechaFin;
		this.trabajoActual = trabajoActual;
		this.referencias = referencias;
		this.genteACargo = genteACargo;
		this.complementoDireccion = complementoDireccion;
	}

	@Id
	@SequenceGenerator(name="seq_experienciaLab", sequenceName=Constante.SECUENCIA_BD_EXPERIENCIA_LABORAL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_experienciaLab")
	@Column(name = "ID_EXPERIENCIA_LABORAL", unique = true, nullable = false)
	public long getIdExperienciaLaboral() {
		return this.idExperienciaLaboral;
	}

	public void setIdExperienciaLaboral(long idExperienciaLaboral) {
		this.idExperienciaLaboral = idExperienciaLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_PRESTACION")
	public TipoPrestacion getTipoPrestacion() {
		return this.tipoPrestacion;
	}

	public void setTipoPrestacion(TipoPrestacion tipoPrestacion) {
		this.tipoPrestacion = tipoPrestacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NIVEL_JERARQUICO")
	public NivelJerarquico getNivelJerarquico() {
		return this.nivelJerarquico;
	}

	public void setNivelJerarquico(NivelJerarquico nivelJerarquico) {
		this.nivelJerarquico = nivelJerarquico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MES_FIN")
	public Mes getMesByMesFin() {
		return this.mesByMesFin;
	}

	public void setMesByMesFin(Mes mesByMesFin) {
		this.mesByMesFin = mesByMesFin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PAIS")
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_CONTRATO")
	public TipoContrato getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(TipoContrato tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MES_INICIO")
	public Mes getMesByMesInicio() {
		return this.mesByMesInicio;
	}

	public void setMesByMesInicio(Mes mesByMesInicio) {
		this.mesByMesInicio = mesByMesInicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_JORNADA")
	public TipoJornada getTipoJornada() {
		return this.tipoJornada;
	}

	public void setTipoJornada(TipoJornada tipoJornada) {
		this.tipoJornada = tipoJornada;
	}

	@Column(name = "NOMBRE_EMPRESA", length = 100)
	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	@Column(name = "PUESTO", length = 100)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "MOTIVO_SEPARACION", length = 100)
	public String getMotivoSeparacion() {
		return this.motivoSeparacion;
	}

	public void setMotivoSeparacion(String motivoSeparacion) {
		this.motivoSeparacion = motivoSeparacion;
	}

	@Column(name = "TEXTO", length = 2500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "TEXTO_FILTRADO", length = 2500)
	public String getTextoFiltrado() {
		return this.textoFiltrado;
	}

	public void setTextoFiltrado(String textoFiltrado) {
		this.textoFiltrado = textoFiltrado;
	}

	@Column(name = "ANIO_INICIO")
	public Short getAnioInicio() {
		return this.anioInicio;
	}

	public void setAnioInicio(Short anioInicio) {
		this.anioInicio = anioInicio;
	}

	@Column(name = "DIA_INICIO")
	public Byte getDiaInicio() {
		return this.diaInicio;
	}

	public void setDiaInicio(Byte diaInicio) {
		this.diaInicio = diaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "ANIO_FIN")
	public Short getAnioFin() {
		return this.anioFin;
	}

	public void setAnioFin(Short anioFin) {
		this.anioFin = anioFin;
	}

	@Column(name = "DIA_FIN")
	public Byte getDiaFin() {
		return this.diaFin;
	}

	public void setDiaFin(Byte diaFin) {
		this.diaFin = diaFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "TRABAJO_ACTUAL")
	public Boolean getTrabajoActual() {
		return this.trabajoActual;
	}

	public void setTrabajoActual(Boolean trabajoActual) {
		this.trabajoActual = trabajoActual;
	}

	@Column(name = "REFERENCIAS")
	public Boolean getReferencias() {
		return this.referencias;
	}

	public void setReferencias(Boolean referencias) {
		this.referencias = referencias;
	}

	@Column(name = "GENTE_A_CARGO")
	public Boolean getGenteACargo() {
		return this.genteACargo;
	}

	public void setGenteACargo(Boolean genteACargo) {
		this.genteACargo = genteACargo;
	}

	@Column(name = "COMPLEMENTO_DIRECCION", length = 1500)
	public String getComplementoDireccion() {
		return this.complementoDireccion;
	}

	public void setComplementoDireccion(String complementoDireccion) {
		this.complementoDireccion = complementoDireccion;
	}

}
