package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filtro generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "FILTRO")
public class Filtro implements java.io.Serializable {

	private long idFiltro;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<PosicionFiltro> posicionFiltros = new HashSet<PosicionFiltro>(0);

	public Filtro() {
	}

	public Filtro(long idFiltro, String descripcion, boolean estatusRegistro) {
		this.idFiltro = idFiltro;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public Filtro(long idFiltro, String descripcion, String significado,
			boolean estatusRegistro, Set<PosicionFiltro> posicionFiltros) {
		this.idFiltro = idFiltro;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.posicionFiltros = posicionFiltros;
	}

	@Id
	@Column(name = "ID_FILTRO", unique = true, nullable = false)
	public long getIdFiltro() {
		return this.idFiltro;
	}

	public void setIdFiltro(long idFiltro) {
		this.idFiltro = idFiltro;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filtro")
	public Set<PosicionFiltro> getPosicionFiltros() {
		return this.posicionFiltros;
	}

	public void setPosicionFiltros(Set<PosicionFiltro> posicionFiltros) {
		this.posicionFiltros = posicionFiltros;
	}

}
