package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GradoAcademico generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "GRADO_ACADEMICO")
public class GradoAcademico implements java.io.Serializable {

	private long idGradoAcademico;
	private String descripcion;
	private String significado;
	private Byte nivel;
	private short dominio;
	private int degradacion;
	private int duracion;
	private boolean estatusRegistro;
	private Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMin = new HashSet<EmpresaPolitica>(
			0);
	private Set<PoliticaMValor> politicaMValors = new HashSet<PoliticaMValor>(0);
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(
			0);
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<Escolaridad> escolaridads = new HashSet<Escolaridad>(0);
	private Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMax = new HashSet<EmpresaPolitica>(
			0);

	public GradoAcademico() {
	}

	public GradoAcademico(long idGradoAcademico, String descripcion,
			short dominio, int degradacion, int duracion) {
		this.idGradoAcademico = idGradoAcademico;
		this.descripcion = descripcion;
		this.dominio = dominio;
		this.degradacion = degradacion;
		this.duracion = duracion;
	}

	public GradoAcademico(long idGradoAcademico, String descripcion,
			String significado, Byte nivel, short dominio, int degradacion,
			int duracion, boolean estatusRegistro,
			Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMin,
			Set<PoliticaMValor> politicaMValors,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors,
			Set<Persona> personas, Set<Escolaridad> escolaridads,
			Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMax) {
		this.idGradoAcademico = idGradoAcademico;
		this.descripcion = descripcion;
		this.significado = significado;
		this.nivel = nivel;
		this.dominio = dominio;
		this.degradacion = degradacion;
		this.duracion = duracion;
		this.estatusRegistro = estatusRegistro;
		this.empresaPoliticasForIdGradoAcademicoMin = empresaPoliticasForIdGradoAcademicoMin;
		this.politicaMValors = politicaMValors;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
		this.personas = personas;
		this.escolaridads = escolaridads;
		this.empresaPoliticasForIdGradoAcademicoMax = empresaPoliticasForIdGradoAcademicoMax;
	}

	@Id
	@Column(name = "id_grado_academico", unique = true, nullable = false)
	public long getIdGradoAcademico() {
		return this.idGradoAcademico;
	}

	public void setIdGradoAcademico(long idGradoAcademico) {
		this.idGradoAcademico = idGradoAcademico;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "nivel")
	public Byte getNivel() {
		return this.nivel;
	}

	public void setNivel(Byte nivel) {
		this.nivel = nivel;
	}

	@Column(name = "dominio", nullable = false)
	public short getDominio() {
		return this.dominio;
	}

	public void setDominio(short dominio) {
		this.dominio = dominio;
	}

	@Column(name = "degradacion", nullable = false)
	public int getDegradacion() {
		return this.degradacion;
	}

	public void setDegradacion(int degradacion) {
		this.degradacion = degradacion;
	}

	@Column(name = "duracion", nullable = false)
	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademicoByIdGradoAcademicoMin")
	public Set<EmpresaPolitica> getEmpresaPoliticasForIdGradoAcademicoMin() {
		return this.empresaPoliticasForIdGradoAcademicoMin;
	}

	public void setEmpresaPoliticasForIdGradoAcademicoMin(
			Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMin) {
		this.empresaPoliticasForIdGradoAcademicoMin = empresaPoliticasForIdGradoAcademicoMin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademico")
	public Set<PoliticaMValor> getPoliticaMValors() {
		return this.politicaMValors;
	}

	public void setPoliticaMValors(Set<PoliticaMValor> politicaMValors) {
		this.politicaMValors = politicaMValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademico")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademico")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademico")
	public Set<Escolaridad> getEscolaridads() {
		return this.escolaridads;
	}

	public void setEscolaridads(Set<Escolaridad> escolaridads) {
		this.escolaridads = escolaridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoAcademicoByIdGradoAcademicoMax")
	public Set<EmpresaPolitica> getEmpresaPoliticasForIdGradoAcademicoMax() {
		return this.empresaPoliticasForIdGradoAcademicoMax;
	}

	public void setEmpresaPoliticasForIdGradoAcademicoMax(
			Set<EmpresaPolitica> empresaPoliticasForIdGradoAcademicoMax) {
		this.empresaPoliticasForIdGradoAcademicoMax = empresaPoliticasForIdGradoAcademicoMax;
	}

}
