package net.tce.model;

// Generated Oct 13, 2015 5:56:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Habilidadpos generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "HABILIDADPOS")
public class Habilidadpos implements java.io.Serializable {

	private long idHabilidadpos;
	private Habilidadpos habilidadpos;
	private TipoHabilidad tipoHabilidad;
	private String descripcion;
	private boolean estatusRegistro;
	
	private Set<Habilidadpos> habilidadposes = new HashSet<Habilidadpos>(0);

	public Habilidadpos() {
	}

	public Habilidadpos(long idHabilidadpos, TipoHabilidad tipoHabilidad,
			String descripcion, boolean estatusRegistro) {
		this.idHabilidadpos = idHabilidadpos;
		this.tipoHabilidad = tipoHabilidad;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public Habilidadpos(long idHabilidadpos, Habilidadpos habilidadpos,
			TipoHabilidad tipoHabilidad, String descripcion,
			boolean estatusRegistro,
			Set<Habilidadpos> habilidadposes) {
		this.idHabilidadpos = idHabilidadpos;
		this.habilidadpos = habilidadpos;
		this.tipoHabilidad = tipoHabilidad;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.habilidadposes = habilidadposes;
	}

	@Id
	@Column(name = "ID_HABILIDADPOS", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdHabilidadpos() {
		return this.idHabilidadpos;
	}

	public void setIdHabilidadpos(long idHabilidadpos) {
		this.idHabilidadpos = idHabilidadpos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SIMILAR")
	public Habilidadpos getHabilidadpos() {
		return this.habilidadpos;
	}

	public void setHabilidadpos(Habilidadpos habilidadpos) {
		this.habilidadpos = habilidadpos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_HABILIDAD", nullable = false)
	public TipoHabilidad getTipoHabilidad() {
		return this.tipoHabilidad;
	}

	public void setTipoHabilidad(TipoHabilidad tipoHabilidad) {
		this.tipoHabilidad = tipoHabilidad;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS_REGISTRO", nullable = false, precision = 1, scale = 0)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habilidadpos")
	public Set<Habilidadpos> getHabilidadposes() {
		return this.habilidadposes;
	}

	public void setHabilidadposes(Set<Habilidadpos> habilidadposes) {
		this.habilidadposes = habilidadposes;
	}

}
