package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * HistoricoPassword generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "HISTORICO_PASSWORD")
public class HistoricoPassword implements java.io.Serializable {

	private long idHistoricoPassword;
	private Persona persona;
	private String password;
	private Date fecha;
	private String pswIniSystem;

	public HistoricoPassword() {
	}

	public HistoricoPassword(long idHistoricoPassword, Persona persona,
			String password, Date fecha) {
		this.idHistoricoPassword = idHistoricoPassword;
		this.persona = persona;
		this.password = password;
		this.fecha = fecha;
	}

	public HistoricoPassword(long idHistoricoPassword, Persona persona,
			String password, Date fecha, String pswIniSystem) {
		this.idHistoricoPassword = idHistoricoPassword;
		this.persona = persona;
		this.password = password;
		this.fecha = fecha;
		this.pswIniSystem = pswIniSystem;
	}

	@Id
	@SequenceGenerator(name="seq_Password", sequenceName=Constante.SECUENCIA_BD_HISTORICO_PASSWORD, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Password")
	@Column(name = "ID_HISTORICO_PASSWORD", unique = true, nullable = false)
	public long getIdHistoricoPassword() {
		return this.idHistoricoPassword;
	}

	public void setIdHistoricoPassword(long idHistoricoPassword) {
		this.idHistoricoPassword = idHistoricoPassword;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "psw_ini_system", length = 100)
	public String getPswIniSystem() {
		return this.pswIniSystem;
	}

	public void setPswIniSystem(String pswIniSystem) {
		this.pswIniSystem = pswIniSystem;
	}

}
