package net.tce.model;

// Generated Jan 19, 2017 6:31:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "IDIOMA")
public class Idioma implements java.io.Serializable {

	private long idIdioma;
	private String descripcion;
	private boolean estatusRegistro;
	private Set<PoliticaMValor> politicaMValors = new HashSet<PoliticaMValor>(0);
	private Set<PersonaIdioma> personaIdiomas = new HashSet<PersonaIdioma>(0);
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(
			0);

	public Idioma() {
	}

	public Idioma(long idIdioma, String descripcion) {
		this.idIdioma = idIdioma;
		this.descripcion = descripcion;
	}

	public Idioma(long idIdioma, String descripcion, boolean estatusRegistro,
			Set<PoliticaMValor> politicaMValors,
			Set<PersonaIdioma> personaIdiomas,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.idIdioma = idIdioma;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.politicaMValors = politicaMValors;
		this.personaIdiomas = personaIdiomas;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@Id
	@Column(name = "id_idioma", unique = true, nullable = false)
	public long getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(long idIdioma) {
		this.idIdioma = idIdioma;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idioma")
	public Set<PoliticaMValor> getPoliticaMValors() {
		return this.politicaMValors;
	}

	public void setPoliticaMValors(Set<PoliticaMValor> politicaMValors) {
		this.politicaMValors = politicaMValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idioma")
	public Set<PersonaIdioma> getPersonaIdiomas() {
		return this.personaIdiomas;
	}

	public void setPersonaIdiomas(Set<PersonaIdioma> personaIdiomas) {
		this.personaIdiomas = personaIdiomas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idioma")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}
}
