package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mecanismo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "MECANISMO")
public class Mecanismo implements java.io.Serializable {

	private long idMecanismo;
	private String descripcion;
	private String significado;
	private boolean inmediato;
	private boolean estatusRegistro;
	private Set<TipoEventoMecanismo> tipoEventoMecanismos = new HashSet<TipoEventoMecanismo>(
			0);

	public Mecanismo() {
	}

	public Mecanismo(long idMecanismo, String descripcion, boolean inmediato,
			boolean estatusRegistro) {
		this.idMecanismo = idMecanismo;
		this.descripcion = descripcion;
		this.inmediato = inmediato;
		this.estatusRegistro = estatusRegistro;
	}

	public Mecanismo(long idMecanismo, String descripcion, String significado,
			boolean inmediato, boolean estatusRegistro,
			Set<TipoEventoMecanismo> tipoEventoMecanismos) {
		this.idMecanismo = idMecanismo;
		this.descripcion = descripcion;
		this.significado = significado;
		this.inmediato = inmediato;
		this.estatusRegistro = estatusRegistro;
		this.tipoEventoMecanismos = tipoEventoMecanismos;
	}

	@Id
	@Column(name = "ID_MECANISMO", unique = true, nullable = false)
	public long getIdMecanismo() {
		return this.idMecanismo;
	}

	public void setIdMecanismo(long idMecanismo) {
		this.idMecanismo = idMecanismo;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "INMEDIATO", nullable = false)
	public boolean isInmediato() {
		return this.inmediato;
	}

	public void setInmediato(boolean inmediato) {
		this.inmediato = inmediato;
	}

	@Column(name = "ESTATUS_REGISTRO", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mecanismo")
	public Set<TipoEventoMecanismo> getTipoEventoMecanismos() {
		return this.tipoEventoMecanismos;
	}

	public void setTipoEventoMecanismos(
			Set<TipoEventoMecanismo> tipoEventoMecanismos) {
		this.tipoEventoMecanismos = tipoEventoMecanismos;
	}

}
