package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Mes generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "MES")
public class Mes implements java.io.Serializable {

	private byte idMes;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Escolaridad> escolaridadsForMesInicio = new HashSet<Escolaridad>(
			0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);
	private Set<Posicion> posicionsForMesCaducidad = new HashSet<Posicion>(0);
	private Set<Escolaridad> escolaridadsForMesFin = new HashSet<Escolaridad>(0);
	private Set<Posicion> posicionsForMesProgramacion = new HashSet<Posicion>(0);
	private Set<ExperienciaLaboral> experienciaLaboralsForMesInicio = new HashSet<ExperienciaLaboral>(
			0);
	private Set<ExperienciaLaboral> experienciaLaboralsForMesFin = new HashSet<ExperienciaLaboral>(
			0);
	private Set<CertificacionEmpresa> certificacionEmpresas = new HashSet<CertificacionEmpresa>(
			0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Mes() {
	}

	public Mes(byte idMes, String descripcion) {
		this.idMes = idMes;
		this.descripcion = descripcion;
	}

	public Mes(byte idMes, String descripcion, String significado,
			boolean estatusRegistro, Set<Escolaridad> escolaridadsForMesInicio,
			Set<Empresa> empresas, Set<Posicion> posicionsForMesCaducidad,
			Set<Escolaridad> escolaridadsForMesFin,
			Set<Posicion> posicionsForMesProgramacion,
			Set<ExperienciaLaboral> experienciaLaboralsForMesInicio,
			Set<ExperienciaLaboral> experienciaLaboralsForMesFin,
			Set<CertificacionEmpresa> certificacionEmpresas,
			Set<Persona> personas) {
		this.idMes = idMes;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.escolaridadsForMesInicio = escolaridadsForMesInicio;
		this.empresas = empresas;
		this.posicionsForMesCaducidad = posicionsForMesCaducidad;
		this.escolaridadsForMesFin = escolaridadsForMesFin;
		this.posicionsForMesProgramacion = posicionsForMesProgramacion;
		this.experienciaLaboralsForMesInicio = experienciaLaboralsForMesInicio;
		this.experienciaLaboralsForMesFin = experienciaLaboralsForMesFin;
		this.certificacionEmpresas = certificacionEmpresas;
		this.personas = personas;
	}

	@Id
	@Column(name = "id_mes", unique = true, nullable = false)
	public byte getIdMes() {
		return this.idMes;
	}

	public void setIdMes(byte idMes) {
		this.idMes = idMes;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesInicio")
	public Set<Escolaridad> getEscolaridadsForMesInicio() {
		return this.escolaridadsForMesInicio;
	}

	public void setEscolaridadsForMesInicio(
			Set<Escolaridad> escolaridadsForMesInicio) {
		this.escolaridadsForMesInicio = escolaridadsForMesInicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mes")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesCaducidad")
	public Set<Posicion> getPosicionsForMesCaducidad() {
		return this.posicionsForMesCaducidad;
	}

	public void setPosicionsForMesCaducidad(
			Set<Posicion> posicionsForMesCaducidad) {
		this.posicionsForMesCaducidad = posicionsForMesCaducidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesFin")
	public Set<Escolaridad> getEscolaridadsForMesFin() {
		return this.escolaridadsForMesFin;
	}

	public void setEscolaridadsForMesFin(Set<Escolaridad> escolaridadsForMesFin) {
		this.escolaridadsForMesFin = escolaridadsForMesFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesProgramacion")
	public Set<Posicion> getPosicionsForMesProgramacion() {
		return this.posicionsForMesProgramacion;
	}

	public void setPosicionsForMesProgramacion(
			Set<Posicion> posicionsForMesProgramacion) {
		this.posicionsForMesProgramacion = posicionsForMesProgramacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesInicio")
	public Set<ExperienciaLaboral> getExperienciaLaboralsForMesInicio() {
		return this.experienciaLaboralsForMesInicio;
	}

	public void setExperienciaLaboralsForMesInicio(
			Set<ExperienciaLaboral> experienciaLaboralsForMesInicio) {
		this.experienciaLaboralsForMesInicio = experienciaLaboralsForMesInicio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesByMesFin")
	public Set<ExperienciaLaboral> getExperienciaLaboralsForMesFin() {
		return this.experienciaLaboralsForMesFin;
	}

	public void setExperienciaLaboralsForMesFin(
			Set<ExperienciaLaboral> experienciaLaboralsForMesFin) {
		this.experienciaLaboralsForMesFin = experienciaLaboralsForMesFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mes")
	public Set<CertificacionEmpresa> getCertificacionEmpresas() {
		return this.certificacionEmpresas;
	}

	public void setCertificacionEmpresas(
			Set<CertificacionEmpresa> certificacionEmpresas) {
		this.certificacionEmpresas = certificacionEmpresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mes")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
