package net.tce.model;

// Generated Oct 2, 2018 7:18:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * ModeloRscPosFase generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "modelo_rsc_pos_fase")
public class ModeloRscPosFase implements java.io.Serializable {

	private long idModeloRscPosFase;
	private ModeloRscPosFase modeloRscPosFase;
	private ModeloRscPos modeloRscPos;
	private short orden;
	private short actividad;
	private Short dias;
	private String nombre;
	private String descripcion;
	private boolean subirArchivo;
	private boolean bajarArchivo;
	private boolean editarComentario;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean activo;
	private Set<TrackingPostulante> trackingPostulantes = new HashSet<TrackingPostulante>(0);
	private Set<Monitor> monitors = new HashSet<Monitor>(0);
	private Set<ModeloRscPosFase> modeloRscPosFases = new HashSet<ModeloRscPosFase>(0);

	public ModeloRscPosFase() {
	}

	public ModeloRscPosFase(long idModeloRscPosFase, ModeloRscPos modeloRscPos, short orden, short actividad,
			String nombre, boolean subirArchivo, boolean bajarArchivo, boolean editarComentario, boolean activo) {
		this.idModeloRscPosFase = idModeloRscPosFase;
		this.modeloRscPos = modeloRscPos;
		this.orden = orden;
		this.actividad = actividad;
		this.nombre = nombre;
		this.subirArchivo = subirArchivo;
		this.bajarArchivo = bajarArchivo;
		this.editarComentario = editarComentario;
		this.activo = activo;
	}

	public ModeloRscPosFase(long idModeloRscPosFase, ModeloRscPosFase modeloRscPosFase, ModeloRscPos modeloRscPos,
			short orden, short actividad, Short dias, String nombre, String descripcion, boolean subirArchivo,
			boolean bajarArchivo, boolean editarComentario, Date fechaInicio, Date fechaFin, boolean activo,
			Set<TrackingPostulante> trackingPostulantes, Set<Monitor> monitors,
			Set<ModeloRscPosFase> modeloRscPosFases) {
		this.idModeloRscPosFase = idModeloRscPosFase;
		this.modeloRscPosFase = modeloRscPosFase;
		this.modeloRscPos = modeloRscPos;
		this.orden = orden;
		this.actividad = actividad;
		this.dias = dias;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.subirArchivo = subirArchivo;
		this.bajarArchivo = bajarArchivo;
		this.editarComentario = editarComentario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.activo = activo;
		this.trackingPostulantes = trackingPostulantes;
		this.monitors = monitors;
		this.modeloRscPosFases = modeloRscPosFases;
	}
	@Id
	@SequenceGenerator(name="seq_modelRSC_pos_fase", sequenceName=Constante.SECUENCIA_BD_MODELO_RSC_POSICION_FASE, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_modelRSC_pos_fase")
	@Column(name = "id_modelo_rsc_pos_fase", unique = true, nullable = false)
	public long getIdModeloRscPosFase() {
		return this.idModeloRscPosFase;
	}

	public void setIdModeloRscPosFase(long idModeloRscPosFase) {
		this.idModeloRscPosFase = idModeloRscPosFase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modelo_rsc_pos_fase_rel")
	public ModeloRscPosFase getModeloRscPosFase() {
		return this.modeloRscPosFase;
	}

	public void setModeloRscPosFase(ModeloRscPosFase modeloRscPosFase) {
		this.modeloRscPosFase = modeloRscPosFase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modelo_rsc_pos", nullable = false)
	public ModeloRscPos getModeloRscPos() {
		return this.modeloRscPos;
	}

	public void setModeloRscPos(ModeloRscPos modeloRscPos) {
		this.modeloRscPos = modeloRscPos;
	}

	@Column(name = "orden", nullable = false)
	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}
	
	@Column(name = "actividad", nullable = false)
	public short getActividad() {
		return this.actividad;
	}

	public void setActividad(short actividad) {
		this.actividad = actividad;
	}
	
	@Column(name = "dias")
	public Short getDias() {
		return this.dias;
	}

	public void setDias(Short dias) {
		this.dias = dias;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "subir_archivo", nullable = false)
	public boolean isSubirArchivo() {
		return this.subirArchivo;
	}

	public void setSubirArchivo(boolean subirArchivo) {
		this.subirArchivo = subirArchivo;
	}

	@Column(name = "bajar_archivo", nullable = false)
	public boolean isBajarArchivo() {
		return this.bajarArchivo;
	}

	public void setBajarArchivo(boolean bajarArchivo) {
		this.bajarArchivo = bajarArchivo;
	}

	@Column(name = "editar_comentario", nullable = false)
	public boolean isEditarComentario() {
		return this.editarComentario;
	}

	public void setEditarComentario(boolean editarComentario) {
		this.editarComentario = editarComentario;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
		
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloRscPosFase")
	@Cascade({CascadeType.DELETE})	
	public Set<Monitor> getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set<Monitor> monitors) {
		this.monitors = monitors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloRscPosFase")
	public Set<ModeloRscPosFase> getModeloRscPosFases() {
		return this.modeloRscPosFases;
	}

	public void setModeloRscPosFases(Set<ModeloRscPosFase> modeloRscPosFases) {
		this.modeloRscPosFases = modeloRscPosFases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloRscPosFase")
	public Set<TrackingPostulante> getTrackingPostulantes() {
		return this.trackingPostulantes;
	}

	public void setTrackingPostulantes(
			Set<TrackingPostulante> trackingPostulantes) {
		this.trackingPostulantes = trackingPostulantes;
	}

}
