package net.tce.model;

// Generated Sep 11, 2018 12:40:00 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * ModeloRscFase generated by hbm2java
 */
@Entity
@Table(name = "modelo_rsc_fase")
public class ModeloRscFase implements java.io.Serializable {

	private long idModeloRscFase;
	private ModeloRsc modeloRsc;
	private Short orden;
	private String nombre;
	private String descripcion;
	private Short actividad;

	public ModeloRscFase() {
	}

	public ModeloRscFase(long idModeloRscFase, ModeloRsc modeloRsc) {
		this.idModeloRscFase = idModeloRscFase;
		this.modeloRsc = modeloRsc;
	}

	public ModeloRscFase(long idModeloRscFase, ModeloRsc modeloRsc,
			Short orden, String nombre, String descripcion, Short actividad) {
		this.idModeloRscFase = idModeloRscFase;
		this.modeloRsc = modeloRsc;
		this.orden = orden;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.actividad = actividad;
	}

	@Id
	@SequenceGenerator(name="seq_modelRSC_fase", sequenceName=Constante.SECUENCIA_BD_MODELO_RSC_FASE, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_modelRSC_fase")
	@Column(name = "id_modelo_rsc_fase", unique = true, nullable = false)
	public long getIdModeloRscFase() {
		return this.idModeloRscFase;
	}

	public void setIdModeloRscFase(long idModeloRscFase) {
		this.idModeloRscFase = idModeloRscFase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modelo_rsc", nullable = false)
	public ModeloRsc getModeloRsc() {
		return this.modeloRsc;
	}

	public void setModeloRsc(ModeloRsc modeloRsc) {
		this.modeloRsc = modeloRsc;
	}

	@Column(name = "orden", nullable = false)
	public Short getOrden() {
		return this.orden;
	}

	public void setOrden(Short orden) {
		this.orden = orden;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	@Column(name = "actividad", nullable = false)
	public Short getActividad() {
		return this.actividad;
	}

	public void setActividad(Short actividad) {
		this.actividad = actividad;
	}
}
