package net.tce.model;

// Generated Sep 11, 2018 12:40:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import net.tce.util.Constante;

/**
 * ModeloRsc generated by hbm2java
 */
@Entity
@Table(name = "modelo_rsc")
public class ModeloRsc implements java.io.Serializable {

	private long idModeloRsc;
	private TipoModeloRsc tipoModeloRsc;
	private String nombre;
	private String descripcion;
	private Boolean activo;
	private Set<ModeloRscFase> modeloRscFases = new HashSet<ModeloRscFase>(0);

	public ModeloRsc() {
	}

	public ModeloRsc(long idModeloRsc, TipoModeloRsc tipoModeloRsc,
			String nombre) {
		this.idModeloRsc = idModeloRsc;
		this.tipoModeloRsc = tipoModeloRsc;
		this.nombre = nombre;
	}

	public ModeloRsc(long idModeloRsc, TipoModeloRsc tipoModeloRsc,
			String nombre, String descripcion, Boolean activo,
			 Set<ModeloRscFase> modeloRscFases) {
		this.idModeloRsc = idModeloRsc;
		this.tipoModeloRsc = tipoModeloRsc;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activo = activo;
		this.modeloRscFases = modeloRscFases;
	}

	@Id
	@SequenceGenerator(name="seq_modelRSC", sequenceName=Constante.SECUENCIA_BD_MODELO_RSC, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_modelRSC")
	@Column(name = "id_modelo_rsc", unique = true, nullable = false)
	public long getIdModeloRsc() {
		return this.idModeloRsc;
	}

	public void setIdModeloRsc(long idModeloRsc) {
		this.idModeloRsc = idModeloRsc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_modelo_rsc", nullable = false)
	public TipoModeloRsc getTipoModeloRsc() {
		return this.tipoModeloRsc;
	}

	public void setTipoModeloRsc(TipoModeloRsc tipoModeloRsc) {
		this.tipoModeloRsc = tipoModeloRsc;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modeloRsc")
	@Cascade({CascadeType.DELETE})	
	public Set<ModeloRscFase> getModeloRscFases() {
		return this.modeloRscFases;
	}

	public void setModeloRscFases(Set<ModeloRscFase> modeloRscFases) {
		this.modeloRscFases = modeloRscFases;
	}

}
