package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MunicipioAdyacencia generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "MUNICIPIO_ADYACENCIA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_municipio", "id_municipio_adyacente" }))
public class MunicipioAdyacencia implements java.io.Serializable {

	private long idMunicipioAdyacencia;
	private Municipio municipioByIdMunicipio;
	private Municipio municipioByIdMunicipioAdyacente;
	private BigDecimal distancia;
	private Short rango;

	public MunicipioAdyacencia() {
	}

	public MunicipioAdyacencia(long idMunicipioAdyacencia,
			Municipio municipioByIdMunicipio,
			Municipio municipioByIdMunicipioAdyacente) {
		this.idMunicipioAdyacencia = idMunicipioAdyacencia;
		this.municipioByIdMunicipio = municipioByIdMunicipio;
		this.municipioByIdMunicipioAdyacente = municipioByIdMunicipioAdyacente;
	}

	public MunicipioAdyacencia(long idMunicipioAdyacencia,
			Municipio municipioByIdMunicipio,
			Municipio municipioByIdMunicipioAdyacente, BigDecimal distancia,
			Short rango) {
		this.idMunicipioAdyacencia = idMunicipioAdyacencia;
		this.municipioByIdMunicipio = municipioByIdMunicipio;
		this.municipioByIdMunicipioAdyacente = municipioByIdMunicipioAdyacente;
		this.distancia = distancia;
		this.rango = rango;
	}

	@Id
	@Column(name = "ID_MUNICIPIO_ADYACENCIA", unique = true, nullable = false)
	public long getIdMunicipioAdyacencia() {
		return this.idMunicipioAdyacencia;
	}

	public void setIdMunicipioAdyacencia(long idMunicipioAdyacencia) {
		this.idMunicipioAdyacencia = idMunicipioAdyacencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MUNICIPIO", nullable = false)
	public Municipio getMunicipioByIdMunicipio() {
		return this.municipioByIdMunicipio;
	}

	public void setMunicipioByIdMunicipio(Municipio municipioByIdMunicipio) {
		this.municipioByIdMunicipio = municipioByIdMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MUNICIPIO_ADYACENTE", nullable = false)
	public Municipio getMunicipioByIdMunicipioAdyacente() {
		return this.municipioByIdMunicipioAdyacente;
	}

	public void setMunicipioByIdMunicipioAdyacente(
			Municipio municipioByIdMunicipioAdyacente) {
		this.municipioByIdMunicipioAdyacente = municipioByIdMunicipioAdyacente;
	}

	@Column(name = "DISTANCIA", precision = 131089, scale = 0)
	public BigDecimal getDistancia() {
		return this.distancia;
	}

	public void setDistancia(BigDecimal distancia) {
		this.distancia = distancia;
	}

	@Column(name = "RANGO")
	public Short getRango() {
		return this.rango;
	}

	public void setRango(Short rango) {
		this.rango = rango;
	}

}
