package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MunicipioDistancia generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "MUNICIPIO_DISTANCIA")
public class MunicipioDistancia implements java.io.Serializable {

	private long idMunicipioDistancia;
	private Municipio municipioByIdMunicipioRelacionado;
	private Municipio municipioByIdMunicipio;
	private BigDecimal distancia;

	public MunicipioDistancia() {
	}

	public MunicipioDistancia(long idMunicipioDistancia,
			Municipio municipioByIdMunicipioRelacionado,
			Municipio municipioByIdMunicipio) {
		this.idMunicipioDistancia = idMunicipioDistancia;
		this.municipioByIdMunicipioRelacionado = municipioByIdMunicipioRelacionado;
		this.municipioByIdMunicipio = municipioByIdMunicipio;
	}

	public MunicipioDistancia(long idMunicipioDistancia,
			Municipio municipioByIdMunicipioRelacionado,
			Municipio municipioByIdMunicipio, BigDecimal distancia) {
		this.idMunicipioDistancia = idMunicipioDistancia;
		this.municipioByIdMunicipioRelacionado = municipioByIdMunicipioRelacionado;
		this.municipioByIdMunicipio = municipioByIdMunicipio;
		this.distancia = distancia;
	}

	@Id
	@Column(name = "ID_MUNICIPIO_DISTANCIA", unique = true, nullable = false)
	public long getIdMunicipioDistancia() {
		return this.idMunicipioDistancia;
	}

	public void setIdMunicipioDistancia(long idMunicipioDistancia) {
		this.idMunicipioDistancia = idMunicipioDistancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MUNICIPIO_RELACIONADO", nullable = false)
	public Municipio getMunicipioByIdMunicipioRelacionado() {
		return this.municipioByIdMunicipioRelacionado;
	}

	public void setMunicipioByIdMunicipioRelacionado(
			Municipio municipioByIdMunicipioRelacionado) {
		this.municipioByIdMunicipioRelacionado = municipioByIdMunicipioRelacionado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MUNICIPIO", nullable = false)
	public Municipio getMunicipioByIdMunicipio() {
		return this.municipioByIdMunicipio;
	}

	public void setMunicipioByIdMunicipio(Municipio municipioByIdMunicipio) {
		this.municipioByIdMunicipio = municipioByIdMunicipio;
	}

	@Column(name = "DISTANCIA", precision = 131089, scale = 0)
	public BigDecimal getDistancia() {
		return this.distancia;
	}

	public void setDistancia(BigDecimal distancia) {
		this.distancia = distancia;
	}

}
