package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * Notificacion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "NOTIFICACION")
public class Notificacion implements java.io.Serializable {

	private long idNotificacion;
	private Persona persona;
	private TipoEvento tipoEvento;
	private Long idEmisor;
	private byte tipoEmisor;
	private Date fechaCreacion;
	private Boolean vista;
	private Boolean desplegada;
	private Integer prioridad;
	private String listaMecanismoPasivo;
	private String listaMecanismoInmediato;
	private String texto;

	public Notificacion() {
	}

	public Notificacion(long idNotificacion, Persona persona,
			TipoEvento tipoEvento, byte tipoEmisor, Date fechaCreacion) {
		this.idNotificacion = idNotificacion;
		this.persona = persona;
		this.tipoEvento = tipoEvento;
		this.tipoEmisor = tipoEmisor;
		this.fechaCreacion = fechaCreacion;
	}

	public Notificacion(long idNotificacion, Persona persona,
			TipoEvento tipoEvento, Long idEmisor, byte tipoEmisor,
			Date fechaCreacion, Boolean vista, Boolean desplegada,
			Integer prioridad, String listaMecanismoPasivo,
			String listaMecanismoInmediato, String texto) {
		this.idNotificacion = idNotificacion;
		this.persona = persona;
		this.tipoEvento = tipoEvento;
		this.idEmisor = idEmisor;
		this.tipoEmisor = tipoEmisor;
		this.fechaCreacion = fechaCreacion;
		this.vista = vista;
		this.desplegada = desplegada;
		this.prioridad = prioridad;
		this.listaMecanismoPasivo = listaMecanismoPasivo;
		this.listaMecanismoInmediato = listaMecanismoInmediato;
		this.texto = texto;
	}

	@Id
	@SequenceGenerator(name="seq_notificacion", sequenceName=Constante.SECUENCIA_BD_NOTIFICACION, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_notificacion")
	@Column(name = "ID_NOTIFICACION", unique = true, nullable = false)
	public long getIdNotificacion() {
		return this.idNotificacion;
	}

	public void setIdNotificacion(long idNotificacion) {
		this.idNotificacion = idNotificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_receptor", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_evento", nullable = false)
	public TipoEvento getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(TipoEvento tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	@Column(name = "id_emisor")
	public Long getIdEmisor() {
		return this.idEmisor;
	}

	public void setIdEmisor(Long idEmisor) {
		this.idEmisor = idEmisor;
	}

	@Column(name = "tipo_emisor", nullable = false)
	public byte getTipoEmisor() {
		return this.tipoEmisor;
	}

	public void setTipoEmisor(byte tipoEmisor) {
		this.tipoEmisor = tipoEmisor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "vista")
	public Boolean getVista() {
		return this.vista;
	}

	public void setVista(Boolean vista) {
		this.vista = vista;
	}

	@Column(name = "desplegada")
	public Boolean getDesplegada() {
		return this.desplegada;
	}

	public void setDesplegada(Boolean desplegada) {
		this.desplegada = desplegada;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "lista_mecanismo_pasivo", length = 250)
	public String getListaMecanismoPasivo() {
		return this.listaMecanismoPasivo;
	}

	public void setListaMecanismoPasivo(String listaMecanismoPasivo) {
		this.listaMecanismoPasivo = listaMecanismoPasivo;
	}

	@Column(name = "lista_mecanismo_inmediato", length = 250)
	public String getListaMecanismoInmediato() {
		return this.listaMecanismoInmediato;
	}

	public void setListaMecanismoInmediato(String listaMecanismoInmediato) {
		this.listaMecanismoInmediato = listaMecanismoInmediato;
	}

	@Column(name = "texto", length = 250)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

}