package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PAIS")
public class Pais implements java.io.Serializable {

	private long idPais;
	private String nombre;
	private boolean estatusRegistro;
	private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(
			0);
	private Set<Estado> estados = new HashSet<Estado>(0);
	private Set<Escolaridad> escolaridads = new HashSet<Escolaridad>(0);
	private Set<PersonaPais> personaPaises = new HashSet<PersonaPais>(0);

	public Pais() {
	}

	public Pais(long idPais, String nombre, boolean estatusRegistro) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.estatusRegistro = estatusRegistro;
	}

	public Pais(long idPais, String nombre, boolean estatusRegistro,
			Set<ExperienciaLaboral> experienciaLaborals, Set<Estado> estados,
			Set<Escolaridad> escolaridads, Set<PersonaPais> personaPaises) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.estatusRegistro = estatusRegistro;
		this.experienciaLaborals = experienciaLaborals;
		this.estados = estados;
		this.escolaridads = escolaridads;
		this.personaPaises = personaPaises;
	}

	@Id
	@Column(name = "ID_PAIS", unique = true, nullable = false)
	public long getIdPais() {
		return this.idPais;
	}

	public void setIdPais(long idPais) {
		this.idPais = idPais;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<ExperienciaLaboral> getExperienciaLaborals() {
		return this.experienciaLaborals;
	}

	public void setExperienciaLaborals(
			Set<ExperienciaLaboral> experienciaLaborals) {
		this.experienciaLaborals = experienciaLaborals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Escolaridad> getEscolaridads() {
		return this.escolaridads;
	}

	public void setEscolaridads(Set<Escolaridad> escolaridads) {
		this.escolaridads = escolaridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<PersonaPais> getPersonaPaises() {
		return this.personaPaises;
	}

	public void setPersonaPaises(Set<PersonaPais> personaPaises) {
		this.personaPaises = personaPaises;
	}

}
