package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import net.tce.util.Constante;

/**
 * PerfilPosicion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PERFIL_POSICION", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_perfil", "id_posicion" }))
public class PerfilPosicion implements java.io.Serializable {

	private long idPerfilPosicion;
	private Perfil perfil;
	private Posicion posicion;
	private BigDecimal ponderacion;
	private Set<BitacoraPosicion> bitacoraPosicions = new HashSet<BitacoraPosicion>(
			0);
	private Set<PosibleCandidato> posibleCandidatos = new HashSet<PosibleCandidato>(
			0);
	private Set<ModeloRscPos> modeloRscPoss = new HashSet<ModeloRscPos>(
			0);

	public PerfilPosicion() {
	}

	public PerfilPosicion(long idPerfilPosicion, Perfil perfil,
			Posicion posicion, BigDecimal ponderacion) {
		this.idPerfilPosicion = idPerfilPosicion;
		this.perfil = perfil;
		this.posicion = posicion;
		this.ponderacion = ponderacion;
	}

	public PerfilPosicion(long idPerfilPosicion, Perfil perfil,
			Posicion posicion, BigDecimal ponderacion,
			Set<BitacoraPosicion> bitacoraPosicions,
			Set<PosibleCandidato> posibleCandidatos,
			Set<ModeloRscPos> modeloRscPoss) {
		this.idPerfilPosicion = idPerfilPosicion;
		this.perfil = perfil;
		this.posicion = posicion;
		this.ponderacion = ponderacion;
		this.bitacoraPosicions = bitacoraPosicions;
		this.posibleCandidatos = posibleCandidatos;
		this.modeloRscPoss = modeloRscPoss;
	}

	@Id
	@SequenceGenerator(name="seq_Perfil_Posicion", sequenceName=Constante.SECUENCIA_BD_PERFIL_POSICION, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Perfil_Posicion")
	@Column(name = "ID_PERFIL_POSICION", unique = true, nullable = false)
	public long getIdPerfilPosicion() {
		return this.idPerfilPosicion;
	}

	public void setIdPerfilPosicion(long idPerfilPosicion) {
		this.idPerfilPosicion = idPerfilPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSICION", nullable = false)
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	@Column(name = "PONDERACION", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(BigDecimal ponderacion) {
		this.ponderacion = ponderacion;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilPosicion")
	public Set<BitacoraPosicion> getBitacoraPosicions() {
		return this.bitacoraPosicions;
	}

	public void setBitacoraPosicions(Set<BitacoraPosicion> bitacoraPosicions) {
		this.bitacoraPosicions = bitacoraPosicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilPosicion")
	public Set<ModeloRscPos> getmodeloRscPoss() {
		return this.modeloRscPoss;
	}

	public void setmodeloRscPoss(Set<ModeloRscPos> modeloRscPoss) {
		this.modeloRscPoss = modeloRscPoss;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilPosicion")
	public Set<PosibleCandidato> getPosibleCandidatos() {
		return this.posibleCandidatos;
	}

	public void setPosibleCandidatos(Set<PosibleCandidato> posibleCandidatos) {
		this.posibleCandidatos = posibleCandidatos;
	}

}
