package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import net.tce.util.Constante;

/**
 * Perfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PERFIL")
public class Perfil implements java.io.Serializable {

	private long idPerfil;
	private Empresa empresa;
	private TipoPerfil tipoPerfil;
	private EstatusPerfil estatusPerfil;
	private String nombre;
	private String descripcion;
	private Boolean clasificado;
	private Set<CompetenciaPerfil> competenciaPerfils = new HashSet<CompetenciaPerfil>(
			0);
	private Set<PerfilPosicion> perfilPosicions = new HashSet<PerfilPosicion>(0);
	private Set<EmpresaPerfil> empresaPerfils = new HashSet<EmpresaPerfil>(0);
	private Set<PersonaPerfil> personaPerfils = new HashSet<PersonaPerfil>(0);
	private Set<DocumentoClasificacion> documentoClasificacions = new HashSet<DocumentoClasificacion>(
			0);
	private Set<PerfilTextoNgram> perfilTextoNgrams = new HashSet<PerfilTextoNgram>(
			0);
	private Set<PoliticaValor> politicaValors = new HashSet<PoliticaValor>(0);
	private Set<AreaPerfil> areaPerfils = new HashSet<AreaPerfil>(0);
	

	public Perfil() {
	}

	public Perfil(long idPerfil, TipoPerfil tipoPerfil,
			EstatusPerfil estatusPerfil) {
		this.idPerfil = idPerfil;
		this.tipoPerfil = tipoPerfil;
		this.estatusPerfil = estatusPerfil;
	}

	public Perfil(long idPerfil, Empresa empresa, TipoPerfil tipoPerfil,
			EstatusPerfil estatusPerfil, 
			String nombre, String descripcion, Boolean clasificado,
			Set<PerfilPosicion> perfilPosicions,
			Set<DocumentoClasificacion> documentoClasificacions,
			Set<CompetenciaPerfil> competenciaPerfils,
			Set<PersonaPerfil> personaPerfils, Set<AreaPerfil> areaPerfils,
			Set<PoliticaValor> politicaValors,
			Set<PerfilTextoNgram> perfilTextoNgrams,
			Set<EmpresaPerfil> empresaPerfils) {
		this.idPerfil = idPerfil;
		this.empresa = empresa;
		this.tipoPerfil = tipoPerfil;
		this.estatusPerfil = estatusPerfil;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clasificado = clasificado;
		this.perfilPosicions = perfilPosicions;
		this.documentoClasificacions = documentoClasificacions;
		this.competenciaPerfils = competenciaPerfils;
		this.personaPerfils = personaPerfils;
		this.areaPerfils = areaPerfils;
		this.politicaValors = politicaValors;
		this.perfilTextoNgrams = perfilTextoNgrams;
		this.empresaPerfils = empresaPerfils;
	}

	@Id
	@SequenceGenerator(name="seq_Perfil", sequenceName=Constante.SECUENCIA_BD_PERFIL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Perfil")
	@Column(name = "ID_PERFIL", unique = true, nullable = false)
	public long getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(long idPerfil) {
		this.idPerfil = idPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_PERFIL", nullable = false)
	public TipoPerfil getTipoPerfil() {
		return this.tipoPerfil;
	}

	public void setTipoPerfil(TipoPerfil tipoPerfil) {
		this.tipoPerfil = tipoPerfil;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTATUS_PERFIL", nullable = false)
	public EstatusPerfil getEstatusPerfil() {
		return this.estatusPerfil;
	}

	public void setEstatusPerfil(EstatusPerfil estatusPerfil) {
		this.estatusPerfil = estatusPerfil;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 1500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

	@Column(name = "CLASIFICADO")
	public Boolean getClasificado() {
		return this.clasificado;
	}

	public void setClasificado(Boolean clasificado) {
		this.clasificado = clasificado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<CompetenciaPerfil> getCompetenciaPerfils() {
		return this.competenciaPerfils;
	}

	public void setCompetenciaPerfils(Set<CompetenciaPerfil> competenciaPerfils) {
		this.competenciaPerfils = competenciaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilPosicion> getPerfilPosicions() {
		return this.perfilPosicions;
	}

	public void setPerfilPosicions(Set<PerfilPosicion> perfilPosicions) {
		this.perfilPosicions = perfilPosicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<EmpresaPerfil> getEmpresaPerfils() {
		return this.empresaPerfils;
	}

	public void setEmpresaPerfils(Set<EmpresaPerfil> empresaPerfils) {
		this.empresaPerfils = empresaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PersonaPerfil> getPersonaPerfils() {
		return this.personaPerfils;
	}

	public void setPersonaPerfils(Set<PersonaPerfil> personaPerfils) {
		this.personaPerfils = personaPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<DocumentoClasificacion> getDocumentoClasificacions() {
		return this.documentoClasificacions;
	}

	public void setDocumentoClasificacions(
			Set<DocumentoClasificacion> documentoClasificacions) {
		this.documentoClasificacions = documentoClasificacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	@Cascade({CascadeType.DELETE})
	public Set<PerfilTextoNgram> getPerfilTextoNgrams() {
		return this.perfilTextoNgrams;
	}

	public void setPerfilTextoNgrams(Set<PerfilTextoNgram> perfilTextoNgrams) {
		this.perfilTextoNgrams = perfilTextoNgrams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	@Cascade({CascadeType.DELETE})
	public Set<PoliticaValor> getPoliticaValors() {
		return this.politicaValors;
	}

	public void setPoliticaValors(Set<PoliticaValor> politicaValors) {
		this.politicaValors = politicaValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<AreaPerfil> getAreaPerfils() {
		return this.areaPerfils;
	}

	public void setAreaPerfils(Set<AreaPerfil> areaPerfils) {
		this.areaPerfils = areaPerfils;
	}

	
}
