package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * PerfilTextoNgram generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PERFIL_TEXTO_NGRAM")
@DynamicUpdate
public class PerfilTextoNgram implements java.io.Serializable {

	private long idPerfilTextoNgram;
	private Perfil perfil;
	private String texto;
	private Short ponderacion;
	private String textoFiltrado;

	public PerfilTextoNgram() {
	}

	public PerfilTextoNgram(long idPerfilTextoNgram) {
		this.idPerfilTextoNgram = idPerfilTextoNgram;
	}

	public PerfilTextoNgram(long idPerfilTextoNgram, Perfil perfil,
			String texto, Short ponderacion, String textoFiltrado) {
		this.idPerfilTextoNgram = idPerfilTextoNgram;
		this.perfil = perfil;
		this.texto = texto;
		this.ponderacion = ponderacion;
		this.textoFiltrado = textoFiltrado;
	}

	@Id
	@SequenceGenerator(name="seq_Perfil_Texto_Ngram", sequenceName=Constante.SECUENCIA_BD_PERFIL_TEXTO_NGRAM, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Perfil_Texto_Ngram")
	@Column(name = "ID_PERFIL_TEXTO_NGRAM", unique = true, nullable = false)
	public long getIdPerfilTextoNgram() {
		return this.idPerfilTextoNgram;
	}

	public void setIdPerfilTextoNgram(long idPerfilTextoNgram) {
		this.idPerfilTextoNgram = idPerfilTextoNgram;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "TEXTO", length = 2500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "PONDERACION")
	public Short getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Short ponderacion) {
		this.ponderacion = ponderacion;
	}

	@Column(name = "TEXTO_FILTRADO", length = 2500)
	public String getTextoFiltrado() {
		return this.textoFiltrado;
	}

	public void setTextoFiltrado(String textoFiltrado) {
		this.textoFiltrado = textoFiltrado;
	}
}
