package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PeriodoEstadoCivil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PERIODO_ESTADO_CIVIL")
public class PeriodoEstadoCivil implements java.io.Serializable {

	private long idPeriodoEstadoCivil;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public PeriodoEstadoCivil() {
	}

	public PeriodoEstadoCivil(long idPeriodoEstadoCivil, String descripcion,
			boolean estatusRegistro) {
		this.idPeriodoEstadoCivil = idPeriodoEstadoCivil;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public PeriodoEstadoCivil(long idPeriodoEstadoCivil, String descripcion,
			String significado, boolean estatusRegistro, Set<Persona> personas) {
		this.idPeriodoEstadoCivil = idPeriodoEstadoCivil;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.personas = personas;
	}

	@Id
	@Column(name = "ID_PERIODO_ESTADO_CIVIL", unique = true, nullable = false)
	public long getIdPeriodoEstadoCivil() {
		return this.idPeriodoEstadoCivil;
	}

	public void setIdPeriodoEstadoCivil(long idPeriodoEstadoCivil) {
		this.idPeriodoEstadoCivil = idPeriodoEstadoCivil;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodoEstadoCivil")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
