package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PeriodicidadBono generated by hbm2java
 */
@Entity
@Table(name = "periodicidad_bono")
public class PeriodicidadBono implements java.io.Serializable {

	private long idPeriodicidadBono;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Bono> bonos = new HashSet<Bono>(0);

	public PeriodicidadBono() {
	}

	public PeriodicidadBono(long idPeriodicidadBono) {
		this.idPeriodicidadBono = idPeriodicidadBono;
	}

	public PeriodicidadBono(long idPeriodicidadBono, String descripcion,
			Boolean estatusRegistro, Set<Bono> bonos) {
		this.idPeriodicidadBono = idPeriodicidadBono;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.bonos = bonos;
	}

	@Id
	@Column(name = "id_periodicidad_bono", unique = true, nullable = false)
	public long getIdPeriodicidadBono() {
		return this.idPeriodicidadBono;
	}

	public void setIdPeriodicidadBono(long idPeriodicidadBono) {
		this.idPeriodicidadBono = idPeriodicidadBono;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidadBono")
	public Set<Bono> getBonos() {
		return this.bonos;
	}

	public void setBonos(Set<Bono> bonos) {
		this.bonos = bonos;
	}

}
