package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PeriodicidadSueldo generated by hbm2java
 */
@Entity
@Table(name = "periodicidad_sueldo")
public class PeriodicidadSueldo implements java.io.Serializable {

	private long idPeriodicidadSueldo;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Sueldo> sueldos = new HashSet<Sueldo>(0);

	public PeriodicidadSueldo() {
	}

	public PeriodicidadSueldo(long idPeriodicidadSueldo) {
		this.idPeriodicidadSueldo = idPeriodicidadSueldo;
	}

	public PeriodicidadSueldo(long idPeriodicidadSueldo, String descripcion,
			Boolean estatusRegistro, Set<Sueldo> sueldos) {
		this.idPeriodicidadSueldo = idPeriodicidadSueldo;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.sueldos = sueldos;
	}

	@Id
	@Column(name = "id_periodicidad_sueldo", unique = true, nullable = false)
	public long getIdPeriodicidadSueldo() {
		return this.idPeriodicidadSueldo;
	}

	public void setIdPeriodicidadSueldo(long idPeriodicidadSueldo) {
		this.idPeriodicidadSueldo = idPeriodicidadSueldo;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidadSueldo")
	public Set<Sueldo> getSueldos() {
		return this.sueldos;
	}

	public void setSueldos(Set<Sueldo> sueldos) {
		this.sueldos = sueldos;
	}

}
