package net.tce.model;
// Generated Nov 25, 2019 12:27:10 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso")
public class Permiso implements java.io.Serializable {

	private long idPermiso;
	private TipoPermiso tipoPermiso;
	private Permiso permiso;
	private String contexto;
	private String valor;
	private String descripcion;
	private Set<RolTareaPermiso> rolTareaPermisos = new HashSet<RolTareaPermiso>(0);
	private Set<Permiso> permisos = new HashSet<Permiso>(0);

	public Permiso() {
	}

	public Permiso(long idPermiso) {
		this.idPermiso = idPermiso;
	}

	public Permiso(long idPermiso, TipoPermiso tipoPermiso, Permiso permiso, String contexto, String valor,
			String descripcion, Set<RolTareaPermiso> rolTareaPermisos, Set<Permiso> permisos) {
		this.idPermiso = idPermiso;
		this.tipoPermiso = tipoPermiso;
		this.permiso = permiso;
		this.contexto = contexto;
		this.valor = valor;
		this.descripcion = descripcion;
		this.rolTareaPermisos = rolTareaPermisos;
		this.permisos = permisos;
	}

	@Id
	@SequenceGenerator(name="seq_permiso", sequenceName=Constante.SECUENCIA_BD_PERMISO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_permiso")
	@Column(name = "id_permiso", unique = true, nullable = false)
	public long getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(long idPermiso) {
		this.idPermiso = idPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_permiso")
	public TipoPermiso getTipoPermiso() {
		return this.tipoPermiso;
	}

	public void setTipoPermiso(TipoPermiso tipoPermiso) {
		this.tipoPermiso = tipoPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_permiso_relacionada")
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@Column(name = "contexto", length = 50)
	public String getContexto() {
		return this.contexto;
	}

	public void setContexto(String contexto) {
		this.contexto = contexto;
	}

	@Column(name = "valor", length = 100)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<RolTareaPermiso> getRolTareaPermisos() {
		return this.rolTareaPermisos;
	}

	public void setRolTareaPermisos(Set<RolTareaPermiso> rolTareaPermisos) {
		this.rolTareaPermisos = rolTareaPermisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

}
