package net.tce.model;

// Generated Jan 19, 2017 6:31:23 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * PersonaIdioma generated by hbm2java
 */
@Entity
@Table(name = "persona_idioma")
public class PersonaIdioma implements java.io.Serializable {

	private long idPersonaIdioma;
	private Persona persona;
	private Idioma idioma;
	private Dominio dominio;

	public PersonaIdioma() {
	}

	public PersonaIdioma(long idPersonaIdioma, Persona persona, Idioma idioma,
			Dominio dominio) {
		this.idPersonaIdioma = idPersonaIdioma;
		this.persona = persona;
		this.idioma = idioma;
		this.dominio = dominio;
	}

	@Id
	@Column(name = "id_persona_idioma", unique = true, nullable = false)
	@SequenceGenerator(name="seq_persona_idioma", sequenceName=Constante.SECUENCIA_BD_PERSONAIDIOMA, initialValue=1, allocationSize=1)	
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_persona_idioma")	
	public long getIdPersonaIdioma() {
		return this.idPersonaIdioma;
	}

	public void setIdPersonaIdioma(long idPersonaIdioma) {
		this.idPersonaIdioma = idPersonaIdioma;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_idioma", nullable = false)
	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dominio", nullable = false)
	public Dominio getDominio() {
		return this.dominio;
	}

	public void setDominio(Dominio dominio) {
		this.dominio = dominio;
	}

}
