package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * PersonaPais generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PERSONA_PAIS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_persona", "id_pais" }))
@DynamicUpdate
public class PersonaPais implements java.io.Serializable {

	private long idPersonaPais;
	private Pais pais;
	private Persona persona;

	public PersonaPais() {
	}

	public PersonaPais(long idPersonaPais, Pais pais, Persona persona) {
		this.idPersonaPais = idPersonaPais;
		this.pais = pais;
		this.persona = persona;
	}

	@Id
	@SequenceGenerator(name="seq_personaPais", sequenceName=Constante.SECUENCIA_BD_PERSONA_PAIS, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_personaPais")
	@Column(name = "ID_PERSONA_PAIS", unique = true, nullable = false)
	public long getIdPersonaPais() {
		return this.idPersonaPais;
	}

	public void setIdPersonaPais(long idPersonaPais) {
		this.idPersonaPais = idPersonaPais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PAIS", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
