package net.tce.model;

// Generated Jan 31, 2017 2:35:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * PoliticaMValor generated by hbm2java
 */
@Entity
@Table(name = "politica_m_valor")
public class PoliticaMValor implements java.io.Serializable {

	private long idPoliticaMValor;
	private TipoGenero tipoGenero;
	private TipoDispViajar tipoDispViajar;
	private PoliticaValor politicaValor;
	private GradoAcademico gradoAcademico;
	private EstadoCivil estadoCivil;
	private Idioma idioma;
	private EstatusEscolar estatusEscolar;
	private Dominio dominio;
	private Short ponderacion;
	private String descripcion;

	public PoliticaMValor() {
	}

	public PoliticaMValor(long idPoliticaMValor, PoliticaValor politicaValor) {
		this.idPoliticaMValor = idPoliticaMValor;
		this.politicaValor = politicaValor;
	}

	public PoliticaMValor(long idPoliticaMValor, TipoGenero tipoGenero,
			TipoDispViajar tipoDispViajar, PoliticaValor politicaValor,
			GradoAcademico gradoAcademico, EstadoCivil estadoCivil,
			Idioma idioma, EstatusEscolar estatusEscolar, Dominio dominio,
			Short ponderacion, String descripcion) {
		this.idPoliticaMValor = idPoliticaMValor;
		this.tipoGenero = tipoGenero;
		this.tipoDispViajar = tipoDispViajar;
		this.politicaValor = politicaValor;
		this.gradoAcademico = gradoAcademico;
		this.estadoCivil = estadoCivil;
		this.idioma = idioma;
		this.estatusEscolar = estatusEscolar;
		this.dominio = dominio;
		this.ponderacion = ponderacion;
		this.descripcion = descripcion;
	}

	@Id
	@SequenceGenerator(name="seq_Politica_M_Valor", sequenceName=Constante.SECUENCIA_BD_POLITICA_MVALOR, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Politica_M_Valor")
	@Column(name = "id_politica_m_valor", unique = true, nullable = false)
	public long getIdPoliticaMValor() {
		return this.idPoliticaMValor;
	}

	public void setIdPoliticaMValor(long idPoliticaMValor) {
		this.idPoliticaMValor = idPoliticaMValor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_genero")
	public TipoGenero getTipoGenero() {
		return this.tipoGenero;
	}

	public void setTipoGenero(TipoGenero tipoGenero) {
		this.tipoGenero = tipoGenero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_disp_viajar")
	public TipoDispViajar getTipoDispViajar() {
		return this.tipoDispViajar;
	}

	public void setTipoDispViajar(TipoDispViajar tipoDispViajar) {
		this.tipoDispViajar = tipoDispViajar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_politica_valor", nullable = false)
	public PoliticaValor getPoliticaValor() {
		return this.politicaValor;
	}

	public void setPoliticaValor(PoliticaValor politicaValor) {
		this.politicaValor = politicaValor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_academico")
	public GradoAcademico getGradoAcademico() {
		return this.gradoAcademico;
	}

	public void setGradoAcademico(GradoAcademico gradoAcademico) {
		this.gradoAcademico = gradoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_civil")
	public EstadoCivil getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(EstadoCivil estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_idioma")
	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_escolar")
	public EstatusEscolar getEstatusEscolar() {
		return this.estatusEscolar;
	}

	public void setEstatusEscolar(EstatusEscolar estatusEscolar) {
		this.estatusEscolar = estatusEscolar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dominio")
	public Dominio getDominio() {
		return this.dominio;
	}

	public void setDominio(Dominio dominio) {
		this.dominio = dominio;
	}

	@Column(name = "ponderacion")
	public Short getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Short ponderacion) {
		this.ponderacion = ponderacion;
	}
	
	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
