package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import net.tce.util.Constante;

/**
 * PoliticaValor generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "POLITICA_VALOR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_empresa", "id_perfil", "id_posicion", "id_concepto", "id_politica" }))
public class PoliticaValor implements java.io.Serializable {

	private long idPoliticaValor;
	private Seccion seccion;
	private Politica politica;
	private Empresa empresa;
	private Perfil perfil;
	private Concepto concepto;
	private Area area;
	private Posicion posicion;
	private String valor;
	private String valorMinRango1;
	private String valorMaxRango1;
	private Short ponderacionRango1;
	private String valorMinRango2;
	private String valorMaxRango2;
	private Short ponderacionRango2;
	private String valorMinRango3;
	private String valorMaxRango3;
	private Short ponderacionRango3;
	private Integer orden;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private BigDecimal ponderacion;
	
	
	private Set<PoliticaMValor> politicaMValors = new HashSet<PoliticaMValor>(0);

	public PoliticaValor() {
	}

	public PoliticaValor(long idPoliticaValor, Politica politica,
			Date fechaCreacion) {
		this.idPoliticaValor = idPoliticaValor;
		this.politica = politica;
		this.fechaCreacion = fechaCreacion;
	}

	public PoliticaValor(long idPoliticaValor, Seccion seccion,
			Politica politica, Empresa empresa, Perfil perfil,
			Concepto concepto, Area area, Posicion posicion, String valor,
			String valorMinRango1, String valorMaxRango1,
			Short ponderacionRango1, String valorMinRango2,
			String valorMaxRango2, Short ponderacionRango2,
			String valorMinRango3, String valorMaxRango3,
			Short ponderacionRango3, Integer orden, Date fechaCreacion,
			Date fechaModificacion, BigDecimal ponderacion,
			Set<PoliticaMValor> politicaMValors) {
		this.idPoliticaValor = idPoliticaValor;
		this.seccion = seccion;
		this.politica = politica;
		this.empresa = empresa;
		this.perfil = perfil;
		this.concepto = concepto;
		this.area = area;
		this.posicion = posicion;
		this.valor = valor;
		this.valorMinRango1 = valorMinRango1;
		this.valorMaxRango1 = valorMaxRango1;
		this.ponderacionRango1 = ponderacionRango1;
		this.valorMinRango2 = valorMinRango2;
		this.valorMaxRango2 = valorMaxRango2;
		this.ponderacionRango2 = ponderacionRango2;
		this.valorMinRango3 = valorMinRango3;
		this.valorMaxRango3 = valorMaxRango3;
		this.ponderacionRango3 = ponderacionRango3;
		this.orden = orden;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ponderacion = ponderacion;
	}

	@Id
	@SequenceGenerator(name="seq_Politica_Valor", sequenceName=Constante.SECUENCIA_BD_POLITICA_VALOR, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_Politica_Valor")
	@Column(name = "ID_POLITICA_VALOR", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdPoliticaValor() {
		return this.idPoliticaValor;
	}

	public void setIdPoliticaValor(long idPoliticaValor) {
		this.idPoliticaValor = idPoliticaValor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SECCION")
	public Seccion getSeccion() {
		return this.seccion;
	}

	public void setSeccion(Seccion seccion) {
		this.seccion = seccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POLITICA", nullable = false)
	public Politica getPolitica() {
		return this.politica;
	}

	public void setPolitica(Politica politica) {
		this.politica = politica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERFIL")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CONCEPTO")
	public Concepto getConcepto() {
		return this.concepto;
	}

	public void setConcepto(Concepto concepto) {
		this.concepto = concepto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSICION")
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	@Column(name = "VALOR", length = 300)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "VALOR_MIN_RANGO1", length = 300)
	public String getValorMinRango1() {
		return this.valorMinRango1;
	}

	public void setValorMinRango1(String valorMinRango1) {
		this.valorMinRango1 = valorMinRango1;
	}

	@Column(name = "VALOR_MAX_RANGO1", length = 300)
	public String getValorMaxRango1() {
		return this.valorMaxRango1;
	}

	public void setValorMaxRango1(String valorMaxRango1) {
		this.valorMaxRango1 = valorMaxRango1;
	}

	@Column(name = "PONDERACION_RANGO1")
	public Short getPonderacionRango1() {
		return this.ponderacionRango1;
	}

	public void setPonderacionRango1(Short ponderacionRango1) {
		this.ponderacionRango1 = ponderacionRango1;
	}

	@Column(name = "VALOR_MIN_RANGO2", length = 300)
	public String getValorMinRango2() {
		return this.valorMinRango2;
	}

	public void setValorMinRango2(String valorMinRango2) {
		this.valorMinRango2 = valorMinRango2;
	}

	@Column(name = "VALOR_MAX_RANGO2", length = 300)
	public String getValorMaxRango2() {
		return this.valorMaxRango2;
	}

	public void setValorMaxRango2(String valorMaxRango2) {
		this.valorMaxRango2 = valorMaxRango2;
	}

	@Column(name = "PONDERACION_RANGO2")
	public Short getPonderacionRango2() {
		return this.ponderacionRango2;
	}

	public void setPonderacionRango2(Short ponderacionRango2) {
		this.ponderacionRango2 = ponderacionRango2;
	}

	@Column(name = "VALOR_MIN_RANGO3", length = 300)
	public String getValorMinRango3() {
		return this.valorMinRango3;
	}

	public void setValorMinRango3(String valorMinRango3) {
		this.valorMinRango3 = valorMinRango3;
	}

	@Column(name = "VALOR_MAX_RANGO3", length = 300)
	public String getValorMaxRango3() {
		return this.valorMaxRango3;
	}

	public void setValorMaxRango3(String valorMaxRango3) {
		this.valorMaxRango3 = valorMaxRango3;
	}

	@Column(name = "PONDERACION_RANGO3")
	public Short getPonderacionRango3() {
		return this.ponderacionRango3;
	}

	public void setPonderacionRango3(Short ponderacionRango3) {
		this.ponderacionRango3 = ponderacionRango3;
	}

	@Column(name = "ORDEN")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_CREACION", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_MODIFICACION", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "PONDERACION", precision = 131089, scale = 0)
	public BigDecimal getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(BigDecimal ponderacion) {
		this.ponderacion = ponderacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "politicaValor")
	@Cascade({CascadeType.DELETE})
	public Set<PoliticaMValor> getPoliticaMValors() {
		return this.politicaMValors;
	}

	public void setPoliticaMValors(Set<PoliticaMValor> politicaMValors) {
		this.politicaMValors = politicaMValors;
	}

}
