package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Politica generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "POLITICA", uniqueConstraints = @UniqueConstraint(columnNames = "clave_politica"))
public class Politica implements java.io.Serializable {

	private long idPolitica;
	private PropositoPolitica propositoPolitica;
	private String tipoValor;
	private String clavePolitica;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<BitacoraPoliticaValor> bitacoraPoliticaValors = new HashSet<BitacoraPoliticaValor>(
			0);
	private Set<PoliticaValor> politicaValors = new HashSet<PoliticaValor>(0);

	public Politica() {
	}

	public Politica(long idPolitica, PropositoPolitica propositoPolitica,
			String tipoValor, String clavePolitica, String descripcion) {
		this.idPolitica = idPolitica;
		this.propositoPolitica = propositoPolitica;
		this.tipoValor = tipoValor;
		this.clavePolitica = clavePolitica;
		this.descripcion = descripcion;
	}

	public Politica(long idPolitica, PropositoPolitica propositoPolitica,
			String tipoValor, String clavePolitica, String descripcion,
			String significado, boolean estatusRegistro,
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors,
			Set<PoliticaValor> politicaValors) {
		this.idPolitica = idPolitica;
		this.propositoPolitica = propositoPolitica;
		this.tipoValor = tipoValor;
		this.clavePolitica = clavePolitica;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
		this.politicaValors = politicaValors;
	}

	@Id
	@Column(name = "id_politica", unique = true, nullable = false)
	public long getIdPolitica() {
		return this.idPolitica;
	}

	public void setIdPolitica(long idPolitica) {
		this.idPolitica = idPolitica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proposito_politica", nullable = false)
	public PropositoPolitica getPropositoPolitica() {
		return this.propositoPolitica;
	}

	public void setPropositoPolitica(PropositoPolitica propositoPolitica) {
		this.propositoPolitica = propositoPolitica;
	}

	@Column(name = "tipo_valor", nullable = false, length = 1)
	public String getTipoValor() {
		return this.tipoValor;
	}

	public void setTipoValor(String tipoValor) {
		this.tipoValor = tipoValor;
	}

	@Column(name = "clave_politica", unique = true, nullable = false, length = 50)
	public String getClavePolitica() {
		return this.clavePolitica;
	}

	public void setClavePolitica(String clavePolitica) {
		this.clavePolitica = clavePolitica;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "politica")
	public Set<BitacoraPoliticaValor> getBitacoraPoliticaValors() {
		return this.bitacoraPoliticaValors;
	}

	public void setBitacoraPoliticaValors(
			Set<BitacoraPoliticaValor> bitacoraPoliticaValors) {
		this.bitacoraPoliticaValors = bitacoraPoliticaValors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "politica")
	public Set<PoliticaValor> getPoliticaValors() {
		return this.politicaValors;
	}

	public void setPoliticaValors(Set<PoliticaValor> politicaValors) {
		this.politicaValors = politicaValors;
	}
}
