package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PosicionFiltro generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "POSICION_FILTRO")
public class PosicionFiltro implements java.io.Serializable {

	private long idPosicionFiltro;
	private Filtro filtro;
	private Posicion posicion;

	public PosicionFiltro() {
	}

	public PosicionFiltro(long idPosicionFiltro, Filtro filtro,
			Posicion posicion) {
		this.idPosicionFiltro = idPosicionFiltro;
		this.filtro = filtro;
		this.posicion = posicion;
	}

	@Id
	@Column(name = "ID_POSICION_FILTRO", unique = true, nullable = false)
	public long getIdPosicionFiltro() {
		return this.idPosicionFiltro;
	}

	public void setIdPosicionFiltro(long idPosicionFiltro) {
		this.idPosicionFiltro = idPosicionFiltro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FILTRO", nullable = false)
	public Filtro getFiltro() {
		return this.filtro;
	}

	public void setFiltro(Filtro filtro) {
		this.filtro = filtro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSICION", nullable = false)
	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

}
