package net.tce.model;

// Generated Dec 21, 2017 7:05:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * PosibleCandidato generated by hbm2java
 */
@Entity
@Table(name = "posible_candidato")
@DynamicUpdate
public class PosibleCandidato implements java.io.Serializable {

	private long idPosibleCandidato;
	private TipoPosibleCandidato tipoPosibleCandidato;
	private EstatusOperativo estatusOperativo;
	private RelacionEmpresaPersona relacionEmpresaPersona;
	private PerfilPosicion perfilPosicion;
	private String comentario;
	private boolean confirmado;
	private String tokenAdd;
	private Set<TrackingPostulante> trackingPostulantes = new HashSet<TrackingPostulante>(
			0);

	public PosibleCandidato() {
	}

	public PosibleCandidato(long idPosibleCandidato,
			RelacionEmpresaPersona relacionEmpresaPersona,
			PerfilPosicion perfilPosicion, boolean confirmado) {
		this.idPosibleCandidato = idPosibleCandidato;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.perfilPosicion = perfilPosicion;
		this.confirmado = confirmado;
	}

	public PosibleCandidato(long idPosibleCandidato,
			TipoPosibleCandidato tipoPosibleCandidato,
			EstatusOperativo estatusOperativo,
			RelacionEmpresaPersona relacionEmpresaPersona,
			PerfilPosicion perfilPosicion, String comentario,
			boolean confirmado, String tokenAdd,
			Set<TrackingPostulante> trackingPostulantes) {
		this.idPosibleCandidato = idPosibleCandidato;
		this.tipoPosibleCandidato = tipoPosibleCandidato;
		this.estatusOperativo = estatusOperativo;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.perfilPosicion = perfilPosicion;
		this.comentario = comentario;
		this.confirmado = confirmado;
		this.tokenAdd = tokenAdd;
		this.trackingPostulantes = trackingPostulantes;
	}
	
	@Id
	@SequenceGenerator(name="seq_posible_candidato", sequenceName=Constante.SECUENCIA_BD_POSIBLE_CANDIDATO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_posible_candidato")
	@Column(name = "id_posible_candidato", unique = true, nullable = false)
	public long getIdPosibleCandidato() {
		return this.idPosibleCandidato;
	}

	public void setIdPosibleCandidato(long idPosibleCandidato) {
		this.idPosibleCandidato = idPosibleCandidato;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_posible_candidato")
	public TipoPosibleCandidato getTipoPosibleCandidato() {
		return this.tipoPosibleCandidato;
	}

	public void setTipoPosibleCandidato(
			TipoPosibleCandidato tipoPosibleCandidato) {
		this.tipoPosibleCandidato = tipoPosibleCandidato;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_operativo")
	public EstatusOperativo getEstatusOperativo() {
		return this.estatusOperativo;
	}

	public void setEstatusOperativo(EstatusOperativo estatusOperativo) {
		this.estatusOperativo = estatusOperativo;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_relacion_empresa_persona", nullable = false)
	public RelacionEmpresaPersona getRelacionEmpresaPersona() {
		return this.relacionEmpresaPersona;
	}

	public void setRelacionEmpresaPersona(
			RelacionEmpresaPersona relacionEmpresaPersona) {
		this.relacionEmpresaPersona = relacionEmpresaPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil_posicion", nullable = false)
	public PerfilPosicion getPerfilPosicion() {
		return this.perfilPosicion;
	}

	public void setPerfilPosicion(PerfilPosicion perfilPosicion) {
		this.perfilPosicion = perfilPosicion;
	}
	
	
	@Column(name = "comentario", length = 1500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}
	
	@Column(name = "confirmado", nullable = false)
	public boolean isConfirmado() {
		return this.confirmado;
	}

	public void setConfirmado(boolean confirmado) {
		this.confirmado = confirmado;
	}
	
	@Column(name = "token_add", length = 100)
	public String getTokenAdd() {
		return this.tokenAdd;
	}

	public void setTokenAdd(String tokenAdd) {
		this.tokenAdd = tokenAdd;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "posibleCandidato")
	public Set<TrackingPostulante> getTrackingPostulantes() {
		return this.trackingPostulantes;
	}

	public void setTrackingPostulantes(
			Set<TrackingPostulante> trackingPostulantes) {
		this.trackingPostulantes = trackingPostulantes;
	}

}
