package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Preferencia generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PREFERENCIA")
public class Preferencia implements java.io.Serializable {

	private long idPreferencia;
	private AreaInteres areaInteres;
	private Persona persona;
	private int prioridad;

	public Preferencia() {
	}

	public Preferencia(long idPreferencia, AreaInteres areaInteres,
			Persona persona, int prioridad) {
		this.idPreferencia = idPreferencia;
		this.areaInteres = areaInteres;
		this.persona = persona;
		this.prioridad = prioridad;
	}

	@Id
	@Column(name = "ID_PREFERENCIA", unique = true, nullable = false)
	public long getIdPreferencia() {
		return this.idPreferencia;
	}

	public void setIdPreferencia(long idPreferencia) {
		this.idPreferencia = idPreferencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AREA_INTERES", nullable = false)
	public AreaInteres getAreaInteres() {
		return this.areaInteres;
	}

	public void setAreaInteres(AreaInteres areaInteres) {
		this.areaInteres = areaInteres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "PRIORIDAD", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

}
