package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Premio generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "PREMIO")
public class Premio implements java.io.Serializable {

	private long idPremio;
	private Empresa empresa;
	private Persona persona;
	private String texto;
	private String institucion;

	public Premio() {
	}

	public Premio(long idPremio) {
		this.idPremio = idPremio;
	}

	public Premio(long idPremio, Empresa empresa, Persona persona,
			String texto, String institucion) {
		this.idPremio = idPremio;
		this.empresa = empresa;
		this.persona = persona;
		this.texto = texto;
		this.institucion = institucion;
	}

	@Id
	@Column(name = "ID_PREMIO", unique = true, nullable = false)
	public long getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(long idPremio) {
		this.idPremio = idPremio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "TEXTO", length = 2500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "INSTITUCION", length = 100)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}


}
