package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reactivo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "REACTIVO")
public class Reactivo implements java.io.Serializable {

	private long idReactivo;
	private Competencia competencia;
	private TipoReactivo tipoReactivo;
	private Integer escala;
	private String planteamiento;
	private boolean estatusRegistro;

	public Reactivo() {
	}

	public Reactivo(long idReactivo, Competencia competencia,
			TipoReactivo tipoReactivo, boolean estatusRegistro) {
		this.idReactivo = idReactivo;
		this.competencia = competencia;
		this.tipoReactivo = tipoReactivo;
		this.estatusRegistro = estatusRegistro;
	}

	public Reactivo(long idReactivo, Competencia competencia,
			TipoReactivo tipoReactivo, Integer escala, String planteamiento,
			boolean estatusRegistro) {
		this.idReactivo = idReactivo;
		this.competencia = competencia;
		this.tipoReactivo = tipoReactivo;
		this.escala = escala;
		this.planteamiento = planteamiento;
		this.estatusRegistro = estatusRegistro;
	}

	@Id
	@Column(name = "ID_REACTIVO", unique = true, nullable = false)
	public long getIdReactivo() {
		return this.idReactivo;
	}

	public void setIdReactivo(long idReactivo) {
		this.idReactivo = idReactivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMPETENCIA", nullable = false)
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_REACTIVO", nullable = false)
	public TipoReactivo getTipoReactivo() {
		return this.tipoReactivo;
	}

	public void setTipoReactivo(TipoReactivo tipoReactivo) {
		this.tipoReactivo = tipoReactivo;
	}

	@Column(name = "ESCALA")
	public Integer getEscala() {
		return this.escala;
	}

	public void setEscala(Integer escala) {
		this.escala = escala;
	}

	@Column(name = "PLANTEAMIENTO", length = 100)
	public String getPlanteamiento() {
		return this.planteamiento;
	}

	public void setPlanteamiento(String planteamiento) {
		this.planteamiento = planteamiento;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

}
