package net.tce.model;
// Generated Aug 7, 2019 2:08:35 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.tce.util.Constante;

/**
 * Recordatorio generated by hbm2java
 */
@Entity
@Table(name = "recordatorio")
public class Recordatorio implements java.io.Serializable {

	private long idRecordatorio;
	private TrackingPostulante trackingPostulante;
	private TipoRecordatorio tipoRecordatorio;
	private TrackingMonitor trackingMonitor;
	private String descripcion;
	private short cifra;
	private boolean activo;
	private boolean seAplico;
	private Date fecha;

	public Recordatorio() {
	}

	public Recordatorio(long idRecordatorio, TipoRecordatorio tipoRecordatorio, String descripcion, short cifra,
			boolean activo, boolean seAplico, Date fecha) {
		this.idRecordatorio = idRecordatorio;
		this.tipoRecordatorio = tipoRecordatorio;
		this.descripcion = descripcion;
		this.cifra = cifra;
		this.activo = activo;
		this.seAplico = seAplico;
		this.fecha = fecha;
	}

	public Recordatorio(long idRecordatorio, TrackingPostulante trackingPostulante, TipoRecordatorio tipoRecordatorio,
			TrackingMonitor trackingMonitor, String descripcion, short cifra, boolean activo, boolean seAplico,
			Date fecha) {
		this.idRecordatorio = idRecordatorio;
		this.trackingPostulante = trackingPostulante;
		this.tipoRecordatorio = tipoRecordatorio;
		this.trackingMonitor = trackingMonitor;
		this.descripcion = descripcion;
		this.cifra = cifra;
		this.activo = activo;
		this.seAplico = seAplico;
		this.fecha = fecha;
	}


	@Id
	@SequenceGenerator(name="seq_recordatorio", sequenceName=Constante.SECUENCIA_BD_RECORDATORIO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_recordatorio")
	@Column(name = "id_recordatorio", unique = true, nullable = false)
	public long getIdRecordatorio() {
		return this.idRecordatorio;
	}

	public void setIdRecordatorio(long idRecordatorio) {
		this.idRecordatorio = idRecordatorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tracking_postulante")
	public TrackingPostulante getTrackingPostulante() {
		return this.trackingPostulante;
	}

	public void setTrackingPostulante(TrackingPostulante trackingPostulante) {
		this.trackingPostulante = trackingPostulante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_recordatorio", nullable = false)
	public TipoRecordatorio getTipoRecordatorio() {
		return this.tipoRecordatorio;
	}

	public void setTipoRecordatorio(TipoRecordatorio tipoRecordatorio) {
		this.tipoRecordatorio = tipoRecordatorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tracking_monitor")
	public TrackingMonitor getTrackingMonitor() {
		return this.trackingMonitor;
	}

	public void setTrackingMonitor(TrackingMonitor trackingMonitor) {
		this.trackingMonitor = trackingMonitor;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "cifra", nullable = false)
	public short getCifra() {
		return this.cifra;
	}

	public void setCifra(short cifra) {
		this.cifra = cifra;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "se_aplico", nullable = false)
	public boolean isSeAplico() {
		return this.seAplico;
	}

	public void setSeAplico(boolean seAplico) {
		this.seAplico = seAplico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
}
