package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Referencia generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "REFERENCIA")
@DynamicUpdate
public class Referencia implements java.io.Serializable {

	private long idReferencia;
	private Persona persona;
	private String nombre;
	private String empresa;
	private String puesto;
	private String email;
	private Boolean previaAutorizacion;
	private String telCelular;
	private String telParticular;

	public Referencia() {
	}

	public Referencia(long idReferencia, Persona persona) {
		this.idReferencia = idReferencia;
		this.persona = persona;
	}

	public Referencia(long idReferencia, Persona persona, String nombre,
			String empresa, String puesto, String email,
			Boolean previaAutorizacion, String telCelular, String telParticular) {
		this.idReferencia = idReferencia;
		this.persona = persona;
		this.nombre = nombre;
		this.empresa = empresa;
		this.puesto = puesto;
		this.email = email;
		this.previaAutorizacion = previaAutorizacion;
		this.telCelular = telCelular;
		this.telParticular = telParticular;
	}

	@Id
	@SequenceGenerator(name="seq_referencia", sequenceName=Constante.SECUENCIA_BD_REFERENCIA, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_referencia")
	@Column(name = "ID_REFERENCIA", unique = true, nullable = false)
	public long getIdReferencia() {
		return this.idReferencia;
	}

	public void setIdReferencia(long idReferencia) {
		this.idReferencia = idReferencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "empresa", length = 100)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "puesto", length = 100)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "previa_autorizacion")
	public Boolean getPreviaAutorizacion() {
		return this.previaAutorizacion;
	}

	public void setPreviaAutorizacion(Boolean previaAutorizacion) {
		this.previaAutorizacion = previaAutorizacion;
	}

	@Column(name = "tel_celular", length = 20)
	public String getTelCelular() {
		return this.telCelular;
	}

	public void setTelCelular(String telCelular) {
		this.telCelular = telCelular;
	}

	@Column(name = "tel_particular", length = 20)
	public String getTelParticular() {
		return this.telParticular;
	}

	public void setTelParticular(String telParticular) {
		this.telParticular = telParticular;
	}

	

}
