package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelacionPersona generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "RELACION_PERSONA")
public class RelacionPersona implements java.io.Serializable {

	private long idRelacionPersona;
	private TipoRelacionPersona tipoRelacionPersona;
	private Persona personaByIdPersonaRel;
	private Persona personaByIdPersona;
	private Date fechaInicio;
	private Date fechaFin;
	private Integer calificacion;
	private boolean estatusRegistro;

	public RelacionPersona() {
	}

	public RelacionPersona(long idRelacionPersona,
			TipoRelacionPersona tipoRelacionPersona,
			Persona personaByIdPersonaRel, Persona personaByIdPersona) {
		this.idRelacionPersona = idRelacionPersona;
		this.tipoRelacionPersona = tipoRelacionPersona;
		this.personaByIdPersonaRel = personaByIdPersonaRel;
		this.personaByIdPersona = personaByIdPersona;
	}

	public RelacionPersona(long idRelacionPersona,
			TipoRelacionPersona tipoRelacionPersona,
			Persona personaByIdPersonaRel, Persona personaByIdPersona,
			Date fechaInicio, Date fechaFin, Integer calificacion,
			boolean estatusRegistro) {
		this.idRelacionPersona = idRelacionPersona;
		this.tipoRelacionPersona = tipoRelacionPersona;
		this.personaByIdPersonaRel = personaByIdPersonaRel;
		this.personaByIdPersona = personaByIdPersona;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.calificacion = calificacion;
		this.estatusRegistro = estatusRegistro;
	}

	@Id
	@Column(name = "ID_RELACION_PERSONA", unique = true, nullable = false)
	public long getIdRelacionPersona() {
		return this.idRelacionPersona;
	}

	public void setIdRelacionPersona(long idRelacionPersona) {
		this.idRelacionPersona = idRelacionPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_RELACION_PERSONA", nullable = false)
	public TipoRelacionPersona getTipoRelacionPersona() {
		return this.tipoRelacionPersona;
	}

	public void setTipoRelacionPersona(TipoRelacionPersona tipoRelacionPersona) {
		this.tipoRelacionPersona = tipoRelacionPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA_REL", nullable = false)
	public Persona getPersonaByIdPersonaRel() {
		return this.personaByIdPersonaRel;
	}

	public void setPersonaByIdPersonaRel(Persona personaByIdPersonaRel) {
		this.personaByIdPersonaRel = personaByIdPersonaRel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA", nullable = false)
	public Persona getPersonaByIdPersona() {
		return this.personaByIdPersona;
	}

	public void setPersonaByIdPersona(Persona personaByIdPersona) {
		this.personaByIdPersona = personaByIdPersona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "CALIFICACION")
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

}
