package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelacionEmpresa generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "RELACION_EMPRESA")
public class RelacionEmpresa implements java.io.Serializable {

	private long idRelacionEmpresa;
	private Empresa empresaByIdEmpresa;
	private Empresa empresaByIdEmpresaRel;
	private TipoRelacionEmpresa tipoRelacionEmpresa;
	private String nombreJerarquia;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean estatusRegistro;

	public RelacionEmpresa() {
	}

	public RelacionEmpresa(long idRelacionEmpresa, Empresa empresaByIdEmpresa,
			Empresa empresaByIdEmpresaRel,
			TipoRelacionEmpresa tipoRelacionEmpresa, Date fechaInicio,
			boolean estatusRegistro) {
		this.idRelacionEmpresa = idRelacionEmpresa;
		this.empresaByIdEmpresa = empresaByIdEmpresa;
		this.empresaByIdEmpresaRel = empresaByIdEmpresaRel;
		this.tipoRelacionEmpresa = tipoRelacionEmpresa;
		this.fechaInicio = fechaInicio;
		this.estatusRegistro = estatusRegistro;
	}

	public RelacionEmpresa(long idRelacionEmpresa, Empresa empresaByIdEmpresa,
			Empresa empresaByIdEmpresaRel,
			TipoRelacionEmpresa tipoRelacionEmpresa, String nombreJerarquia,
			Date fechaInicio, Date fechaFin, boolean estatusRegistro) {
		this.idRelacionEmpresa = idRelacionEmpresa;
		this.empresaByIdEmpresa = empresaByIdEmpresa;
		this.empresaByIdEmpresaRel = empresaByIdEmpresaRel;
		this.tipoRelacionEmpresa = tipoRelacionEmpresa;
		this.nombreJerarquia = nombreJerarquia;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estatusRegistro = estatusRegistro;
	}

	@Id
	@Column(name = "ID_RELACION_EMPRESA", unique = true, nullable = false)
	public long getIdRelacionEmpresa() {
		return this.idRelacionEmpresa;
	}

	public void setIdRelacionEmpresa(long idRelacionEmpresa) {
		this.idRelacionEmpresa = idRelacionEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA", nullable = false)
	public Empresa getEmpresaByIdEmpresa() {
		return this.empresaByIdEmpresa;
	}

	public void setEmpresaByIdEmpresa(Empresa empresaByIdEmpresa) {
		this.empresaByIdEmpresa = empresaByIdEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA_REL", nullable = false)
	public Empresa getEmpresaByIdEmpresaRel() {
		return this.empresaByIdEmpresaRel;
	}

	public void setEmpresaByIdEmpresaRel(Empresa empresaByIdEmpresaRel) {
		this.empresaByIdEmpresaRel = empresaByIdEmpresaRel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_RELACION_EMPRESA", nullable = false)
	public TipoRelacionEmpresa getTipoRelacionEmpresa() {
		return this.tipoRelacionEmpresa;
	}

	public void setTipoRelacionEmpresa(TipoRelacionEmpresa tipoRelacionEmpresa) {
		this.tipoRelacionEmpresa = tipoRelacionEmpresa;
	}

	@Column(name = "NOMBRE_JERARQUIA", length = 250)
	public String getNombreJerarquia() {
		return this.nombreJerarquia;
	}

	public void setNombreJerarquia(String nombreJerarquia) {
		this.nombreJerarquia = nombreJerarquia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_INICIO", nullable = false, length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_FIN", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

}
