package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelacionPosicion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "RELACION_POSICION")
public class RelacionPosicion implements java.io.Serializable {

	private long idRelacionPosicion;
	private Posicion posicionByIdPosicionRel;
	private Posicion posicionByIdPosicion;
	private TipoRelacionPosicion tipoRelacionPosicion;
	private boolean estatusRegistro;

	public RelacionPosicion() {
	}

	public RelacionPosicion(long idRelacionPosicion, boolean estatusRegistro) {
		this.idRelacionPosicion = idRelacionPosicion;
		this.estatusRegistro = estatusRegistro;
	}

	public RelacionPosicion(long idRelacionPosicion,
			Posicion posicionByIdPosicionRel, Posicion posicionByIdPosicion,
			TipoRelacionPosicion tipoRelacionPosicion, boolean estatusRegistro) {
		this.idRelacionPosicion = idRelacionPosicion;
		this.posicionByIdPosicionRel = posicionByIdPosicionRel;
		this.posicionByIdPosicion = posicionByIdPosicion;
		this.tipoRelacionPosicion = tipoRelacionPosicion;
		this.estatusRegistro = estatusRegistro;
	}

	@Id
	@Column(name = "ID_RELACION_POSICION", unique = true, nullable = false)
	public long getIdRelacionPosicion() {
		return this.idRelacionPosicion;
	}

	public void setIdRelacionPosicion(long idRelacionPosicion) {
		this.idRelacionPosicion = idRelacionPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSICION_REL")
	public Posicion getPosicionByIdPosicionRel() {
		return this.posicionByIdPosicionRel;
	}

	public void setPosicionByIdPosicionRel(Posicion posicionByIdPosicionRel) {
		this.posicionByIdPosicionRel = posicionByIdPosicionRel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_POSICION")
	public Posicion getPosicionByIdPosicion() {
		return this.posicionByIdPosicion;
	}

	public void setPosicionByIdPosicion(Posicion posicionByIdPosicion) {
		this.posicionByIdPosicion = posicionByIdPosicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_RELACION_POSICION")
	public TipoRelacionPosicion getTipoRelacionPosicion() {
		return this.tipoRelacionPosicion;
	}

	public void setTipoRelacionPosicion(
			TipoRelacionPosicion tipoRelacionPosicion) {
		this.tipoRelacionPosicion = tipoRelacionPosicion;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

}
