package net.tce.model;
// Generated Nov 25, 2019 11:54:28 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol")
public class Rol implements java.io.Serializable {

	private long idRol;
	private String descripcion;
	private boolean rolInicial;
	private String vistaInicial;
	private Set<RelacionEmpresaPersona> relacionEmpresaPersonas = new HashSet<RelacionEmpresaPersona>(0);
	private Set<ModeloRscPos> modeloRscPoses = new HashSet<ModeloRscPos>(0);
	private Set<RolTareaPermiso> rolTareaPermisos = new HashSet<RolTareaPermiso>(0);

	public Rol() {
	}

	public Rol(long idRol, String descripcion, boolean rolInicial) {
		this.idRol = idRol;
		this.descripcion = descripcion;
		this.rolInicial = rolInicial;
	}

	public Rol(long idRol, String descripcion, boolean rolInicial, String vistaInicial,
			Set<RelacionEmpresaPersona> relacionEmpresaPersonas, Set<ModeloRscPos> modeloRscPoses,
			Set<RolTareaPermiso> rolTareaPermisos) {
		this.idRol = idRol;
		this.descripcion = descripcion;
		this.rolInicial = rolInicial;
		this.vistaInicial = vistaInicial;
		this.relacionEmpresaPersonas = relacionEmpresaPersonas;
		this.modeloRscPoses = modeloRscPoses;
		this.rolTareaPermisos = rolTareaPermisos;
	}

	@Id
	@Column(name = "id_rol", unique = true, nullable = false)
	@SequenceGenerator(name="seq_rol", sequenceName=Constante.SECUENCIA_BD_ROL, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_rol")
	public long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(long idRol) {
		this.idRol = idRol;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "rol_inicial", nullable = false)
	public boolean isRolInicial() {
		return this.rolInicial;
	}

	public void setRolInicial(boolean rolInicial) {
		this.rolInicial = rolInicial;
	}

	@Column(name = "vista_inicial", length = 250)
	public String getVistaInicial() {
		return this.vistaInicial;
	}

	public void setVistaInicial(String vistaInicial) {
		this.vistaInicial = vistaInicial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RelacionEmpresaPersona> getRelacionEmpresaPersonas() {
		return this.relacionEmpresaPersonas;
	}

	public void setRelacionEmpresaPersonas(Set<RelacionEmpresaPersona> relacionEmpresaPersonas) {
		this.relacionEmpresaPersonas = relacionEmpresaPersonas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<ModeloRscPos> getModeloRscPoses() {
		return this.modeloRscPoses;
	}

	public void setModeloRscPoses(Set<ModeloRscPos> modeloRscPoses) {
		this.modeloRscPoses = modeloRscPoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolTareaPermiso> getRolTareaPermisos() {
		return this.rolTareaPermisos;
	}

	public void setRolTareaPermisos(Set<RolTareaPermiso> rolTareaPermisos) {
		this.rolTareaPermisos = rolTareaPermisos;
	}

}
