package net.tce.model;
// Generated Nov 25, 2019 11:54:28 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

/**
 * RolTareaPermiso generated by hbm2java
 */
@Entity
@Table(name = "rol_tarea_permiso")
public class RolTareaPermiso implements java.io.Serializable {

	private long idRolTareaPermiso;
	private Rol rol;
	private Tarea tarea;
	private Permiso permiso;
	private boolean activo;

	public RolTareaPermiso() {
	}

	public RolTareaPermiso(long idRolTareaPermiso, boolean activo) {
		this.idRolTareaPermiso = idRolTareaPermiso;
		this.activo = activo;
	}

	public RolTareaPermiso(long idRolTareaPermiso, Rol rol, Tarea tarea, Permiso permiso, boolean activo) {
		this.idRolTareaPermiso = idRolTareaPermiso;
		this.rol = rol;
		this.tarea = tarea;
		this.permiso = permiso;
		this.activo = activo;
	}

	@Id
	@SequenceGenerator(name="seq_rtp", sequenceName=Constante.SECUENCIA_BD_ROL_TAREA_PERMISO, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_rtp")
	@Column(name = "id_rol_tarea_permiso", unique = true, nullable = false)
	public long getIdRolTareaPermiso() {
		return this.idRolTareaPermiso;
	}

	public void setIdRolTareaPermiso(long idRolTareaPermiso) {
		this.idRolTareaPermiso = idRolTareaPermiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarea")
	public Tarea getTarea() {
		return this.tarea;
	}

	public void setTarea(Tarea tarea) {
		this.tarea = tarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_permiso")
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
