package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seccion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "SECCION")
public class Seccion implements java.io.Serializable {

	private long idSeccion;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Concepto> conceptos = new HashSet<Concepto>(0);
	private Set<PoliticaValor> politicaValors = new HashSet<PoliticaValor>(0);

	public Seccion() {
	}

	public Seccion(long idSeccion, String descripcion, boolean estatusRegistro) {
		this.idSeccion = idSeccion;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public Seccion(long idSeccion, String descripcion, String significado,
			boolean estatusRegistro, Set<Concepto> conceptos,
			Set<PoliticaValor> politicaValors) {
		this.idSeccion = idSeccion;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.conceptos = conceptos;
		this.politicaValors = politicaValors;
	}

	@Id
	@Column(name = "ID_SECCION", unique = true, nullable = false)
	public long getIdSeccion() {
		return this.idSeccion;
	}

	public void setIdSeccion(long idSeccion) {
		this.idSeccion = idSeccion;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seccion")
	public Set<Concepto> getConceptos() {
		return this.conceptos;
	}

	public void setConceptos(Set<Concepto> conceptos) {
		this.conceptos = conceptos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seccion")
	public Set<PoliticaValor> getPoliticaValors() {
		return this.politicaValors;
	}

	public void setPoliticaValors(Set<PoliticaValor> politicaValors) {
		this.politicaValors = politicaValors;
	}

}
