package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Sueldo generated by hbm2java
 */
@Entity
@Table(name = "sueldo")
@DynamicUpdate
public class Sueldo implements java.io.Serializable {

	private long idPersona;
	private PeriodicidadSueldo periodicidadSueldo;
	private Compensacion compensacion;
	private Long cantidad;

	public Sueldo() {
	}

	public Sueldo(PeriodicidadSueldo periodicidadSueldo,
			Compensacion compensacion) {
		this.periodicidadSueldo = periodicidadSueldo;
		this.compensacion = compensacion;
	}

	public Sueldo(PeriodicidadSueldo periodicidadSueldo,
			Compensacion compensacion, Long cantidad) {
		this.periodicidadSueldo = periodicidadSueldo;
		this.compensacion = compensacion;
		this.cantidad = cantidad;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "compensacion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_persona", unique = true, nullable = false)
	public long getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(long idPersona) {
		this.idPersona = idPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodicidad_sueldo")
	public PeriodicidadSueldo getPeriodicidadSueldo() {
		return this.periodicidadSueldo;
	}

	public void setPeriodicidadSueldo(PeriodicidadSueldo periodicidadSueldo) {
		this.periodicidadSueldo = periodicidadSueldo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Compensacion getCompensacion() {
		return this.compensacion;
	}

	public void setCompensacion(Compensacion compensacion) {
		this.compensacion = compensacion;
	}

	@Column(name = "cantidad")
	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

}
