package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoEventoMecanismo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_EVENTO_MECANISMO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_mecanismo", "id_tipo_evento" }))
public class TipoEventoMecanismo implements java.io.Serializable {

	private long idTipoEventoMecanismo;
	private Mecanismo mecanismo;
	private TipoEvento tipoEvento;

	public TipoEventoMecanismo() {
	}

	public TipoEventoMecanismo(long idTipoEventoMecanismo, Mecanismo mecanismo,
			TipoEvento tipoEvento) {
		this.idTipoEventoMecanismo = idTipoEventoMecanismo;
		this.mecanismo = mecanismo;
		this.tipoEvento = tipoEvento;
	}

	@Id
	@Column(name = "ID_TIPO_EVENTO_MECANISMO", unique = true, nullable = false)
	public long getIdTipoEventoMecanismo() {
		return this.idTipoEventoMecanismo;
	}

	public void setIdTipoEventoMecanismo(long idTipoEventoMecanismo) {
		this.idTipoEventoMecanismo = idTipoEventoMecanismo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MECANISMO", nullable = false)
	public Mecanismo getMecanismo() {
		return this.mecanismo;
	}

	public void setMecanismo(Mecanismo mecanismo) {
		this.mecanismo = mecanismo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_EVENTO", nullable = false)
	public TipoEvento getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(TipoEvento tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

}
