package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAsentamiento generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_ASENTAMIENTO")
public class TipoAsentamiento implements java.io.Serializable {

	private long idTipoAsentamiento;
	private String claveTipoAsentamiento;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Asentamiento> asentamientos = new HashSet<Asentamiento>(0);

	public TipoAsentamiento() {
	}

	public TipoAsentamiento(long idTipoAsentamiento, String descripcion,
			boolean estatusRegistro) {
		this.idTipoAsentamiento = idTipoAsentamiento;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoAsentamiento(long idTipoAsentamiento,
			String claveTipoAsentamiento, String descripcion,
			String significado, boolean estatusRegistro,
			Set<Asentamiento> asentamientos) {
		this.idTipoAsentamiento = idTipoAsentamiento;
		this.claveTipoAsentamiento = claveTipoAsentamiento;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.asentamientos = asentamientos;
	}

	@Id
	@Column(name = "ID_TIPO_ASENTAMIENTO", unique = true, nullable = false)
	public long getIdTipoAsentamiento() {
		return this.idTipoAsentamiento;
	}

	public void setIdTipoAsentamiento(long idTipoAsentamiento) {
		this.idTipoAsentamiento = idTipoAsentamiento;
	}

	@Column(name = "CLAVE_TIPO_ASENTAMIENTO", length = 10)
	public String getClaveTipoAsentamiento() {
		return this.claveTipoAsentamiento;
	}

	public void setClaveTipoAsentamiento(String claveTipoAsentamiento) {
		this.claveTipoAsentamiento = claveTipoAsentamiento;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAsentamiento")
	public Set<Asentamiento> getAsentamientos() {
		return this.asentamientos;
	}

	public void setAsentamientos(Set<Asentamiento> asentamientos) {
		this.asentamientos = asentamientos;
	}

}
