package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoReactivo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_REACTIVO")
public class TipoReactivo implements java.io.Serializable {

	private long idTipoReactivo;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Reactivo> reactivos = new HashSet<Reactivo>(0);

	public TipoReactivo() {
	}

	public TipoReactivo(long idTipoReactivo, String descripcion,
			boolean estatusRegistro) {
		this.idTipoReactivo = idTipoReactivo;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoReactivo(long idTipoReactivo, String descripcion,
			String significado, boolean estatusRegistro, Set<Reactivo> reactivos) {
		this.idTipoReactivo = idTipoReactivo;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.reactivos = reactivos;
	}

	@Id
	@Column(name = "ID_TIPO_REACTIVO", unique = true, nullable = false)
	public long getIdTipoReactivo() {
		return this.idTipoReactivo;
	}

	public void setIdTipoReactivo(long idTipoReactivo) {
		this.idTipoReactivo = idTipoReactivo;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoReactivo")
	public Set<Reactivo> getReactivos() {
		return this.reactivos;
	}

	public void setReactivos(Set<Reactivo> reactivos) {
		this.reactivos = reactivos;
	}

}
