package net.tce.model;
// Generated Jan 21, 2020 11:22:18 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoModuloBitacora generated by hbm2java
 */
@Entity
@Table(name = "tipo_modulo_bitacora")
public class TipoModuloBitacora implements java.io.Serializable {

	private short idTipoModuloBitacora;
	private String nombre;
	private String descripcion;
	private Set<BitacoraTrack> bitacoraTracks = new HashSet<BitacoraTrack>(0);

	public TipoModuloBitacora() {
	}

	public TipoModuloBitacora(short idTipoModuloBitacora) {
		this.idTipoModuloBitacora = idTipoModuloBitacora;
	}

	public TipoModuloBitacora(short idTipoModuloBitacora, String nombre, String descripcion,
			Set<BitacoraTrack> bitacoraTracks) {
		this.idTipoModuloBitacora = idTipoModuloBitacora;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.bitacoraTracks = bitacoraTracks;
	}

	@Id

	@Column(name = "id_tipo_modulo_bitacora", unique = true, nullable = false)
	public short getIdTipoModuloBitacora() {
		return this.idTipoModuloBitacora;
	}

	public void setIdTipoModuloBitacora(short idTipoModuloBitacora) {
		this.idTipoModuloBitacora = idTipoModuloBitacora;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoModuloBitacora")
	public Set<BitacoraTrack> getBitacoraTracks() {
		return this.bitacoraTracks;
	}

	public void setBitacoraTracks(Set<BitacoraTrack> bitacoraTracks) {
		this.bitacoraTracks = bitacoraTracks;
	}

}
