package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContenidoArchivo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_CONTENIDO_ARCHIVO")
public class TipoContenidoArchivo implements java.io.Serializable {

	private long idTipoContenidoArchivo;
	private TipoArchivo tipoArchivo;
	private TipoContenido tipoContenido;
	private Set<Contenido> contenidos = new HashSet<Contenido>(0);

	public TipoContenidoArchivo() {
	}

	public TipoContenidoArchivo(long idTipoContenidoArchivo,
			TipoArchivo tipoArchivo, TipoContenido tipoContenido) {
		this.idTipoContenidoArchivo = idTipoContenidoArchivo;
		this.tipoArchivo = tipoArchivo;
		this.tipoContenido = tipoContenido;
	}

	public TipoContenidoArchivo(long idTipoContenidoArchivo,
			TipoArchivo tipoArchivo, TipoContenido tipoContenido,
			Set<Contenido> contenidos) {
		this.idTipoContenidoArchivo = idTipoContenidoArchivo;
		this.tipoArchivo = tipoArchivo;
		this.tipoContenido = tipoContenido;
		this.contenidos = contenidos;
	}

	@Id
	@Column(name = "ID_TIPO_CONTENIDO_ARCHIVO", unique = true, nullable = false)
	public long getIdTipoContenidoArchivo() {
		return this.idTipoContenidoArchivo;
	}

	public void setIdTipoContenidoArchivo(long idTipoContenidoArchivo) {
		this.idTipoContenidoArchivo = idTipoContenidoArchivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_ARCHIVO", nullable = false)
	public TipoArchivo getTipoArchivo() {
		return this.tipoArchivo;
	}

	public void setTipoArchivo(TipoArchivo tipoArchivo) {
		this.tipoArchivo = tipoArchivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_CONTENIDO", nullable = false)
	public TipoContenido getTipoContenido() {
		return this.tipoContenido;
	}

	public void setTipoContenido(TipoContenido tipoContenido) {
		this.tipoContenido = tipoContenido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContenidoArchivo")
	public Set<Contenido> getContenidos() {
		return this.contenidos;
	}

	public void setContenidos(Set<Contenido> contenidos) {
		this.contenidos = contenidos;
	}

}
