package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoArchivo generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_ARCHIVO")
public class TipoArchivo implements java.io.Serializable {

	private long idTipoArchivo;
	private String descripcion;
	private String significado;
	private String extension;
	private boolean estatusRegistro;
	private Set<TipoContenidoArchivo> tipoContenidoArchivos = new HashSet<TipoContenidoArchivo>(
			0);

	public TipoArchivo() {
	}

	public TipoArchivo(long idTipoArchivo, String descripcion) {
		this.idTipoArchivo = idTipoArchivo;
		this.descripcion = descripcion;
	}

	public TipoArchivo(long idTipoArchivo, String descripcion,
			String significado, String extension, boolean estatusRegistro,
			Set<TipoContenidoArchivo> tipoContenidoArchivos) {
		this.idTipoArchivo = idTipoArchivo;
		this.descripcion = descripcion;
		this.significado = significado;
		this.extension = extension;
		this.estatusRegistro = estatusRegistro;
		this.tipoContenidoArchivos = tipoContenidoArchivos;
	}

	@Id
	@Column(name = "ID_TIPO_ARCHIVO", unique = true, nullable = false)
	public long getIdTipoArchivo() {
		return this.idTipoArchivo;
	}

	public void setIdTipoArchivo(long idTipoArchivo) {
		this.idTipoArchivo = idTipoArchivo;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "EXTENSION", length = 100)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoArchivo")
	public Set<TipoContenidoArchivo> getTipoContenidoArchivos() {
		return this.tipoContenidoArchivos;
	}

	public void setTipoContenidoArchivos(
			Set<TipoContenidoArchivo> tipoContenidoArchivos) {
		this.tipoContenidoArchivos = tipoContenidoArchivos;
	}

}
