package net.tce.model;

// Generated Jul 7, 2015 1:49:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPermiso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_PERMISO")
public class TipoPermiso implements java.io.Serializable {

	private byte idTipoPermiso;
	private String descripcion;
	private String significado;
	private Boolean estatusRegistro;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);

	public TipoPermiso() {
	}

	public TipoPermiso(byte idTipoPermiso) {
		this.idTipoPermiso = idTipoPermiso;
	}

	public TipoPermiso(byte idTipoPermiso, String descripcion,
			String significado, Boolean estatusRegistro, Set<Permiso> permisos) {
		this.idTipoPermiso = idTipoPermiso;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.permisos = permisos;
	}

	@Id
	@Column(name = "ID_TIPO_PERMISO", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getIdTipoPermiso() {
		return this.idTipoPermiso;
	}

	public void setIdTipoPermiso(byte idTipoPermiso) {
		this.idTipoPermiso = idTipoPermiso;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO", precision = 1, scale = 0)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPermiso")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

}
