package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoConf generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_CONF")
public class TipoConf implements java.io.Serializable {

	private byte idTipoConf;
	private String descripcion;
	private boolean estatusRegistro;
	private Set<Conf> confs = new HashSet<Conf>(0);

	public TipoConf() {
	}

	public TipoConf(byte idTipoConf, String descripcion, boolean estatusRegistro) {
		this.idTipoConf = idTipoConf;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoConf(byte idTipoConf, String descripcion,
			boolean estatusRegistro, Set<Conf> confs) {
		this.idTipoConf = idTipoConf;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.confs = confs;
	}

	@Id
	@Column(name = "ID_TIPO_CONF", unique = true, nullable = false)
	public byte getIdTipoConf() {
		return this.idTipoConf;
	}

	public void setIdTipoConf(byte idTipoConf) {
		this.idTipoConf = idTipoConf;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConf")
	public Set<Conf> getConfs() {
		return this.confs;
	}

	public void setConfs(Set<Conf> confs) {
		this.confs = confs;
	}

}
