package net.tce.model;

// Generated Nov 9, 2015 1:59:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSuscriptor generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_SUSCRIPTOR")
public class TipoSuscriptor implements java.io.Serializable {

	private byte idTipoSuscriptor;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public TipoSuscriptor() {
	}

	public TipoSuscriptor(byte idTipoSuscriptor) {
		this.idTipoSuscriptor = idTipoSuscriptor;
	}

	public TipoSuscriptor(byte idTipoSuscriptor, String descripcion,
			Boolean estatusRegistro, Set<Empresa> empresas) {
		this.idTipoSuscriptor = idTipoSuscriptor;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.empresas = empresas;
	}

	@Id
	@Column(name = "ID_TIPO_SUSCRIPTOR", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getIdTipoSuscriptor() {
		return this.idTipoSuscriptor;
	}

	public void setIdTipoSuscriptor(byte idTipoSuscriptor) {
		this.idTipoSuscriptor = idTipoSuscriptor;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS_REGISTRO", precision = 1, scale = 0)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSuscriptor")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
