package net.tce.model;
// Generated Aug 7, 2019 2:08:35 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoRecordatorio generated by hbm2java
 */
@Entity
@Table(name = "tipo_recordatorio")
public class TipoRecordatorio implements java.io.Serializable {

	private short idTipoRecordatorio;
	private String descripcion;
	private boolean estatusRegistro;
	private Set<Recordatorio> recordatorios = new HashSet<Recordatorio>(0);

	public TipoRecordatorio() {
	}

	public TipoRecordatorio(short idTipoRecordatorio, boolean estatusRegistro) {
		this.idTipoRecordatorio = idTipoRecordatorio;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoRecordatorio(short idTipoRecordatorio, String descripcion, boolean estatusRegistro,
			Set<Recordatorio> recordatorios) {
		this.idTipoRecordatorio = idTipoRecordatorio;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.recordatorios = recordatorios;
	}

	@Id

	@Column(name = "id_tipo_recordatorio", unique = true, nullable = false)
	public short getIdTipoRecordatorio() {
		return this.idTipoRecordatorio;
	}

	public void setIdTipoRecordatorio(short idTipoRecordatorio) {
		this.idTipoRecordatorio = idTipoRecordatorio;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoRecordatorio")
	public Set<Recordatorio> getRecordatorios() {
		return this.recordatorios;
	}

	public void setRecordatorios(Set<Recordatorio> recordatorios) {
		this.recordatorios = recordatorios;
	}

}
