package net.tce.model;
// Generated Jan 23, 2020 7:01:01 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEventoBitacora generated by hbm2java
 */
@Entity
@Table(name = "tipo_evento_bitacora")
public class TipoEventoBitacora implements java.io.Serializable {

	private short idTipoEventoBitacora;
	private String descripcion;
	private Set<BitacoraTrack> bitacoraTracks = new HashSet<BitacoraTrack>(0);

	public TipoEventoBitacora() {
	}

	public TipoEventoBitacora(short idTipoEventoBitacora) {
		this.idTipoEventoBitacora = idTipoEventoBitacora;
	}

	public TipoEventoBitacora(short idTipoEventoBitacora, String descripcion, Set<BitacoraTrack> bitacoraTracks) {
		this.idTipoEventoBitacora = idTipoEventoBitacora;
		this.descripcion = descripcion;
		this.bitacoraTracks = bitacoraTracks;
	}

	@Id

	@Column(name = "id_tipo_evento_bitacora", unique = true, nullable = false)
	public short getIdTipoEventoBitacora() {
		return this.idTipoEventoBitacora;
	}

	public void setIdTipoEventoBitacora(short idTipoEventoBitacora) {
		this.idTipoEventoBitacora = idTipoEventoBitacora;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEventoBitacora")
	public Set<BitacoraTrack> getBitacoraTracks() {
		return this.bitacoraTracks;
	}

	public void setBitacoraTracks(Set<BitacoraTrack> bitacoraTracks) {
		this.bitacoraTracks = bitacoraTracks;
	}

}
