package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAviso generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_AVISO")
public class TipoAviso implements java.io.Serializable {

	private long idTipoAviso;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public TipoAviso() {
	}

	public TipoAviso(long idTipoAviso, String descripcion,
			boolean estatusRegistro) {
		this.idTipoAviso = idTipoAviso;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoAviso(long idTipoAviso, String descripcion, String significado,
			boolean estatusRegistro, Set<Aviso> avisos) {
		this.idTipoAviso = idTipoAviso;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "ID_TIPO_AVISO", unique = true, nullable = false)
	public long getIdTipoAviso() {
		return this.idTipoAviso;
	}

	public void setIdTipoAviso(long idTipoAviso) {
		this.idTipoAviso = idTipoAviso;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAviso")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

}
