package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoEventoReceptor generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_EVENTO_RECEPTOR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_receptor", "id_tipo_evento" }))
public class TipoEventoReceptor implements java.io.Serializable {

	private long idTipoEventoReceptor;
	private Receptor receptor;
	private TipoEvento tipoEvento;

	public TipoEventoReceptor() {
	}

	public TipoEventoReceptor(long idTipoEventoReceptor, Receptor receptor,
			TipoEvento tipoEvento) {
		this.idTipoEventoReceptor = idTipoEventoReceptor;
		this.receptor = receptor;
		this.tipoEvento = tipoEvento;
	}

	@Id
	@Column(name = "ID_TIPO_EVENTO_RECEPTOR", unique = true, nullable = false)
	public long getIdTipoEventoReceptor() {
		return this.idTipoEventoReceptor;
	}

	public void setIdTipoEventoReceptor(long idTipoEventoReceptor) {
		this.idTipoEventoReceptor = idTipoEventoReceptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RECEPTOR", nullable = false)
	public Receptor getReceptor() {
		return this.receptor;
	}

	public void setReceptor(Receptor receptor) {
		this.receptor = receptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_EVENTO", nullable = false)
	public TipoEvento getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(TipoEvento tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

}
