package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVale generated by hbm2java
 */
@Entity
@Table(name = "tipo_vale")
public class TipoVale implements java.io.Serializable {

	private long idTipoVale;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Vale> vales = new HashSet<Vale>(0);

	public TipoVale() {
	}

	public TipoVale(long idTipoVale) {
		this.idTipoVale = idTipoVale;
	}

	public TipoVale(long idTipoVale, String descripcion,
			Boolean estatusRegistro, Set<Vale> vales) {
		this.idTipoVale = idTipoVale;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.vales = vales;
	}

	@Id
	@Column(name = "id_tipo_vale", unique = true, nullable = false)
	public long getIdTipoVale() {
		return this.idTipoVale;
	}

	public void setIdTipoVale(long idTipoVale) {
		this.idTipoVale = idTipoVale;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVale")
	public Set<Vale> getVales() {
		return this.vales;
	}

	public void setVales(Set<Vale> vales) {
		this.vales = vales;
	}

}
