package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoRelacionPosicion generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_RELACION_POSICION")
public class TipoRelacionPosicion implements java.io.Serializable {

	private long idTipoRelacionPosicion;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<RelacionPosicion> relacionPosicions = new HashSet<RelacionPosicion>(
			0);

	public TipoRelacionPosicion() {
	}

	public TipoRelacionPosicion(long idTipoRelacionPosicion,
			boolean estatusRegistro) {
		this.idTipoRelacionPosicion = idTipoRelacionPosicion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoRelacionPosicion(long idTipoRelacionPosicion,
			String descripcion, String significado, boolean estatusRegistro,
			Set<RelacionPosicion> relacionPosicions) {
		this.idTipoRelacionPosicion = idTipoRelacionPosicion;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.relacionPosicions = relacionPosicions;
	}

	@Id
	@Column(name = "ID_TIPO_RELACION_POSICION", unique = true, nullable = false)
	public long getIdTipoRelacionPosicion() {
		return this.idTipoRelacionPosicion;
	}

	public void setIdTipoRelacionPosicion(long idTipoRelacionPosicion) {
		this.idTipoRelacionPosicion = idTipoRelacionPosicion;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoRelacionPosicion")
	public Set<RelacionPosicion> getRelacionPosicions() {
		return this.relacionPosicions;
	}

	public void setRelacionPosicions(Set<RelacionPosicion> relacionPosicions) {
		this.relacionPosicions = relacionPosicions;
	}

}
