package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEstatusPadres generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_ESTATUS_PADRES")
public class TipoEstatusPadres implements java.io.Serializable {

	private long idTipoEstatusPadres;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public TipoEstatusPadres() {
	}

	public TipoEstatusPadres(long idTipoEstatusPadres, String descripcion,
			boolean estatusRegistro) {
		this.idTipoEstatusPadres = idTipoEstatusPadres;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoEstatusPadres(long idTipoEstatusPadres, String descripcion,
			String significado, boolean estatusRegistro, Set<Persona> personas) {
		this.idTipoEstatusPadres = idTipoEstatusPadres;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.personas = personas;
	}

	@Id
	@Column(name = "ID_TIPO_ESTATUS_PADRES", unique = true, nullable = false)
	public long getIdTipoEstatusPadres() {
		return this.idTipoEstatusPadres;
	}

	public void setIdTipoEstatusPadres(long idTipoEstatusPadres) {
		this.idTipoEstatusPadres = idTipoEstatusPadres;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEstatusPadres")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
