package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPlan generated by hbm2java
 */
@Entity
@Table(name = "tipo_plan")
public class TipoPlan implements java.io.Serializable {

	private long idTipoPlan;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Plan> plans = new HashSet<Plan>(0);

	public TipoPlan() {
	}

	public TipoPlan(long idTipoPlan) {
		this.idTipoPlan = idTipoPlan;
	}

	public TipoPlan(long idTipoPlan, String descripcion,
			Boolean estatusRegistro, Set<Plan> plans) {
		this.idTipoPlan = idTipoPlan;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.plans = plans;
	}

	@Id
	@Column(name = "id_tipo_plan", unique = true, nullable = false)
	public long getIdTipoPlan() {
		return this.idTipoPlan;
	}

	public void setIdTipoPlan(long idTipoPlan) {
		this.idTipoPlan = idTipoPlan;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPlan")
	public Set<Plan> getPlans() {
		return this.plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}

}
