package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVivienda generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_VIVIENDA")
public class TipoVivienda implements java.io.Serializable {

	private long idTipoVivienda;
	private String descripcion;
	private String significado;
	private BigDecimal ponderacion;
	private boolean estatusRegistro;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public TipoVivienda() {
	}

	public TipoVivienda(long idTipoVivienda, String descripcion,
			BigDecimal ponderacion) {
		this.idTipoVivienda = idTipoVivienda;
		this.descripcion = descripcion;
		this.ponderacion = ponderacion;
	}

	public TipoVivienda(long idTipoVivienda, String descripcion,
			String significado, BigDecimal ponderacion,
			boolean estatusRegistro, Set<Persona> personas) {
		this.idTipoVivienda = idTipoVivienda;
		this.descripcion = descripcion;
		this.significado = significado;
		this.ponderacion = ponderacion;
		this.estatusRegistro = estatusRegistro;
		this.personas = personas;
	}

	@Id
	@Column(name = "ID_TIPO_VIVIENDA", unique = true, nullable = false)
	public long getIdTipoVivienda() {
		return this.idTipoVivienda;
	}

	public void setIdTipoVivienda(long idTipoVivienda) {
		this.idTipoVivienda = idTipoVivienda;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "PONDERACION", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(BigDecimal ponderacion) {
		this.ponderacion = ponderacion;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVivienda")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
