package net.tce.model;

// Generated Oct 13, 2015 5:56:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoHabilidad generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_HABILIDAD")
public class TipoHabilidad implements java.io.Serializable {

	private long idTipoHabilidad;
	private String descripcion;
	private boolean estatusRegistro;
	private Set<Habilidadpos> habilidadposes = new HashSet<Habilidadpos>(0);

	public TipoHabilidad() {
	}

	public TipoHabilidad(long idTipoHabilidad, String descripcion,
			boolean estatusRegistro) {
		this.idTipoHabilidad = idTipoHabilidad;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoHabilidad(long idTipoHabilidad, String descripcion,
			boolean estatusRegistro, Set<Habilidadpos> habilidadposes) {
		this.idTipoHabilidad = idTipoHabilidad;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.habilidadposes = habilidadposes;
	}

	@Id
	@Column(name = "ID_TIPO_HABILIDAD", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdTipoHabilidad() {
		return this.idTipoHabilidad;
	}

	public void setIdTipoHabilidad(long idTipoHabilidad) {
		this.idTipoHabilidad = idTipoHabilidad;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS_REGISTRO", nullable = false, precision = 1, scale = 0)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoHabilidad")
	public Set<Habilidadpos> getHabilidadposes() {
		return this.habilidadposes;
	}

	public void setHabilidadposes(Set<Habilidadpos> habilidadposes) {
		this.habilidadposes = habilidadposes;
	}

}
