package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPerfil generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_PERFIL")
public class TipoPerfil implements java.io.Serializable {

	private long idTipoPerfil;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public TipoPerfil() {
	}

	public TipoPerfil(long idTipoPerfil, String descripcion,
			boolean estatusRegistro) {
		this.idTipoPerfil = idTipoPerfil;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoPerfil(long idTipoPerfil, String descripcion,
			String significado, boolean estatusRegistro, Set<Perfil> perfils) {
		this.idTipoPerfil = idTipoPerfil;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.perfils = perfils;
	}

	@Id
	@Column(name = "ID_TIPO_PERFIL", unique = true, nullable = false)
	public long getIdTipoPerfil() {
		return this.idTipoPerfil;
	}

	public void setIdTipoPerfil(long idTipoPerfil) {
		this.idTipoPerfil = idTipoPerfil;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPerfil")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
