package net.tce.model;

// Generated Sep 26, 2017 2:27:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSeguro generated by hbm2java
 */
@Entity
@Table(name = "tipo_seguro")
public class TipoSeguro implements java.io.Serializable {

	private long idTipoSeguro;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<Seguro> seguros = new HashSet<Seguro>(0);

	public TipoSeguro() {
	}

	public TipoSeguro(long idTipoSeguro) {
		this.idTipoSeguro = idTipoSeguro;
	}

	public TipoSeguro(long idTipoSeguro, String descripcion,
			Boolean estatusRegistro, Set<Seguro> seguros) {
		this.idTipoSeguro = idTipoSeguro;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.seguros = seguros;
	}

	@Id
	@Column(name = "id_tipo_seguro", unique = true, nullable = false)
	public long getIdTipoSeguro() {
		return this.idTipoSeguro;
	}

	public void setIdTipoSeguro(long idTipoSeguro) {
		this.idTipoSeguro = idTipoSeguro;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSeguro")
	public Set<Seguro> getSeguros() {
		return this.seguros;
	}

	public void setSeguros(Set<Seguro> seguros) {
		this.seguros = seguros;
	}

}
