package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContacto generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_CONTACTO")
public class TipoContacto implements java.io.Serializable {

	private long idTipoContacto;
	private ClasificacionContacto clasificacionContacto;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Contacto> contactos = new HashSet<Contacto>(0);

	public TipoContacto() {
	}

	public TipoContacto(long idTipoContacto,
			ClasificacionContacto clasificacionContacto, boolean estatusRegistro) {
		this.idTipoContacto = idTipoContacto;
		this.clasificacionContacto = clasificacionContacto;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoContacto(long idTipoContacto,
			ClasificacionContacto clasificacionContacto, String descripcion,
			String significado, boolean estatusRegistro, Set<Contacto> contactos) {
		this.idTipoContacto = idTipoContacto;
		this.clasificacionContacto = clasificacionContacto;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.contactos = contactos;
	}

	@Id
	@Column(name = "ID_TIPO_CONTACTO", unique = true, nullable = false)
	public long getIdTipoContacto() {
		return this.idTipoContacto;
	}

	public void setIdTipoContacto(long idTipoContacto) {
		this.idTipoContacto = idTipoContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLASIFICACION_CONTACTO", nullable = false)
	public ClasificacionContacto getClasificacionContacto() {
		return this.clasificacionContacto;
	}

	public void setClasificacionContacto(
			ClasificacionContacto clasificacionContacto) {
		this.clasificacionContacto = clasificacionContacto;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

}
