package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPrecision generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_PRECISION")
public class TipoPrecision implements java.io.Serializable {

	private long idTipoPrecision;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);
	private Set<BitacoraDomicilio> bitacoraDomicilios = new HashSet<BitacoraDomicilio>(
			0);

	public TipoPrecision() {
	}

	public TipoPrecision(long idTipoPrecision, String descripcion) {
		this.idTipoPrecision = idTipoPrecision;
		this.descripcion = descripcion;
	}

	public TipoPrecision(long idTipoPrecision, String descripcion,
			String significado, boolean estatusRegistro,
			Set<Domicilio> domicilios, Set<BitacoraDomicilio> bitacoraDomicilios) {
		this.idTipoPrecision = idTipoPrecision;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.domicilios = domicilios;
		this.bitacoraDomicilios = bitacoraDomicilios;
	}

	@Id
	@Column(name = "id_tipo_precision", unique = true, nullable = false)
	public long getIdTipoPrecision() {
		return this.idTipoPrecision;
	}

	public void setIdTipoPrecision(long idTipoPrecision) {
		this.idTipoPrecision = idTipoPrecision;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrecision")
	public Set<Domicilio> getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Set<Domicilio> domicilios) {
		this.domicilios = domicilios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrecision")
	public Set<BitacoraDomicilio> getBitacoraDomicilios() {
		return this.bitacoraDomicilios;
	}

	public void setBitacoraDomicilios(Set<BitacoraDomicilio> bitacoraDomicilios) {
		this.bitacoraDomicilios = bitacoraDomicilios;
	}


}
