package net.tce.model;

// Generated Dec 21, 2017 7:05:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPrestacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_prestacion")
public class TipoPrestacion implements java.io.Serializable {

	private long idTipoPrestacion;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<Posicion> posicions = new HashSet<Posicion>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);
	private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(
			0);
	private Set<BitacoraPosicion> bitacoraPosicions = new HashSet<BitacoraPosicion>(
			0);

	public TipoPrestacion() {
	}

	public TipoPrestacion(long idTipoPrestacion, String descripcion) {
		this.idTipoPrestacion = idTipoPrestacion;
		this.descripcion = descripcion;
	}

	public TipoPrestacion(long idTipoPrestacion, String descripcion,
			String significado, boolean estatusRegistro,
			Set<Posicion> posicions, Set<Persona> personas,
			Set<ExperienciaLaboral> experienciaLaborals,
			Set<BitacoraPosicion> bitacoraPosicions) {
		this.idTipoPrestacion = idTipoPrestacion;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.posicions = posicions;
		this.personas = personas;
		this.experienciaLaborals = experienciaLaborals;
		this.bitacoraPosicions = bitacoraPosicions;
	}

	@Id
	@Column(name = "id_tipo_prestacion", unique = true, nullable = false)
	public long getIdTipoPrestacion() {
		return this.idTipoPrestacion;
	}

	public void setIdTipoPrestacion(long idTipoPrestacion) {
		this.idTipoPrestacion = idTipoPrestacion;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "significado", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "estatus_registro", nullable = false)
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrestacion")
	public Set<Posicion> getPosicions() {
		return this.posicions;
	}

	public void setPosicions(Set<Posicion> posicions) {
		this.posicions = posicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrestacion")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrestacion")
	public Set<ExperienciaLaboral> getExperienciaLaborals() {
		return this.experienciaLaborals;
	}

	public void setExperienciaLaborals(
			Set<ExperienciaLaboral> experienciaLaborals) {
		this.experienciaLaborals = experienciaLaborals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPrestacion")
	public Set<BitacoraPosicion> getBitacoraPosicions() {
		return this.bitacoraPosicions;
	}

	public void setBitacoraPosicions(Set<BitacoraPosicion> bitacoraPosicions) {
		this.bitacoraPosicions = bitacoraPosicions;
	}

}
