package net.tce.model;

// Generated Sep 11, 2018 12:40:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoModeloRsc generated by hbm2java
 */
@Entity
@Table(name = "tipo_modelo_rsc")
public class TipoModeloRsc implements java.io.Serializable {

	private long idTipoModeloRsc;
	private String descripcion;
	private Boolean estatusRegistro;
	private Set<ModeloRsc> modeloRscs = new HashSet<ModeloRsc>(0);

	public TipoModeloRsc() {
	}

	public TipoModeloRsc(long idTipoModeloRsc) {
		this.idTipoModeloRsc = idTipoModeloRsc;
	}

	public TipoModeloRsc(long idTipoModeloRsc, String descripcion,
			Boolean estatusRegistro, Set<ModeloRsc> modeloRscs) {
		this.idTipoModeloRsc = idTipoModeloRsc;
		this.descripcion = descripcion;
		this.estatusRegistro = estatusRegistro;
		this.modeloRscs = modeloRscs;
	}

	@Id
	@Column(name = "id_tipo_modelo_rsc", unique = true, nullable = false)
	public long getIdTipoModeloRsc() {
		return this.idTipoModeloRsc;
	}

	public void setIdTipoModeloRsc(long idTipoModeloRsc) {
		this.idTipoModeloRsc = idTipoModeloRsc;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus_registro", nullable = false)
	public Boolean getEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(Boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoModeloRsc")
	public Set<ModeloRsc> getModeloRscs() {
		return this.modeloRscs;
	}

	public void setModeloRscs(Set<ModeloRsc> modeloRscs) {
		this.modeloRscs = modeloRscs;
	}

}
