package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContenido generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_CONTENIDO")
public class TipoContenido implements java.io.Serializable {

	private long idTipoContenido;
	private String descripcion;
	private String significado;
	private Integer minimo;
	private Integer maximo;
	private Long volumenMinimo;
	private Long volumenMaximo;
	private boolean estatusRegistro;
	private Set<TipoContenidoArchivo> tipoContenidoArchivos = new HashSet<TipoContenidoArchivo>(
			0);

	public TipoContenido() {
	}

	public TipoContenido(long idTipoContenido, String descripcion) {
		this.idTipoContenido = idTipoContenido;
		this.descripcion = descripcion;
	}

	public TipoContenido(long idTipoContenido, String descripcion,
			String significado, Integer minimo, Integer maximo,
			Long volumenMinimo, Long volumenMaximo, boolean estatusRegistro,
			Set<TipoContenidoArchivo> tipoContenidoArchivos) {
		this.idTipoContenido = idTipoContenido;
		this.descripcion = descripcion;
		this.significado = significado;
		this.minimo = minimo;
		this.maximo = maximo;
		this.volumenMinimo = volumenMinimo;
		this.volumenMaximo = volumenMaximo;
		this.estatusRegistro = estatusRegistro;
		this.tipoContenidoArchivos = tipoContenidoArchivos;
	}

	@Id
	@Column(name = "ID_TIPO_CONTENIDO", unique = true, nullable = false)
	public long getIdTipoContenido() {
		return this.idTipoContenido;
	}

	public void setIdTipoContenido(long idTipoContenido) {
		this.idTipoContenido = idTipoContenido;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "MINIMO")
	public Integer getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Integer minimo) {
		this.minimo = minimo;
	}

	@Column(name = "MAXIMO")
	public Integer getMaximo() {
		return this.maximo;
	}

	public void setMaximo(Integer maximo) {
		this.maximo = maximo;
	}

	@Column(name = "VOLUMEN_MINIMO")
	public Long getVolumenMinimo() {
		return this.volumenMinimo;
	}

	public void setVolumenMinimo(Long volumenMinimo) {
		this.volumenMinimo = volumenMinimo;
	}

	@Column(name = "VOLUMEN_MAXIMO")
	public Long getVolumenMaximo() {
		return this.volumenMaximo;
	}

	public void setVolumenMaximo(Long volumenMaximo) {
		this.volumenMaximo = volumenMaximo;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContenido")
	public Set<TipoContenidoArchivo> getTipoContenidoArchivos() {
		return this.tipoContenidoArchivos;
	}

	public void setTipoContenidoArchivos(
			Set<TipoContenidoArchivo> tipoContenidoArchivos) {
		this.tipoContenidoArchivos = tipoContenidoArchivos;
	}

}
