package net.tce.model;

// Generated Feb 2, 2015 3:37:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoRelacionEmpresa generated by hbm2java
 */
@Entity @SuppressWarnings("serial")
@Table(name = "TIPO_RELACION_EMPRESA")
public class TipoRelacionEmpresa implements java.io.Serializable {

	private long idTipoRelacionEmpresa;
	private String descripcion;
	private String significado;
	private boolean estatusRegistro;
	private Set<RelacionEmpresa> relacionEmpresas = new HashSet<RelacionEmpresa>(
			0);

	public TipoRelacionEmpresa() {
	}

	public TipoRelacionEmpresa(long idTipoRelacionEmpresa,
			boolean estatusRegistro) {
		this.idTipoRelacionEmpresa = idTipoRelacionEmpresa;
		this.estatusRegistro = estatusRegistro;
	}

	public TipoRelacionEmpresa(long idTipoRelacionEmpresa, String descripcion,
			String significado, boolean estatusRegistro,
			Set<RelacionEmpresa> relacionEmpresas) {
		this.idTipoRelacionEmpresa = idTipoRelacionEmpresa;
		this.descripcion = descripcion;
		this.significado = significado;
		this.estatusRegistro = estatusRegistro;
		this.relacionEmpresas = relacionEmpresas;
	}

	@Id
	@Column(name = "ID_TIPO_RELACION_EMPRESA", unique = true, nullable = false)
	public long getIdTipoRelacionEmpresa() {
		return this.idTipoRelacionEmpresa;
	}

	public void setIdTipoRelacionEmpresa(long idTipoRelacionEmpresa) {
		this.idTipoRelacionEmpresa = idTipoRelacionEmpresa;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGNIFICADO", length = 1500)
	public String getSignificado() {
		return this.significado;
	}

	public void setSignificado(String significado) {
		this.significado = significado;
	}

	@Column(name = "ESTATUS_REGISTRO")
	public boolean isEstatusRegistro() {
		return this.estatusRegistro;
	}

	public void setEstatusRegistro(boolean estatusRegistro) {
		this.estatusRegistro = estatusRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoRelacionEmpresa")
	public Set<RelacionEmpresa> getRelacionEmpresas() {
		return this.relacionEmpresas;
	}

	public void setRelacionEmpresas(Set<RelacionEmpresa> relacionEmpresas) {
		this.relacionEmpresas = relacionEmpresas;
	}

}
