package net.tce.model;

// Generated Sep 11, 2018 12:40:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicUpdate;

import net.tce.util.Constante;

/**
 * TrackingMonitor generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "tracking_monitor")
public class TrackingMonitor implements java.io.Serializable {

	private long idTrackingMonitor;
	private TrackingPostulante trackingPostulante;
	private EstadoTracking estadoTracking;
	private RelacionEmpresaPersona relacionEmpresaPersona;
	private Monitor monitor;
	private String comentario;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean oculto;
	private boolean isTransDifRol;
	private boolean enGrupo;
	private boolean notificacionEnviada;
	private Set<Contenido> contenidos = new HashSet<Contenido>(0);
	private Set<Recordatorio> recordatorios = new HashSet<Recordatorio>(0);

	public TrackingMonitor() {
	}

	public TrackingMonitor(long idTrackingMonitor, EstadoTracking estadoTracking,
			RelacionEmpresaPersona relacionEmpresaPersona, Monitor monitor, boolean oculto, boolean isTransDifRol,
			boolean enGrupo, boolean notificacionEnviada) {
		this.idTrackingMonitor = idTrackingMonitor;
		this.estadoTracking = estadoTracking;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.monitor = monitor;
		this.oculto = oculto;
		this.isTransDifRol = isTransDifRol;
		this.enGrupo = enGrupo;
		this.notificacionEnviada = notificacionEnviada;
	}

	public TrackingMonitor(long idTrackingMonitor, TrackingPostulante trackingPostulante, EstadoTracking estadoTracking,
			RelacionEmpresaPersona relacionEmpresaPersona, Monitor monitor, String comentario, Date fechaInicio,
			Date fechaFin, boolean oculto, boolean isTransDifRol, boolean enGrupo, boolean notificacionEnviada,
			 Set<Contenido> contenidos, Set<Recordatorio> recordatorios) {
		this.idTrackingMonitor = idTrackingMonitor;
		this.trackingPostulante = trackingPostulante;
		this.estadoTracking = estadoTracking;
		this.relacionEmpresaPersona = relacionEmpresaPersona;
		this.monitor = monitor;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.oculto = oculto;
		this.isTransDifRol = isTransDifRol;
		this.enGrupo = enGrupo;
		this.notificacionEnviada = notificacionEnviada;
		this.contenidos = contenidos;
		this.recordatorios = recordatorios;
	}
	
	@Id
	@SequenceGenerator(name="seq_tracking_monitor", sequenceName=Constante.SECUENCIA_BD_TCK_MONITOR, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_tracking_monitor")
	@Column(name = "id_tracking_monitor", unique = true, nullable = false)
	public long getIdTrackingMonitor() {
		return this.idTrackingMonitor;
	}

	public void setIdTrackingMonitor(long idTrackingMonitor) {
		this.idTrackingMonitor = idTrackingMonitor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_tracking", nullable = false)
	public EstadoTracking getEstadoTracking() {
		return this.estadoTracking;
	}

	public void setEstadoTracking(EstadoTracking estadoTracking) {
		this.estadoTracking = estadoTracking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_monitor", nullable = false)
	public Monitor getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tracking_postulante")
	public TrackingPostulante getTrackingPostulante() {
		return this.trackingPostulante;
	}

	public void setTrackingPostulante(TrackingPostulante trackingPostulante) {
		this.trackingPostulante = trackingPostulante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "postulante", nullable = false)
	public RelacionEmpresaPersona getRelacionEmpresaPersona() {
		return this.relacionEmpresaPersona;
	}

	public void setRelacionEmpresaPersona(
			RelacionEmpresaPersona relacionEmpresaPersona) {
		this.relacionEmpresaPersona = relacionEmpresaPersona;
	}

	@Column(name = "comentario", length = 1500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", length = 29)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", length = 29)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	@Column(name = "oculto", nullable = false)
	public boolean isOculto() {
		return this.oculto;
	}

	public void setOculto(boolean oculto) {
		this.oculto = oculto;
	}
	
	@Column(name = "is_trans_dif_rol", nullable = false)
	public boolean isIsTransDifRol() {
		return this.isTransDifRol;
	}

	public void setIsTransDifRol(boolean isTransDifRol) {
		this.isTransDifRol = isTransDifRol;
	}
	
	@Column(name = "en_grupo", nullable = false)
	public boolean isEnGrupo() {
		return this.enGrupo;
	}

	public void setEnGrupo(boolean enGrupo) {
		this.enGrupo = enGrupo;
	}
	
	@Column(name = "notificacion_enviada", nullable = false)
	public boolean isNotificacionEnviada() {
		return this.notificacionEnviada;
	}

	public void setNotificacionEnviada(boolean notificacionEnviada) {
		this.notificacionEnviada = notificacionEnviada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trackingMonitor")
	public Set<Contenido> getContenidos() {
		return this.contenidos;
	}

	public void setContenidos(Set<Contenido> contenidos) {
		this.contenidos = contenidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trackingMonitor")
	public Set<Recordatorio> getRecordatorios() {
		return this.recordatorios;
	}

	public void setRecordatorios(Set<Recordatorio> recordatorios) {
		this.recordatorios = recordatorios;
	}
}
