package net.tce.model;

// Generated Oct 5, 2017 6:53:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import net.tce.util.Constante;

import org.hibernate.annotations.DynamicUpdate;

/**
 * Vale generated by hbm2java
 */
@Entity
@Table(name = "vale")
@DynamicUpdate
public class Vale implements java.io.Serializable {

	private long idVale;
	private TipoVale tipoVale;
	private Compensacion compensacion;
	private Integer cantidad;
	private boolean activo;

	public Vale() {
	}

	public Vale(long idVale, Compensacion compensacion, boolean activo) {
		this.idVale = idVale;
		this.compensacion = compensacion;
		this.activo = activo;
	}

	public Vale(long idVale, TipoVale tipoVale, Compensacion compensacion,
			Integer cantidad, boolean activo) {
		this.idVale = idVale;
		this.tipoVale = tipoVale;
		this.compensacion = compensacion;
		this.cantidad = cantidad;
		this.activo = activo;
	}


	@Id
	@SequenceGenerator(name="seq_vale", sequenceName=Constante.SECUENCIA_BD_VALE, initialValue=1, allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_vale")
	@Column(name = "id_vale", unique = true, nullable = false)
	public long getIdVale() {
		return this.idVale;
	}

	public void setIdVale(long idVale) {
		this.idVale = idVale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_vale")
	public TipoVale getTipoVale() {
		return this.tipoVale;
	}

	public void setTipoVale(TipoVale tipoVale) {
		this.tipoVale = tipoVale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Compensacion getCompensacion() {
		return this.compensacion;
	}

	public void setCompensacion(Compensacion compensacion) {
		this.compensacion = compensacion;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}
}
